SIMLIB/C++: src/_test_.cc File Reference
_test_.cc File Reference
Simple test model.
#include "simlib.h"
Classes
struct Test
class TestProcess
Macros
#define SIMLIB_DEBUG
#define I_REALLY_KNOW_HOW_TO_USE_WAITUNTIL
Functions
void Sample ()
int main ()
Variables
Constant F (1.0)
Test t (F)
TestProcess globalprocess
Sampler S (Sample, 1)
Detailed Description
Simple test model.
Definition in file _test_.cc.
Macro Definition Documentation
I_REALLY_KNOW_HOW_TO_USE_WAITUNTIL
#define I_REALLY_KNOW_HOW_TO_USE_WAITUNTIL
Definition at line 7 of file _test_.cc.
SIMLIB_DEBUG
#define SIMLIB_DEBUG
Definition at line 4 of file _test_.cc.
Function Documentation
main()
int main ()
Examples
_test_.cc, examples/ball.cc, examples/ball2.cc, examples/bessel.cc, examples/ctest.cc, examples/heating.cc, examples/lorenz.cc, examples/model2-timeout.cc, examples/model2.cc, examples/multiexp.cc, examples/rc.cc, examples/rlc.cc, examples/test3D.cc, examples/wheel.cc, and examples/wheel2.cc.
Definition at line 44 of file _test_.cc.
References simlib3::Process::Activate(), simlib3::Activate(), globalprocess, simlib3::Init(), simlib3::Print(), simlib3::Run(), simlib3::SetAccuracy(), simlib3::SetStep(), and simlib3::Time.
Sample()
void Sample ()
Examples
_test_.cc, examples/ball.cc, examples/ball2.cc, examples/bessel.cc, examples/ctest.cc, examples/heating.cc, examples/lorenz.cc, examples/multiexp.cc, examples/wheel.cc, and examples/wheel2.cc.
Definition at line 38 of file _test_.cc.
References simlib3::Print(), t, simlib3::T, Test::v, simlib3::Integrator::Value(), simlib3::Status::Value(), simlib3::aContiBlock::Value(), and Test::y.
Variable Documentation
F
Constant F(1.0) (1. 0)
Examples
_test_.cc, examples/ctest.cc, examples/wheel.cc, and examples/wheel2.cc.
globalprocess
TestProcess globalprocess
Examples
_test_.cc.
Definition at line 35 of file _test_.cc.
Referenced by main().
S
Sampler S(Sample, 1) (Sample , 1)
Examples
_test_.cc, examples/ball.cc, examples/ball2.cc, examples/bessel.cc, examples/ctest.cc, examples/heating.cc, examples/lorenz.cc, examples/wheel.cc, and examples/wheel2.cc.
t
Test t(F) (F)
Examples
_test_.cc, and examples/model2-timeout.cc.
Referenced by simlib3::Entity::Activate(), simlib3::Process::Activate(), simlib3::Event::Activate(), simlib3::EventNoticeAllocator::alloc(), simlib3::EventNotice::Create(), simlib3::CalendarQueue::estimate_bucket_width(), simlib3::CalendarQueue::Get(), simlib3::CalendarListImplementation::insert(), Sample(), simlib3::SQS::ScheduleAt(), simlib3::CalendarList::ScheduleAt(), simlib3::CalendarQueue::ScheduleAt(), simlib3::CalendarListImplementation::search(), simlib3::CalendarQueue::SearchMinTime(), simlib3::EventNotice::Set(), simlib3::Calendar::SetMinTime(), simlib3::CalendarQueue::time2bucket(), and simlib3::CalendarQueue::time2bucket_top().