SIMLIB/C++: simlib3::aContiBlock2D1 Class Reference
simlib3::aContiBlock2D1 Class Reference
SIMLIB/C++ 2D extension
continuous block with single input and alg.
#include <simlib2D.h>
Public Member Functions
aContiBlock2D1 (Input2D i)
Value2D InputValue ()
Input2D SetInput (Input2D i)
Public Member Functions inherited from simlib3::aContiBlock2D
aContiBlock2D ()
~aContiBlock2D ()
virtual void _Eval ()
virtual Value2D Value ()=0
void Print ()
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Attributes
Input2D input
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::aContiBlock2D
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
continuous block with single input and alg.
loop check
Definition at line 124 of file simlib2D.h.
Constructor & Destructor Documentation
aContiBlock2D1()
simlib3::aContiBlock2D1::aContiBlock2D1 (Input2D i) explicit
Definition at line 136 of file simlib2D.cc.
References AlgLoopDetected, input, and simlib3::SIMLIB_error().
Member Function Documentation
InputValue()
Value2D simlib3::aContiBlock2D1::InputValue () inline
Definition at line 128 of file simlib2D.h.
References input, and simlib3::Input2D::Value().
Referenced by simlib3::_Mul2D1D::Value(), simlib3::_Div2D::Value(), simlib3::_UMinus2D::Value(), simlib3::_Norm2D::Value(), and simlib3::Expression2D::Value().
SetInput()
Input2D simlib3::aContiBlock2D1::SetInput (Input2D i) inline
Definition at line 129 of file simlib2D.h.
References input, and simlib3::Input2D::Set().
Member Data Documentation
input
Input2D simlib3::aContiBlock2D1::input private
Definition at line 125 of file simlib2D.h.
Referenced by aContiBlock2D1(), InputValue(), and SetInput().
The documentation for this class was generated from the following files:
src/simlib2D.h
src/simlib2D.cc