SIMLIB/C++: simlib3::aContiBlock2D Class Reference
simlib3::aContiBlock2D Class Reference abstract
SIMLIB/C++ 2D extension
Abstract 2D block with single 2D output.
#include <simlib2D.h>
Public Member Functions
aContiBlock2D ()
~aContiBlock2D ()
virtual void _Eval ()
virtual Value2D Value ()=0
void Print ()
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Protected Attributes
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Private Member Functions
virtual void Eval ()
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Detailed Description
Abstract 2D block with single 2D output.
Definition at line 60 of file simlib2D.h.
Constructor & Destructor Documentation
aContiBlock2D()
simlib3::aContiBlock2D::aContiBlock2D ()
Definition at line 92 of file simlib2D.cc.
References Dprintf.
~aContiBlock2D()
simlib3::aContiBlock2D::~aContiBlock2D ()
Definition at line 98 of file simlib2D.cc.
References Dprintf.
Member Function Documentation
_Eval()
void simlib3::aContiBlock2D::_Eval () virtual
Reimplemented in simlib3::_Add2D, simlib3::_Sub2D, simlib3::_Mul2D1D, simlib3::_Div2D, simlib3::_UMinus2D, and simlib3::_Norm2D.
Definition at line 113 of file simlib2D.cc.
References AlgLoopDetected, Eval(), isEvaluated, and simlib3::SIMLIB_error().
Eval()
virtual void simlib3::aContiBlock2D::Eval () inline private virtual
Definition at line 64 of file simlib2D.h.
Referenced by _Eval().
Print()
void simlib3::aContiBlock2D::Print ()
Definition at line 105 of file simlib2D.cc.
References simlib3::Value2D::Print(), and Value().
Value()
virtual Value2D simlib3::aContiBlock2D::Value () pure virtual
Implemented in simlib3::_Add2D, simlib3::_Sub2D, simlib3::_Mul2D1D, simlib3::_Div2D, simlib3::_UMinus2D, simlib3::_Norm2D, simlib3::Constant2D, simlib3::Variable2D, simlib3::Expression2D, simlib3::Adaptor2D, and simlib3::Integrator2D.
Referenced by Print(), and simlib3::Input2D::Value().
Member Data Documentation
isEvaluated
bool simlib3::aContiBlock2D::isEvaluated protected
Definition at line 62 of file simlib2D.h.
Referenced by _Eval().
The documentation for this class was generated from the following files:
src/simlib2D.h
src/simlib2D.cc