SIMLIB/C++: simlib3::IntegratorContainer Class Reference
simlib3::IntegratorContainer Class Reference
IntegratorContainer - internal container of integrators (singleton)
#include <simlib.h>
Public Types
typedef std::list< Integrator * >::iterator iterator
Static Public Member Functions
static bool isAny (void)
static size_t Size (void)
static iterator Begin (void)
static iterator End (void)
static iterator Insert (Integrator *ptr)
static void Erase (iterator it)
static void InitAll ()
static void EvaluateAll ()
static void LtoN ()
static void NtoL ()
Private Member Functions
IntegratorContainer ()
Static Private Member Functions
static std::list< Integrator * > * Instance (void)
Static Private Attributes
static std::list< Integrator * > * ListPtr =NULL
list of integrators
Detailed Description
IntegratorContainer - internal container of integrators (singleton)
Definition at line 986 of file simlib.h.
Member Typedef Documentation
iterator
typedef std::list<Integrator*>::iterator simlib3::IntegratorContainer::iterator
Definition at line 992 of file simlib.h.
Constructor & Destructor Documentation
IntegratorContainer()
simlib3::IntegratorContainer::IntegratorContainer () private
Member Function Documentation
Begin()
static iterator simlib3::IntegratorContainer::Begin (void) inline static
Definition at line 1002 of file simlib.h.
References Instance().
Referenced by simlib3::IntegrationMethod::FirstIntegrator(), simlib3::StatusMethod::GoToState(), simlib3::StatusMethod::RestoreState(), and simlib3::StatusMethod::StoreState().
End()
static iterator simlib3::IntegratorContainer::End (void) inline static
Definition at line 1006 of file simlib.h.
References Instance().
Referenced by simlib3::StatusMethod::GoToState(), simlib3::IntegrationMethod::LastIntegrator(), simlib3::StatusMethod::RestoreState(), and simlib3::StatusMethod::StoreState().
Erase()
void simlib3::IntegratorContainer::Erase (IntegratorContainer::iterator it) static
Definition at line 303 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::Integrator::~Integrator().
EvaluateAll()
void simlib3::IntegratorContainer::EvaluateAll () static
Definition at line 363 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::SIMLIB_Dynamic().
InitAll()
void simlib3::IntegratorContainer::InitAll () static
Definition at line 346 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::SIMLIB_ContinueInit().
Insert()
IntegratorContainer::iterator simlib3::IntegratorContainer::Insert (Integrator * ptr) static
Definition at line 292 of file intg.cc.
References Dprintf, Instance(), and ListPtr.
Referenced by simlib3::Integrator::CtrInit().
Instance()
std::list< Integrator * > * simlib3::IntegratorContainer::Instance (void) static private
Definition at line 277 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by Begin(), End(), and Insert().
isAny()
static bool simlib3::IntegratorContainer::isAny (void) inline static
Definition at line 994 of file simlib.h.
References ListPtr.
Referenced by simlib3::Run(), simlib3::SIMLIB_ContinueInit(), and simlib3::IntegrationMethod::StepSim().
LtoN()
void simlib3::IntegratorContainer::LtoN () static
Definition at line 331 of file intg.cc.
References Dprintf, and ListPtr.
NtoL()
void simlib3::IntegratorContainer::NtoL () static
Definition at line 316 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::IntegrationMethod::Prepare(), and simlib3::IntegrationMethod::Summarize().
Size()
static size_t simlib3::IntegratorContainer::Size (void) inline static
Definition at line 998 of file simlib.h.
References ListPtr.
Referenced by simlib3::Integrator::Integrator(), simlib3::Integrator::Integrator(), simlib3::Integrator::Integrator(), simlib3::IntegrationMethod::PrepareStep(), and simlib3::Integrator::~Integrator().
Member Data Documentation
ListPtr
std::list< Integrator * > * simlib3::IntegratorContainer::ListPtr =NULL static private
list of integrators
Definition at line 988 of file simlib.h.
Referenced by Erase(), EvaluateAll(), InitAll(), Insert(), Instance(), isAny(), LtoN(), NtoL(), and Size().
The documentation for this class was generated from the following files:
src/simlib.h
src/intg.cc