SIMLIB/C++: simlib3::aContiBlock1 Class Reference
simlib3::aContiBlock1 Class Reference
SIMLIB/C++
base for continuous blocks with single input and algebraic loop check
#include <simlib.h>
Public Member Functions
aContiBlock1 (Input i)
constructor for blocks with single input
double InputValue ()
Public Member Functions inherited from simlib3::aContiBlock
aContiBlock ()
virtual void _Eval ()
evaluate block (with loop detection)
virtual double Value ()=0
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Attributes
Input input
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::aContiBlock
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
base for continuous blocks with single input and algebraic loop check
Definition at line 940 of file simlib.h.
Constructor & Destructor Documentation
aContiBlock1()
simlib3::aContiBlock1::aContiBlock1 (Input i) explicit
constructor for blocks with single input
Definition at line 61 of file continuous.cc.
References AlgLoopDetected, input, and simlib3::SIMLIB_error().
Member Function Documentation
InputValue()
double simlib3::aContiBlock1::InputValue () inline
Definition at line 944 of file simlib.h.
References input, and simlib3::Input::Value().
Referenced by simlib3::Status::Eval(), simlib3::Hyst::Eval(), simlib3::Blash::Eval(), simlib3::Relay::Eval(), simlib3::Delay::Sample(), simlib3::ZDelay::SampleIn(), simlib3::_UMinus::Value(), simlib3::Expression::Value(), simlib3::Function1::Value(), simlib3::Lim::Value(), simlib3::Insv::Value(), simlib3::Qntzr::Value(), simlib3::Frict::Value(), simlib3::Rline::Value(), simlib3::Iterations::Value(), simlib3::Bisect::Value(), simlib3::RegulaFalsi::Value(), and simlib3::Newton::Value().
Member Data Documentation
input
Input simlib3::aContiBlock1::input private
Definition at line 941 of file simlib.h.
Referenced by aContiBlock1(), and InputValue().
The documentation for this class was generated from the following files:
src/simlib.h
src/continuous.cc