SIMLIB/C++: simlib3::_XYpart Class Reference
simlib3::_XYpart Class Reference
Public Types
enum WhichPart { x , y }
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Public Member Functions
_XYpart (Input2D a, WhichPart w)
virtual double Value () override
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::aContiBlock
aContiBlock ()
virtual void _Eval ()
evaluate block (with loop detection)
virtual double Value ()=0
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Member Functions
virtual void _Eval () override
evaluate block (with loop detection)
Private Attributes
Input2D input
WhichPart which
Additional Inherited Members
Protected Attributes inherited from simlib3::aContiBlock
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
Definition at line 395 of file simlib2D.cc.
Member Enumeration Documentation
WhichPart
enum simlib3::_XYpart::WhichPart
Enumerator
x
y
Definition at line 399 of file simlib2D.cc.
Constructor & Destructor Documentation
_XYpart()
simlib3::_XYpart::_XYpart (Input2D a, WhichPart w) inline
Definition at line 400 of file simlib2D.cc.
Member Function Documentation
_Eval()
virtual void simlib3::_XYpart::_Eval () inline override private virtual
evaluate block (with loop detection)
evaluation with algebraic loop detection
Reimplemented from simlib3::aContiBlock.
Definition at line 396 of file simlib2D.cc.
Value()
virtual double simlib3::_XYpart::Value () inline override virtual
get block output value
this method should be defined in classes derived from aContiBlock
Implements simlib3::aContiBlock.
Definition at line 401 of file simlib2D.cc.
References input, SIMLIB_internal_error, simlib3::Input2D::Value(), which, x, simlib3::Value2D::x(), y, and simlib3::Value2D::y().
Member Data Documentation
input
Input2D simlib3::_XYpart::input private
Definition at line 397 of file simlib2D.cc.
Referenced by Value().
which
WhichPart simlib3::_XYpart::which private
Definition at line 411 of file simlib2D.cc.
Referenced by Value().
The documentation for this class was generated from the following file:
src/simlib2D.cc