SIMLIB/C++: simlib3::IntegrationMethod Class Reference
simlib3::IntegrationMethod Class Reference abstract
IntegrationMethod - Abstract base class for integration methods.
#include <simlib.h>
Classes
class Memory
Public Member Functions
IntegrationMethod (const char *name)
register method to list of methods and name it
virtual ~IntegrationMethod ()
destroy integration method (remove from list)
virtual bool IsSingleStep (void)=0
virtual void TurnOff (void)
turn off integration method: flush memories etc...
virtual void Integrate (void)=0
virtual bool PrepareStep (void)
prepare object for integration step
virtual void Resize (size_t size)
resize all the memories to the given size
Static Public Member Functions
static void StepSim (void)
step of numerical integration method
static void IntegrationDone (void)
static void SetMethod (const char *name)
set method which will be used
static const char * GetMethod (void)
static void InitStep (double step_frag)
initialize step
static void FunCall (double step_frag)
static void SetOptStep (double opt_step)
static void SetStepSize (double step_size)
static bool IsConditionFlag (void)
static int GetErrNo (void)
static void SetErrNo (int num)
Protected Types
typedef IntegratorContainer::iterator Iterator
Static Protected Member Functions
static Iterator FirstIntegrator (void)
static Iterator LastIntegrator (void)
static bool StateCond (void)
check on changes of state conditions
static IntegrationMethod * SearchMethod (const char *name)
search method in the list of registrated methods
Static Protected Attributes
static bool IsEndStepEvent =false
Private Member Functions
IntegrationMethod (const IntegrationMethod &)=delete
IntegrationMethod & operator= (const IntegrationMethod &)=delete
IntegrationMethod ()
IntegrationMethod (IntegrationMethod &)
Static Private Member Functions
static bool Prepare (void)
initialize integration step
static void Iterate (void)
compute new values of state blocks in model without integrators
static void Summarize (void)
set up new state after execution of integration step
Private Attributes
std::list< IntegrationMethod * >::iterator ItList
const char * method_name
size_t PrevINum
std::list< Memory * > MList
Static Private Attributes
static IntegrationMethod * CurrentMethodPtr = &rke
pointer to the method currently used "rke" is a predefined method (historical reasons, we need rk45)
static std::list< IntegrationMethod * > * MthLstPtr =NULL
static std::list< Memory * > * PtrMList
Friends
class Memory
Detailed Description
IntegrationMethod - Abstract base class for integration methods.
Definition at line 1058 of file simlib.h.
Member Typedef Documentation
Iterator
typedef IntegratorContainer::iterator simlib3::IntegrationMethod::Iterator protected
Definition at line 1080 of file simlib.h.
Constructor & Destructor Documentation
IntegrationMethod() [1/4]
simlib3::IntegrationMethod::IntegrationMethod (const IntegrationMethod &) private delete
IntegrationMethod() [2/4]
simlib3::IntegrationMethod::IntegrationMethod () private
IntegrationMethod() [3/4]
simlib3::IntegrationMethod::IntegrationMethod (IntegrationMethod &) private
IntegrationMethod() [4/4]
simlib3::IntegrationMethod::IntegrationMethod (const char * name) explicit
register method to list of methods and name it
Definition at line 194 of file numint.cc.
References Dprintf, ItList, method_name, MList, MthLstPtr, NI_MultDefMeth, PtrMList, and simlib3::SIMLIB_error().
~IntegrationMethod()
simlib3::IntegrationMethod::~IntegrationMethod () virtual
destroy integration method (remove from list)
Definition at line 222 of file numint.cc.
References Dprintf, ItList, method_name, MthLstPtr, and SIMLIB_internal_error.
Member Function Documentation
FirstIntegrator()
static Iterator simlib3::IntegrationMethod::FirstIntegrator (void) inline static protected
Definition at line 1081 of file simlib.h.
References simlib3::IntegratorContainer::Begin().
Referenced by simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), and simlib3::RKF8::Integrate().
FunCall()
void simlib3::IntegrationMethod::FunCall (double step_frag) static
Definition at line 337 of file numint.cc.
References _SetTime, simlib3::SIMLIB_DeltaTime, simlib3::SIMLIB_Dynamic(), simlib3::SIMLIB_StepSize, simlib3::SIMLIB_StepStartTime, and simlib3::Time.
GetErrNo()
int simlib3::IntegrationMethod::GetErrNo (void) static
Definition at line 322 of file numint.cc.
References simlib3::SIMLIB_ERRNO.
GetMethod()
static const char * simlib3::IntegrationMethod::GetMethod (void) inline static
Definition at line 1125 of file simlib.h.
References CurrentMethodPtr, and method_name.
Referenced by simlib3::GetMethod(), simlib3::GetStarter(), and simlib3::SetStarter().
InitStep()
void simlib3::IntegrationMethod::InitStep (double step_frag) static
initialize step
Definition at line 298 of file numint.cc.
References simlib3::max(), simlib3::min(), simlib3::SIMLIB_ContractStep, simlib3::SIMLIB_ContractStepFlag, simlib3::SIMLIB_MaxStep, simlib3::SIMLIB_MinStep, and simlib3::SIMLIB_StepSize.
Integrate()
virtual void simlib3::IntegrationMethod::Integrate (void) pure virtual
Implemented in simlib3::ABM4, simlib3::EULER, simlib3::FW, simlib3::RKE, simlib3::RKF3, simlib3::RKF5, and simlib3::RKF8.
Referenced by simlib3::ABM4::Integrate(), and StepSim().
IntegrationDone()
static void simlib3::IntegrationMethod::IntegrationDone (void) inline static
Definition at line 1121 of file simlib.h.
References CurrentMethodPtr, and TurnOff().
Referenced by simlib3::Run().
IsConditionFlag()
bool simlib3::IntegrationMethod::IsConditionFlag (void) static
Definition at line 317 of file numint.cc.
References simlib3::SIMLIB_ConditionFlag.
IsSingleStep()
virtual bool simlib3::IntegrationMethod::IsSingleStep (void) pure virtual
Implemented in simlib3::SingleStepMethod, and simlib3::MultiStepMethod.
Iterate()
void simlib3::IntegrationMethod::Iterate (void) static private
compute new values of state blocks in model without integrators
Definition at line 88 of file numint.cc.
References _SetTime, Dprintf, IsEndStepEvent, simlib3::StatusContainer::LtoN(), simlib3::max(), simlib3::SIMLIB_ContractStep, simlib3::SIMLIB_ContractStepFlag, simlib3::SIMLIB_DeltaTime, simlib3::SIMLIB_Dynamic(), simlib3::SIMLIB_MinStep, simlib3::SIMLIB_StepSize, simlib3::SIMLIB_StepStartTime, simlib3::aCondition::TestAll(), and simlib3::Time.
Referenced by StepSim().
LastIntegrator()
static Iterator simlib3::IntegrationMethod::LastIntegrator (void) inline static protected
Definition at line 1084 of file simlib.h.
References simlib3::IntegratorContainer::End().
Referenced by simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), and simlib3::RKF8::Integrate().
operator=()
IntegrationMethod & simlib3::IntegrationMethod::operator= (const IntegrationMethod &) private delete
Prepare()
bool simlib3::IntegrationMethod::Prepare (void) static private
initialize integration step
Definition at line 128 of file numint.cc.
References CurrentMethodPtr, Dprintf, IsEndStepEvent, simlib3::NextTime, NI_IlStepSize, simlib3::IntegratorContainer::NtoL(), simlib3::StatusContainer::NtoL(), PrepareStep(), simlib3::SIMLIB_ConditionFlag, simlib3::SIMLIB_DeltaTime, simlib3::SIMLIB_Dynamic(), simlib3::SIMLIB_error(), simlib3::SIMLIB_OptStep, simlib3::SIMLIB_ResetStatus, simlib3::SIMLIB_StepSize, simlib3::SIMLIB_StepStartTime, simlib3::aCondition::TestAll(), and simlib3::Time.
Referenced by StepSim().
PrepareStep()
bool simlib3::IntegrationMethod::PrepareStep (void) virtual
prepare object for integration step
Reimplemented in simlib3::ABM4, simlib3::FW, simlib3::MultiStepMethod, and simlib3::StatusMethod.
Definition at line 282 of file numint.cc.
References Dprintf, PrevINum, Resize(), and simlib3::IntegratorContainer::Size().
Referenced by Prepare(), simlib3::FW::PrepareStep(), simlib3::MultiStepMethod::PrepareStep(), and simlib3::StatusMethod::PrepareStep().
Resize()
void simlib3::IntegrationMethod::Resize (size_t size) virtual
resize all the memories to the given size
Definition at line 271 of file numint.cc.
References Dprintf, and MList.
Referenced by PrepareStep(), and TurnOff().
SearchMethod()
IntegrationMethod * simlib3::IntegrationMethod::SearchMethod (const char * name) static protected
search method in the list of registrated methods
Definition at line 239 of file numint.cc.
References Dprintf, MthLstPtr, NI_UnknownMeth, and simlib3::SIMLIB_error().
Referenced by simlib3::MultiStepMethod::GetStarter(), SetMethod(), simlib3::MultiStepMethod::SetStarter(), and simlib3::MultiStepMethod::SlavePtr().
SetErrNo()
static void simlib3::IntegrationMethod::SetErrNo (int num) static
SetMethod()
void simlib3::IntegrationMethod::SetMethod (const char * name) static
set method which will be used
Definition at line 75 of file numint.cc.
References CurrentMethodPtr, Dprintf, NI_CantSetMethod, SearchMethod(), simlib3::SIMLIB_DynamicFlag, simlib3::SIMLIB_error(), and TurnOff().
Referenced by simlib3::SetMethod().
SetOptStep()
void simlib3::IntegrationMethod::SetOptStep (double opt_step) static
Definition at line 307 of file numint.cc.
References simlib3::SIMLIB_OptStep.
SetStepSize()
void simlib3::IntegrationMethod::SetStepSize (double step_size) static
Definition at line 312 of file numint.cc.
References simlib3::SIMLIB_StepSize.
StateCond()
bool simlib3::IntegrationMethod::StateCond (void) static protected
check on changes of state conditions
Definition at line 175 of file numint.cc.
References Dprintf, IsEndStepEvent, simlib3::SIMLIB_ContractStep, simlib3::SIMLIB_ContractStepFlag, simlib3::SIMLIB_MinStep, simlib3::SIMLIB_StepSize, and simlib3::aCondition::TestAll().
Referenced by simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), and simlib3::RKF8::Integrate().
StepSim()
void simlib3::IntegrationMethod::StepSim (void) static
step of numerical integration method
Definition at line 52 of file numint.cc.
References CurrentMethodPtr, Dprintf, Integrate(), simlib3::IntegratorContainer::isAny(), Iterate(), Prepare(), simlib3::SIMLIB_DynamicFlag, Summarize(), and simlib3::Time.
Referenced by simlib3::Run().
Summarize()
void simlib3::IntegrationMethod::Summarize (void) static private
set up new state after execution of integration step
Definition at line 114 of file numint.cc.
References _SetTime, Dprintf, IsEndStepEvent, simlib3::NextTime, simlib3::IntegratorContainer::NtoL(), simlib3::StatusContainer::NtoL(), simlib3::SIMLIB_DeltaTime, simlib3::SIMLIB_StepStartTime, and simlib3::Time.
Referenced by StepSim().
TurnOff()
void simlib3::IntegrationMethod::TurnOff (void) virtual
turn off integration method: flush memories etc...
Reimplemented in simlib3::MultiStepMethod, and simlib3::StatusMethod.
Definition at line 261 of file numint.cc.
References Dprintf, PrevINum, and Resize().
Referenced by IntegrationDone(), SetMethod(), simlib3::MultiStepMethod::TurnOff(), and simlib3::StatusMethod::TurnOff().
Friends And Related Symbol Documentation
Memory
friend class Memory friend
Definition at line 1068 of file simlib.h.
Member Data Documentation
CurrentMethodPtr
IntegrationMethod * simlib3::IntegrationMethod::CurrentMethodPtr = &rke static private
pointer to the method currently used "rke" is a predefined method (historical reasons, we need rk45)
Definition at line 1062 of file simlib.h.
Referenced by GetMethod(), IntegrationDone(), Prepare(), SetMethod(), and StepSim().
IsEndStepEvent
bool simlib3::IntegrationMethod::IsEndStepEvent =false static protected
Definition at line 1079 of file simlib.h.
Referenced by simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), Iterate(), Prepare(), simlib3::StatusMethod::RestoreState(), StateCond(), and Summarize().
ItList
std::list<IntegrationMethod*>::iterator simlib3::IntegrationMethod::ItList private
Definition at line 1064 of file simlib.h.
Referenced by IntegrationMethod(), and ~IntegrationMethod().
method_name
const char* simlib3::IntegrationMethod::method_name private
Definition at line 1065 of file simlib.h.
Referenced by GetMethod(), IntegrationMethod(), and ~IntegrationMethod().
MList
std::list<Memory*> simlib3::IntegrationMethod::MList private
Definition at line 1071 of file simlib.h.
Referenced by IntegrationMethod(), and Resize().
MthLstPtr
std::list< IntegrationMethod * > * simlib3::IntegrationMethod::MthLstPtr =NULL static private
Definition at line 1063 of file simlib.h.
Referenced by IntegrationMethod(), SearchMethod(), and ~IntegrationMethod().
PrevINum
size_t simlib3::IntegrationMethod::PrevINum private
Definition at line 1070 of file simlib.h.
Referenced by PrepareStep(), and TurnOff().
PtrMList
std::list< IntegrationMethod::Memory * > * simlib3::IntegrationMethod::PtrMList static private
Definition at line 1072 of file simlib.h.
Referenced by IntegrationMethod().
The documentation for this class was generated from the following files:
src/simlib.h
src/numint.cc