SIMLIB/C++: simlib3::SIMLIB_Delay Class Reference
simlib3::SIMLIB_Delay Class Reference
continuous delay block
Static Public Member Functions
static void Register (Delay *p)
static void UnRegister (Delay *p)
Static Private Member Functions
static void Initialize ()
static void Destroy ()
static void SampleAll ()
function to scan inputs of all delay objects
static void InitAll ()
function to initialize all delay objects
Static Private Attributes
static std::list< Delay * > * listptr = 0
list of delay objects – singleton
Detailed Description
continuous delay block
Definition at line 44 of file delay.cc.
Member Function Documentation
Destroy()
static void simlib3::SIMLIB_Delay::Destroy () inline static private
< should be called by ExitSimulation()? ###???
Definition at line 62 of file delay.cc.
References INSTALL_HOOK, and listptr.
Referenced by UnRegister().
InitAll()
static void simlib3::SIMLIB_Delay::InitAll () inline static private
function to initialize all delay objects
Definition at line 77 of file delay.cc.
References listptr.
Referenced by Initialize().
Initialize()
static void simlib3::SIMLIB_Delay::Initialize () inline static private
< initialize delay subsystem
Definition at line 56 of file delay.cc.
References InitAll(), INSTALL_HOOK, listptr, and SampleAll().
Referenced by Register().
Register()
static void simlib3::SIMLIB_Delay::Register (Delay * p) inline static
< must be called by Delay ctr
Definition at line 47 of file delay.cc.
References Initialize(), and listptr.
Referenced by simlib3::Delay::Delay().
SampleAll()
static void simlib3::SIMLIB_Delay::SampleAll () inline static private
function to scan inputs of all delay objects
Definition at line 70 of file delay.cc.
References listptr.
Referenced by Initialize().
UnRegister()
static void simlib3::SIMLIB_Delay::UnRegister (Delay * p) inline static
< must be called from Delay destructor
Definition at line 51 of file delay.cc.
References Destroy(), and listptr.
Referenced by simlib3::Delay::~Delay().
Member Data Documentation
listptr
std::list< Delay * > * simlib3::SIMLIB_Delay::listptr = 0 static private
list of delay objects – singleton
Definition at line 45 of file delay.cc.
Referenced by Destroy(), InitAll(), Initialize(), Register(), SampleAll(), and UnRegister().
The documentation for this class was generated from the following file:
src/delay.cc