SIMLIB/C++: simlib3::Integrator2D Class Reference
simlib3::Integrator2D Class Reference
SIMLIB/C++ 2D extension
2D vector integrator
#include <simlib2D.h>
Classes
class special_input
Public Member Functions
Integrator2D (Input2D i, Value2D initial_value)
Integrator2D (Input2D i)
Integrator2D (Integrator2D &i, Value2D initial_value=Value2D(0, 0))
Integrator2D ()
Input2D SetInput (Input2D i)
Integrator2D & operator= (const Value2D &a)
Integrator2D & operator= (Input2D i)
virtual Value2D Value () override
Public Member Functions inherited from simlib3::aContiBlock2D
aContiBlock2D ()
~aContiBlock2D ()
virtual void _Eval ()
virtual Value2D Value ()=0
void Print ()
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Attributes
Integrator _x
Integrator _y
simlib3::Integrator2D::special_input in
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::aContiBlock2D
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
2D vector integrator
Definition at line 179 of file simlib2D.h.
Constructor & Destructor Documentation
Integrator2D() [1/4]
simlib3::Integrator2D::Integrator2D (Input2D i, Value2D initial_value)
Definition at line 165 of file simlib2D.cc.
Integrator2D() [2/4]
simlib3::Integrator2D::Integrator2D (Input2D i)
Definition at line 170 of file simlib2D.cc.
Integrator2D() [3/4]
simlib3::Integrator2D::Integrator2D (Integrator2D & i, Value2D initial_value = Value2D(0,0))
Definition at line 175 of file simlib2D.cc.
Integrator2D() [4/4]
simlib3::Integrator2D::Integrator2D ()
Definition at line 185 of file simlib2D.cc.
Member Function Documentation
operator=() [1/2]
Integrator2D & simlib3::Integrator2D::operator= (const Value2D & a)
Definition at line 193 of file simlib2D.cc.
References _x, _y, simlib3::Value2D::x(), and simlib3::Value2D::y().
operator=() [2/2]
Integrator2D & simlib3::Integrator2D::operator= (Input2D i)
Definition at line 200 of file simlib2D.cc.
References _x, _y, simlib3::Input2D::Value(), simlib3::Value2D::x(), and simlib3::Value2D::y().
SetInput()
Input2D simlib3::Integrator2D::SetInput (Input2D i) inline
Definition at line 199 of file simlib2D.h.
References simlib3::Integrator2D::special_input::in, in, and simlib3::Input2D::Set().
Value()
Value2D simlib3::Integrator2D::Value () override virtual
Implements simlib3::aContiBlock2D.
Definition at line 212 of file simlib2D.cc.
References _x, _y, and simlib3::Integrator::Value().
Member Data Documentation
_x
Integrator simlib3::Integrator2D::_x private
Definition at line 180 of file simlib2D.h.
Referenced by operator=(), operator=(), and Value().
_y
Integrator simlib3::Integrator2D::_y private
Definition at line 180 of file simlib2D.h.
Referenced by operator=(), operator=(), and Value().
in
simlib3::Integrator2D::special_input simlib3::Integrator2D::in private
Referenced by SetInput().
The documentation for this class was generated from the following files:
src/simlib2D.h
src/simlib2D.cc