SIMLIB/C++: simlib3::ZDelay Class Reference
simlib3::ZDelay Class Reference
#include <zdelay.h>
Public Member Functions
ZDelay (Input i, ZDelayTimer *clock=default_clock, double initvalue=0)
ZDelay (Input i, double initvalue)
~ZDelay ()
void Init (double iv)
virtual void Init ()
virtual double Value () override
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::aContiBlock1
aContiBlock1 (Input i)
constructor for blocks with single input
double InputValue ()
Public Member Functions inherited from simlib3::aContiBlock
aContiBlock ()
virtual void _Eval ()
evaluate block (with loop detection)
virtual double Value ()=0
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Protected Member Functions
virtual void SampleIn ()
virtual void SampleOut ()
Protected Attributes
double new_value
double old_value
double initval
Protected Attributes inherited from simlib3::aContiBlock
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Static Protected Attributes
static ZDelayTimer * default_clock = 0
Private Member Functions
ZDelay (const ZDelay &)
void operator= (const ZDelay &)
Private Attributes
double input_value
ZDelayTimer * clock
Friends
class ZDelayTimer
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Detailed Description
Definition at line 55 of file zdelay.h.
Constructor & Destructor Documentation
ZDelay() [1/3]
simlib3::ZDelay::ZDelay (const ZDelay &) private
ZDelay() [2/3]
simlib3::ZDelay::ZDelay (Input i, ZDelayTimer * clock = default_clock, double initvalue = 0) explicit
Definition at line 197 of file zdelay.cc.
References clock, Dprintf, Init(), simlib3::ZDelayTimer::Register(), and SIMLIB_internal_error.
ZDelay() [3/3]
simlib3::ZDelay::ZDelay (Input i, double initvalue)
Definition at line 212 of file zdelay.cc.
References clock, Dprintf, Init(), simlib3::ZDelayTimer::Register(), and SIMLIB_internal_error.
~ZDelay()
simlib3::ZDelay::~ZDelay ()
Definition at line 231 of file zdelay.cc.
References clock, Dprintf, and simlib3::ZDelayTimer::UnRegister().
Member Function Documentation
Init() [1/2]
void simlib3::ZDelay::Init () virtual
Definition at line 241 of file zdelay.cc.
References Dprintf, initval, input_value, new_value, and old_value.
Referenced by Init(), ZDelay(), and ZDelay().
Init() [2/2]
void simlib3::ZDelay::Init (double iv)
Definition at line 246 of file zdelay.cc.
References Init(), and initval.
operator=()
void simlib3::ZDelay::operator= (const ZDelay &) private
SampleIn()
void simlib3::ZDelay::SampleIn () protected virtual
Definition at line 254 of file zdelay.cc.
References Dprintf, input_value, and simlib3::aContiBlock1::InputValue().
SampleOut()
void simlib3::ZDelay::SampleOut () protected virtual
Definition at line 260 of file zdelay.cc.
References Dprintf, input_value, new_value, and old_value.
Value()
double simlib3::ZDelay::Value () override virtual
get block output value
this method should be defined in classes derived from aContiBlock
Implements simlib3::aContiBlock.
Definition at line 270 of file zdelay.cc.
References Dprintf, and old_value.
Friends And Related Symbol Documentation
ZDelayTimer
friend class ZDelayTimer friend
Definition at line 60 of file zdelay.h.
Member Data Documentation
clock
ZDelayTimer* simlib3::ZDelay::clock private
Definition at line 59 of file zdelay.h.
Referenced by simlib3::ZDelayTimer::Register(), simlib3::ZDelayTimer::UnRegister(), ZDelay(), ZDelay(), and ~ZDelay().
default_clock
ZDelayTimer * simlib3::ZDelay::default_clock = 0 static protected
Definition at line 69 of file zdelay.h.
Referenced by simlib3::ZDelayTimer::ZDelayTimer(), and simlib3::ZDelayTimer::~ZDelayTimer().
initval
double simlib3::ZDelay::initval protected
Definition at line 68 of file zdelay.h.
Referenced by Init(), and Init().
input_value
double simlib3::ZDelay::input_value private
Definition at line 58 of file zdelay.h.
Referenced by Init(), SampleIn(), and SampleOut().
new_value
double simlib3::ZDelay::new_value protected
Definition at line 65 of file zdelay.h.
Referenced by Init(), and SampleOut().
old_value
double simlib3::ZDelay::old_value protected
Definition at line 66 of file zdelay.h.
Referenced by Init(), SampleOut(), and Value().
The documentation for this class was generated from the following files:
src/zdelay.h
src/zdelay.cc