SIMLIB/C++: simlib3::aContiBlock3D1 Class Reference
simlib3::aContiBlock3D1 Class Reference
SIMLIB/C++ 3D extension
continuous 3D block with single input
#include <simlib3D.h>
Public Member Functions
aContiBlock3D1 (Input3D i)
Value3D InputValue ()
Input3D SetInput (Input3D i)
Public Member Functions inherited from simlib3::aContiBlock3D
aContiBlock3D ()
~aContiBlock3D ()
virtual void _Eval ()
virtual Value3D Value ()=0
void Print ()
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Attributes
Input3D input
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::aContiBlock3D
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
continuous 3D block with single input
Definition at line 125 of file simlib3D.h.
Constructor & Destructor Documentation
aContiBlock3D1()
simlib3::aContiBlock3D1::aContiBlock3D1 (Input3D i) explicit
Definition at line 134 of file simlib3D.cc.
References AlgLoopDetected, input, and simlib3::SIMLIB_error().
Member Function Documentation
InputValue()
Value3D simlib3::aContiBlock3D1::InputValue () inline
Definition at line 129 of file simlib3D.h.
References input, and simlib3::Input3D::Value().
Referenced by simlib3::_Mul3D1D::Value(), simlib3::_Div3D::Value(), simlib3::_UMinus3D::Value(), simlib3::_Norm3D::Value(), and simlib3::Expression3D::Value().
SetInput()
Input3D simlib3::aContiBlock3D1::SetInput (Input3D i) inline
Definition at line 130 of file simlib3D.h.
References input, and simlib3::Input3D::Set().
Member Data Documentation
input
Input3D simlib3::aContiBlock3D1::input private
Definition at line 126 of file simlib3D.h.
Referenced by aContiBlock3D1(), InputValue(), and SetInput().
The documentation for this class was generated from the following files:
src/simlib3D.h
src/simlib3D.cc