SIMLIB/C++: simlib3::WaitUntilList Class Reference
simlib3::WaitUntilList Class Reference
Public Types
typedef container_t::iterator iterator
Static Public Member Functions
static iterator begin ()
static iterator end ()
static bool empty ()
static void InsertCurrent ()
static void GetCurrent ()
static void WU_hook ()
static void Remove (Process *p)
static void clear ()
static void create ()
static void destroy ()
Private Types
typedef std::list< Process * > container_t
Private Member Functions
WaitUntilList ()
~WaitUntilList ()
Private Attributes
container_t l
Static Private Attributes
static WaitUntilList * instance = 0
static iterator current
Friends
void WU_print ()
Detailed Description
Definition at line 36 of file waitunti.cc.
Member Typedef Documentation
container_t
typedef std::list<Process *> simlib3::WaitUntilList::container_t private
Definition at line 37 of file waitunti.cc.
iterator
typedef container_t::iterator simlib3::WaitUntilList::iterator
Definition at line 41 of file waitunti.cc.
Constructor & Destructor Documentation
WaitUntilList()
simlib3::WaitUntilList::WaitUntilList () inline private
Definition at line 65 of file waitunti.cc.
References Dprintf.
Referenced by create().
~WaitUntilList()
simlib3::WaitUntilList::~WaitUntilList () inline private
Definition at line 66 of file waitunti.cc.
References Dprintf.
Member Function Documentation
begin()
static iterator simlib3::WaitUntilList::begin () inline static
Definition at line 42 of file waitunti.cc.
References instance, and l.
Referenced by clear(), InsertCurrent(), and WU_hook().
clear()
void simlib3::WaitUntilList::clear () static
Definition at line 190 of file waitunti.cc.
References simlib3::Process::_WaitUntilRemove(), begin(), end(), INSTALL_HOOK, instance, simlib3::SimObject::isAllocated(), l, and SIMLIB_internal_error.
Referenced by create(), and destroy().
create()
static void simlib3::WaitUntilList::create () inline static
Definition at line 53 of file waitunti.cc.
References clear(), destroy(), INSTALL_HOOK, instance, simlib3::SIMLIB_atexit(), SIMLIB_internal_error, and WaitUntilList().
Referenced by InsertCurrent().
destroy()
static void simlib3::WaitUntilList::destroy () inline static
Definition at line 59 of file waitunti.cc.
References clear(), and instance.
Referenced by create().
empty()
static bool simlib3::WaitUntilList::empty () inline static
Definition at line 44 of file waitunti.cc.
References instance, and l.
Referenced by GetCurrent(), InsertCurrent(), and WU_hook().
end()
static iterator simlib3::WaitUntilList::end () inline static
Definition at line 43 of file waitunti.cc.
References instance, and l.
Referenced by clear(), InsertCurrent(), and WU_hook().
GetCurrent()
void simlib3::WaitUntilList::GetCurrent () static
Definition at line 175 of file waitunti.cc.
References current, Dprintf, empty(), simlib3::flag, simlib3::Entity::id(), INSTALL_HOOK, instance, and l.
Referenced by simlib3::Process::_WaitUntil().
InsertCurrent()
void simlib3::WaitUntilList::InsertCurrent () static
Definition at line 153 of file waitunti.cc.
References begin(), create(), Dprintf, empty(), end(), simlib3::flag, simlib3::Entity::id(), INSTALL_HOOK, instance, l, simlib3::Entity::Priority, simlib3::SIMLIB_Current, and WU_hook().
Referenced by simlib3::Process::_WaitUntil().
Remove()
static void simlib3::WaitUntilList::Remove (Process * p) inline static
Definition at line 48 of file waitunti.cc.
References Dprintf, simlib3::Entity::id(), instance, and l.
Referenced by simlib3::Process::_WaitUntilRemove().
WU_hook()
void simlib3::WaitUntilList::WU_hook () static
Definition at line 92 of file waitunti.cc.
References begin(), current, Dprintf, empty(), end(), simlib3::flag, simlib3::SIMLIB_Current, and SIMLIB_internal_error.
Referenced by InsertCurrent().
Friends And Related Symbol Documentation
WU_print
void WU_print () friend
Definition at line 75 of file waitunti.cc.
Member Data Documentation
current
WaitUntilList::iterator simlib3::WaitUntilList::current static private
Definition at line 68 of file waitunti.cc.
Referenced by GetCurrent(), and WU_hook().
instance
WaitUntilList * simlib3::WaitUntilList::instance = 0 static private
Definition at line 39 of file waitunti.cc.
Referenced by begin(), clear(), create(), destroy(), empty(), end(), GetCurrent(), InsertCurrent(), and Remove().
l
container_t simlib3::WaitUntilList::l private
Definition at line 38 of file waitunti.cc.
Referenced by begin(), clear(), empty(), end(), GetCurrent(), InsertCurrent(), and Remove().
The documentation for this class was generated from the following file:
src/waitunti.cc