SIMLIB/C++: simlib3::Process Class Reference
simlib3::Process Class Reference abstract
SIMLIB/C++
Abstract base class for all simulation processesProcess behavior is specified by Behavior method and can be interrupted during execution by e.g.
#include <simlib.h>
Public Member Functions
Process (Priority_t p=DEFAULT_PRIORITY)
Process constructor sets state to PREPARED.
virtual ~Process ()
Process destructor Sets status to TERMINATED and removes process from queue/calendar/waituntil list.
virtual void Behavior ()=0
behavior description
virtual void Output () const override
print object to default output
virtual std::string Name () const override
name of object
virtual void Activate (double t) override
activate at time t (schedule)
virtual void Passivate () override
process deactivation (sleep)
virtual void Wait (double dtime)
wait for dtime interval
bool _WaitUntil (bool test)
wait for condition (slow!)
void Interrupt ()
test of WaitUntil list, allow running others
virtual void Terminate () override
kill process
void Seize (Facility &f, ServicePriority_t sp=0)
seize facility
void Release (Facility &f)
release facility
void Enter (Store &s, unsigned long ReqCap=1)
acquire some capacity
void Leave (Store &s, unsigned long ReqCap=1)
return some capacity
virtual void Into (Queue &q)
insert process into queue
void Activate ()
activate now
virtual void Activate (double t)
activate at time t (schedule)
Public Member Functions inherited from simlib3::Entity
unsigned long id () const
Entity (Priority_t p=DEFAULT_PRIORITY)
constructor
virtual ~Entity ()
destructor
operator Entity * ()
double ActivationTime ()
get activation time of entity - iff scheduled
it is here, because Entity has no knowledge of calendar activation record structure
void Activate ()
activate now
virtual void Activate (double t)
activate at time t (schedule)
virtual void Passivate ()
deactivation
virtual void Terminate ()=0
end Behavior() and remove entity
bool Idle ()
entity activation is not scheduled in calendar
void Cancel ()
end Behavior() and remove entity
virtual void Out () override
remove entity from queue
EventNotice * GetEventNotice ()
Public Member Functions inherited from simlib3::Link
Link ()
virtual ~Link ()
virtual void Into (List *l)
insert last
virtual void Out ()
remove from list
List * Where ()
where is linked
virtual bool isInQueue ()
present in queue
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Types
enum ProcessStatus_t { _PREPARED =1 , _RUNNING , _INTERRUPTED , _TERMINATED }
possible process status values
Private Member Functions
virtual void _Run () noexcept override
Process dispatch method.
bool isPrepared () const
bool isCurrent () const
bool isInterrupted () const
bool isTerminated () const
void _WaitUntilRemove ()
Private Attributes
void * _context
process context pointer
enum simlib3::Process::ProcessStatus_t _status
bool _wait_until
Friends
class WaitUntilList
Additional Inherited Members
Public Types inherited from simlib3::Entity
typedef EntityPriority_t Priority_t
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Public Attributes inherited from simlib3::Entity
Priority_t Priority
priority of the entity (scheduling,queues)
Protected Member Functions inherited from simlib3::Link
Link (Link *p, Link *s, List *h)
Protected Attributes inherited from simlib3::Entity
unsigned long _Ident
unique identification number of entity
double _MarkTime
union {
double _RemainingTime
unsigned long _RequiredCapacity
};
ServicePriority_t _SPrio
priority of service in Facility
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Static Protected Attributes inherited from simlib3::Entity
static unsigned long _Number = 0L
current number of entities
Detailed Description
Abstract base class for all simulation processes
Process behavior is specified by Behavior method and can be interrupted during execution by e.g.
Wait method call (it is coroutine)
Definition at line 440 of file simlib.h.
Member Enumeration Documentation
ProcessStatus_t
enum simlib3::Process::ProcessStatus_t private
possible process status values
Enumerator
_PREPARED
_RUNNING
_INTERRUPTED
_TERMINATED
Definition at line 445 of file simlib.h.
Constructor & Destructor Documentation
Process()
simlib3::Process::Process (Priority_t p = DEFAULT_PRIORITY)
Process constructor sets state to PREPARED.
Examples
_test_.cc.
Definition at line 250 of file process.cc.
References _context, _PREPARED, _status, _wait_until, and Dprintf.
~Process()
simlib3::Process::~Process () virtual
Process destructor Sets status to TERMINATED and removes process from queue/calendar/waituntil list.
TODO: Warn if this==Current? (e.g. "delete this;" in Behavior())
Definition at line 262 of file process.cc.
References _context, _status, _TERMINATED, _wait_until, _WaitUntilRemove(), Dprintf, simlib3::SQS::Get(), simlib3::Entity::Idle(), simlib3::Entity::Out(), and simlib3::Link::Where().
Member Function Documentation
_Run()
void simlib3::Process::_Run () override private virtual noexcept
Process dispatch method.
The dispatcher starts/reactivates process behavior
IMPORTANT notes:
Function contains some non-portable code and should be called from single place in simulation-control algorithm, because it is sensitive to stack-frame position (it saves/restores the stack contents).
This function: 1) marks current position on stack 2) marks current CPU context 3) calls Behavior() 4) after interruption of Behavior() returns 5) if called next time, do 1), 2) and move stack pointer (SP) 6) copy saved stack content back 7) do longjmp() to restore Behavior() execution
Implements simlib3::Entity.
Definition at line 455 of file process.cc.
References _context, simlib3::Entity::_Ident, _INTERRUPTED, _PREPARED, _RUNNING, _status, _TERMINATED, Behavior(), CANARY1, DBG_THREAD, DEBUG, Dprintf, simlib3::SQS::Get(), simlib3::Entity::Idle(), simlib3::SimObject::isAllocated(), isTerminated(), simlib3::Entity::Out(), simlib3::P_Context, simlib3::P_DispatcherStatusBuffer, simlib3::P_StackBase, simlib3::P_StackBase2, simlib3::P_StackSize, ProcessNotInitialized, simlib3::SIMLIB_error(), simlib3::P_Context_t::size, simlib3::P_Context_t::stack, STACK_RESERVED, simlib3::P_Context_t::status, THREAD_DEBUG, and simlib3::Link::Where().
_WaitUntil()
bool simlib3::Process::_WaitUntil (bool test)
wait for condition (slow!)
Definition at line 123 of file waitunti.cc.
References _wait_until, Dprintf, simlib3::WaitUntilList::GetCurrent(), simlib3::WaitUntilList::InsertCurrent(), Passivate(), simlib3::SIMLIB_Current, and SIMLIB_internal_error.
_WaitUntilRemove()
void simlib3::Process::_WaitUntilRemove () private
Definition at line 142 of file waitunti.cc.
References _wait_until, and simlib3::WaitUntilList::Remove().
Referenced by simlib3::WaitUntilList::clear(), and ~Process().
Activate() [1/3]
void simlib3::Entity::Activate () inline
activate now
Definition at line 408 of file simlib.h.
Activate() [2/3]
void simlib3::Entity::Activate (double t) virtual
activate at time t (schedule)
entity activation at given time
Reimplemented from simlib3::Entity.
Definition at line 409 of file entity.cc.
Activate() [3/3]
void simlib3::Process::Activate (double t) override virtual
activate at time t (schedule)
Activate process at time t.
Reimplemented from simlib3::Entity.
Examples
_test_.cc.
Definition at line 323 of file process.cc.
References simlib3::Entity::_Ident, simlib3::Entity::Activate(), Dprintf, isCurrent(), t, and THREAD_INTERRUPT.
Referenced by main().
Behavior()
virtual void simlib3::Process::Behavior () pure virtual
behavior description
Implemented in TestProcess.
Referenced by _Run().
Enter()
void simlib3::Process::Enter (Store & s, unsigned long ReqCap = 1)
acquire some capacity
Enter - use cap capacity of store s possibly waiting in input queue, if not enough free capacity.
Definition at line 363 of file process.cc.
References simlib3::Store::Enter().
Interrupt()
void simlib3::Process::Interrupt ()
test of WaitUntil list, allow running others
Interrupt process behavior - this ensures WaitUntil tests WARNING: use with care - it can run higher (or equal) priority processes before continuing.
Definition at line 308 of file process.cc.
References simlib3::Entity::_Ident, simlib3::Entity::Activate(), Dprintf, isCurrent(), and THREAD_INTERRUPT.
Into()
void simlib3::Process::Into (Queue & q) virtual
insert process into queue
insert current process into queue The process can be at most in single queue.
Definition at line 380 of file process.cc.
References simlib3::Queue::Insert(), simlib3::Entity::Out(), simlib3::SIMLIB_warning(), and simlib3::Link::Where().
isCurrent()
bool simlib3::Process::isCurrent () const inline private
Definition at line 449 of file simlib.h.
References _RUNNING, and _status.
Referenced by Activate(), Interrupt(), Output(), Passivate(), Terminate(), and Wait().
isInterrupted()
bool simlib3::Process::isInterrupted () const inline private
Definition at line 450 of file simlib.h.
References _INTERRUPTED, and _status.
isPrepared()
bool simlib3::Process::isPrepared () const inline private
Definition at line 448 of file simlib.h.
References _PREPARED, and _status.
isTerminated()
bool simlib3::Process::isTerminated () const inline private
Definition at line 451 of file simlib.h.
References _status, and _TERMINATED.
Referenced by _Run().
Leave()
void simlib3::Process::Leave (Store & s, unsigned long ReqCap = 1)
return some capacity
Leave - return cap capacity of store s and enter first waiting entity from queue, which can use free capacity.
Definition at line 372 of file process.cc.
References simlib3::Store::Leave().
Name()
std::string simlib3::Process::Name () const override virtual
name of object
Name of the process warning: uses static buffer for generic names TODO: use std::string.
Reimplemented from simlib3::SimObject.
Definition at line 294 of file process.cc.
References simlib3::Entity::_Ident, simlib3::SimObject::Name(), and simlib3::SIMLIB_create_tmp_name().
Referenced by Output().
Output()
void simlib3::Process::Output () const override virtual
print object to default output
Reimplemented from simlib3::SimObject.
Definition at line 108 of file output2.cc.
References isCurrent(), Name(), and simlib3::Print().
Passivate()
void simlib3::Process::Passivate () override virtual
process deactivation (sleep)
Process deactivation To continue the behavior it should be activated again Warning: memory leak if not activated/deleted.
Reimplemented from simlib3::Entity.
Definition at line 393 of file process.cc.
References Dprintf, isCurrent(), simlib3::Entity::Passivate(), and THREAD_INTERRUPT.
Referenced by _WaitUntil().
Release()
void simlib3::Process::Release (Facility & f)
release facility
Release facility f possibly activate first waiting entity in queue.
Definition at line 355 of file process.cc.
References simlib3::Facility::Release().
Seize()
void simlib3::Process::Seize (Facility & f, ServicePriority_t sp = 0)
seize facility
Seize facility f with optional priority of service sp possibly waiting in input queue, if it is busy.
Definition at line 347 of file process.cc.
References simlib3::Facility::Seize().
Terminate()
void simlib3::Process::Terminate () override virtual
kill process
Terminate the process if called by current process, self-destruct free memory of the process.
Implements simlib3::Entity.
Definition at line 406 of file process.cc.
References simlib3::Entity::_Ident, _status, _TERMINATED, Dprintf, simlib3::SQS::Get(), simlib3::Entity::Idle(), simlib3::SimObject::isAllocated(), isCurrent(), simlib3::Entity::Out(), THREAD_EXIT, and simlib3::Link::Where().
Wait()
void simlib3::Process::Wait (double dtime) virtual
wait for dtime interval
Wait for dtime.
Examples
_test_.cc.
Definition at line 335 of file process.cc.
References simlib3::Entity::_Ident, simlib3::Entity::Activate(), Dprintf, isCurrent(), THREAD_INTERRUPT, and simlib3::Time.
Referenced by TestProcess::Behavior().
Friends And Related Symbol Documentation
WaitUntilList
friend class WaitUntilList friend
Definition at line 453 of file simlib.h.
Member Data Documentation
_context
void* simlib3::Process::_context private
process context pointer
Definition at line 441 of file simlib.h.
Referenced by _Run(), Process(), and ~Process().
_status
enum simlib3::Process::ProcessStatus_t simlib3::Process::_status private
Referenced by _Run(), isCurrent(), isInterrupted(), isPrepared(), isTerminated(), Process(), Terminate(), and ~Process().
_wait_until
bool simlib3::Process::_wait_until private
Definition at line 454 of file simlib.h.
Referenced by _WaitUntil(), _WaitUntilRemove(), Process(), and ~Process().
The documentation for this class was generated from the following files:
src/simlib.h
src/output2.cc
src/process.cc
src/waitunti.cc