SIMLIB/C++: simlib3::Integrator3D Class Reference
simlib3::Integrator3D Class Reference
SIMLIB/C++ 3D extension
3D vector integrator
#include <simlib3D.h>
Classes
class special_input
Public Member Functions
Integrator3D (Input3D i, const Value3D &initial_value)
Integrator3D (Input3D i)
Integrator3D (Integrator3D &i, const Value3D &initial_value=Value3D(0, 0, 0))
Integrator3D ()
Input3D SetInput (Input3D i)
void Init (const Value3D &v)
Integrator3D & operator= (const Value3D &a)
Integrator3D & operator= (Input3D i)
virtual Value3D Value () override
Public Member Functions inherited from simlib3::aContiBlock3D
aContiBlock3D ()
~aContiBlock3D ()
virtual void _Eval ()
virtual Value3D Value ()=0
void Print ()
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Attributes
Integrator _x
Integrator _y
Integrator _z
simlib3::Integrator3D::special_input in
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::aContiBlock3D
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
3D vector integrator
Definition at line 180 of file simlib3D.h.
Constructor & Destructor Documentation
Integrator3D() [1/4]
simlib3::Integrator3D::Integrator3D (Input3D i, const Value3D & initial_value)
Definition at line 164 of file simlib3D.cc.
Integrator3D() [2/4]
simlib3::Integrator3D::Integrator3D (Input3D i)
Definition at line 170 of file simlib3D.cc.
Integrator3D() [3/4]
simlib3::Integrator3D::Integrator3D (Integrator3D & i, const Value3D & initial_value = Value3D(0,0,0))
Definition at line 175 of file simlib3D.cc.
Integrator3D() [4/4]
simlib3::Integrator3D::Integrator3D ()
Definition at line 186 of file simlib3D.cc.
Member Function Documentation
Init()
void simlib3::Integrator3D::Init (const Value3D & v) inline
Definition at line 203 of file simlib3D.h.
References _x, _y, _z, simlib3::Integrator::Init(), simlib3::Value3D::x(), simlib3::Value3D::y(), and simlib3::Value3D::z().
operator=() [1/2]
Integrator3D & simlib3::Integrator3D::operator= (const Value3D & a)
Definition at line 201 of file simlib3D.cc.
References _x, _y, _z, simlib3::Value3D::x(), simlib3::Value3D::y(), and simlib3::Value3D::z().
operator=() [2/2]
Integrator3D & simlib3::Integrator3D::operator= (Input3D i)
Definition at line 209 of file simlib3D.cc.
References _x, _y, _z, simlib3::Input3D::Value(), simlib3::Value3D::x(), simlib3::Value3D::y(), and simlib3::Value3D::z().
SetInput()
Input3D simlib3::Integrator3D::SetInput (Input3D i) inline
Definition at line 200 of file simlib3D.h.
References simlib3::Integrator3D::special_input::in, in, and simlib3::Input3D::Set().
Value()
Value3D simlib3::Integrator3D::Value () override virtual
Implements simlib3::aContiBlock3D.
Definition at line 193 of file simlib3D.cc.
References _x, _y, _z, and simlib3::Integrator::Value().
Member Data Documentation
_x
Integrator simlib3::Integrator3D::_x private
Definition at line 181 of file simlib3D.h.
Referenced by Init(), operator=(), operator=(), and Value().
_y
Integrator simlib3::Integrator3D::_y private
Definition at line 181 of file simlib3D.h.
Referenced by Init(), operator=(), operator=(), and Value().
_z
Integrator simlib3::Integrator3D::_z private
Definition at line 181 of file simlib3D.h.
Referenced by Init(), operator=(), operator=(), and Value().
in
simlib3::Integrator3D::special_input simlib3::Integrator3D::in private
Referenced by SetInput().
The documentation for this class was generated from the following files:
src/simlib3D.h
src/simlib3D.cc