SIMLIB/C++: simlib3::ZDelayTimer::ZDelayContainer Class Reference
simlib3::ZDelayTimer::ZDelayContainer Class Reference
Public Types
typedef container_t::iterator iterator
Public Member Functions
ZDelayContainer ()
iterator begin ()
iterator end ()
void insert (ZDelay *p)
void erase (ZDelay *p)
void clear ()
Private Types
typedef std::set< ZDelay * > container_t
Private Attributes
container_t c
Detailed Description
Definition at line 90 of file zdelay.cc.
Member Typedef Documentation
container_t
typedef std::set<ZDelay*> simlib3::ZDelayTimer::ZDelayContainer::container_t private
Definition at line 91 of file zdelay.cc.
iterator
typedef container_t::iterator simlib3::ZDelayTimer::ZDelayContainer::iterator
Definition at line 95 of file zdelay.cc.
Constructor & Destructor Documentation
ZDelayContainer()
simlib3::ZDelayTimer::ZDelayContainer::ZDelayContainer () inline
Definition at line 94 of file zdelay.cc.
Member Function Documentation
begin()
iterator simlib3::ZDelayTimer::ZDelayContainer::begin () inline
Definition at line 96 of file zdelay.cc.
References c.
Referenced by simlib3::ZDelayTimer::Behavior(), simlib3::ZDelayTimer::Init(), and simlib3::ZDelayTimer::~ZDelayTimer().
clear()
void simlib3::ZDelayTimer::ZDelayContainer::clear () inline
Definition at line 100 of file zdelay.cc.
References c.
Referenced by simlib3::ZDelayTimer::~ZDelayTimer().
end()
iterator simlib3::ZDelayTimer::ZDelayContainer::end () inline
Definition at line 97 of file zdelay.cc.
References c.
Referenced by simlib3::ZDelayTimer::Behavior(), simlib3::ZDelayTimer::Init(), and simlib3::ZDelayTimer::~ZDelayTimer().
erase()
void simlib3::ZDelayTimer::ZDelayContainer::erase (ZDelay * p) inline
Definition at line 99 of file zdelay.cc.
References c.
Referenced by simlib3::ZDelayTimer::UnRegister().
insert()
void simlib3::ZDelayTimer::ZDelayContainer::insert (ZDelay * p) inline
Definition at line 98 of file zdelay.cc.
References c.
Referenced by simlib3::ZDelayTimer::Register().
Member Data Documentation
c
container_t simlib3::ZDelayTimer::ZDelayContainer::c private
Definition at line 92 of file zdelay.cc.
Referenced by begin(), clear(), end(), erase(), and insert().
The documentation for this class was generated from the following file:
src/zdelay.cc