SIMLIB/C++: simlib3::EULER Class Reference
simlib3::EULER Class Reference
#include <ni_euler.h>
Public Member Functions
EULER (const char *name)
virtual ~EULER ()
virtual void Integrate (void) override
Public Member Functions inherited from simlib3::StatusMethod
StatusMethod (const char *name)
initialization
virtual ~StatusMethod ()
virtual void TurnOff (void) override
turn off integration method: flush memories etc...
virtual bool PrepareStep (void) override
prepare object for integration step
virtual void StatusResize (size_t size)
resize status memories to the given size
Public Member Functions inherited from simlib3::SingleStepMethod
SingleStepMethod (const char *name)
virtual bool IsSingleStep (void) override
void SetStartMode (bool start_mode)
bool IsStartMode (void)
Public Member Functions inherited from simlib3::IntegrationMethod
IntegrationMethod (const char *name)
register method to list of methods and name it
virtual ~IntegrationMethod ()
destroy integration method (remove from list)
virtual bool IsSingleStep (void)=0
virtual void TurnOff (void)
turn off integration method: flush memories etc...
virtual void Integrate (void)=0
virtual bool PrepareStep (void)
prepare object for integration step
virtual void Resize (size_t size)
resize all the memories to the given size
Private Attributes
Memory si
Memory di
Memory A
StatusMemory xi
Additional Inherited Members
Static Public Member Functions inherited from simlib3::IntegrationMethod
static void StepSim (void)
step of numerical integration method
static void IntegrationDone (void)
static void SetMethod (const char *name)
set method which will be used
static const char * GetMethod (void)
static void InitStep (double step_frag)
initialize step
static void FunCall (double step_frag)
static void SetOptStep (double opt_step)
static void SetStepSize (double step_size)
static bool IsConditionFlag (void)
static int GetErrNo (void)
static void SetErrNo (int num)
Protected Types inherited from simlib3::StatusMethod
typedef StatusContainer::iterator StatusIterator
Protected Types inherited from simlib3::IntegrationMethod
typedef IntegratorContainer::iterator Iterator
Static Protected Member Functions inherited from simlib3::StatusMethod
static StatusIterator FirstStatus (void)
static StatusIterator LastStatus (void)
static void StoreState (Memory &di, Memory &si, StatusMemory &xi)
store state of integrators and status variables
static void RestoreState (double dthlf, Memory &di, Memory &si, StatusMemory &xi)
restore state of integrators and status variables
static void GoToState (Memory &di, Memory &si, StatusMemory &xi)
move startpoint to given state
Static Protected Member Functions inherited from simlib3::IntegrationMethod
static Iterator FirstIntegrator (void)
static Iterator LastIntegrator (void)
static bool StateCond (void)
check on changes of state conditions
static IntegrationMethod * SearchMethod (const char *name)
search method in the list of registrated methods
Static Protected Attributes inherited from simlib3::IntegrationMethod
static bool IsEndStepEvent =false
Detailed Description
Definition at line 22 of file ni_euler.h.
Constructor & Destructor Documentation
EULER()
simlib3::EULER::EULER (const char * name) inline
Definition at line 27 of file ni_euler.h.
~EULER()
virtual simlib3::EULER::~EULER () inline virtual
Definition at line 30 of file ni_euler.h.
Member Function Documentation
Integrate()
void simlib3::EULER::Integrate (void) override virtual
Implements simlib3::IntegrationMethod.
Definition at line 46 of file ni_euler.cc.
References simlib3::_Print(), _SetTime, A, AccuracyError, di, Dprintf, simlib3::IntegrationMethod::FirstIntegrator(), simlib3::StatusMethod::GoToState(), simlib3::IntegrationMethod::IsEndStepEvent, simlib3::SingleStepMethod::IsStartMode(), simlib3::IntegrationMethod::LastIntegrator(), simlib3::max(), simlib3::min(), simlib3::OptStep, simlib3::StatusMethod::RestoreState(), si, simlib3::SIMLIB_AbsoluteError, simlib3::SIMLIB_ConditionFlag, simlib3::SIMLIB_ContractStep, simlib3::SIMLIB_ContractStepFlag, simlib3::SIMLIB_DeltaTime, simlib3::SIMLIB_Dynamic(), simlib3::SIMLIB_ERRNO, simlib3::SIMLIB_MaxStep, simlib3::SIMLIB_MinStep, simlib3::SIMLIB_OptStep, simlib3::SIMLIB_RelativeError, simlib3::SIMLIB_StepSize, simlib3::SIMLIB_StepStartTime, simlib3::SIMLIB_warning(), simlib3::IntegrationMethod::StateCond(), simlib3::StatusMethod::StoreState(), simlib3::Time, and xi.
Member Data Documentation
A
Memory simlib3::EULER::A private
Definition at line 24 of file ni_euler.h.
Referenced by Integrate().
di
Memory simlib3::EULER::di private
Definition at line 24 of file ni_euler.h.
Referenced by Integrate().
si
Memory simlib3::EULER::si private
Definition at line 24 of file ni_euler.h.
Referenced by Integrate().
xi
StatusMemory simlib3::EULER::xi private
Definition at line 25 of file ni_euler.h.
Referenced by Integrate().
The documentation for this class was generated from the following files:
src/ni_euler.h
src/ni_euler.cc