SIMLIB/C++: simlib3::AlgLoopDetector Class Reference
simlib3::AlgLoopDetector Class Reference
class for algebraic loop detection AlgLoopDetector object should be used in Value() method only it checks for recursion in continuous block expression evaluation
User should remove algebraic loop manualy using special block (see AlgLoop solvers)
#include <internal.h>
Public Member Functions
AlgLoopDetector (aContiBlock *x)
~AlgLoopDetector ()
Private Member Functions
void lock ()
begin checking for recursion in Value() calling
void unlock ()
end checking for recursion
Private Attributes
aContiBlock * block
Detailed Description
class for algebraic loop detection AlgLoopDetector object should be used in Value() method only it checks for recursion in continuous block expression evaluation
User should remove algebraic loop manualy using special block (see AlgLoop solvers)
Definition at line 307 of file internal.h.
Constructor & Destructor Documentation
AlgLoopDetector()
simlib3::AlgLoopDetector::AlgLoopDetector (aContiBlock * x) inline
Definition at line 319 of file internal.h.
References lock().
~AlgLoopDetector()
simlib3::AlgLoopDetector::~AlgLoopDetector () inline
Definition at line 320 of file internal.h.
References unlock().
Member Function Documentation
lock()
void simlib3::AlgLoopDetector::lock () inline private
begin checking for recursion in Value() calling
Definition at line 310 of file internal.h.
References simlib3::SimObject::_EVAL_FLAG, AlgLoopDetected, block, simlib3::SIMLIB_error(), and simlib3::SimObject::TestAndSetFlag().
Referenced by AlgLoopDetector().
unlock()
void simlib3::AlgLoopDetector::unlock () inline private
end checking for recursion
Definition at line 315 of file internal.h.
References simlib3::SimObject::_EVAL_FLAG, block, and simlib3::SimObject::TestAndSetFlag().
Referenced by ~AlgLoopDetector().
Member Data Documentation
block
aContiBlock* simlib3::AlgLoopDetector::block private
Definition at line 308 of file internal.h.
Referenced by lock(), and unlock().
The documentation for this class was generated from the following file:
src/internal.h