SIMLIB/C++: simlib3::_XYZpart Class Reference
simlib3::_XYZpart Class Reference
Public Types
enum WhichPart { x , y , z }
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Public Member Functions
_XYZpart (Input3D a, WhichPart w)
virtual double Value () override
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::aContiBlock
aContiBlock ()
virtual void _Eval ()
evaluate block (with loop detection)
virtual double Value ()=0
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Member Functions
virtual void _Eval () override
evaluate block (with loop detection)
Private Attributes
Input3D input
WhichPart which
Additional Inherited Members
Protected Attributes inherited from simlib3::aContiBlock
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
Definition at line 414 of file simlib3D.cc.
Member Enumeration Documentation
WhichPart
enum simlib3::_XYZpart::WhichPart
Enumerator
x
y
z
Definition at line 418 of file simlib3D.cc.
Constructor & Destructor Documentation
_XYZpart()
simlib3::_XYZpart::_XYZpart (Input3D a, WhichPart w) inline
Definition at line 419 of file simlib3D.cc.
Member Function Documentation
_Eval()
virtual void simlib3::_XYZpart::_Eval () inline override private virtual
evaluate block (with loop detection)
evaluation with algebraic loop detection
Reimplemented from simlib3::aContiBlock.
Definition at line 415 of file simlib3D.cc.
Value()
virtual double simlib3::_XYZpart::Value () inline override virtual
get block output value
this method should be defined in classes derived from aContiBlock
Implements simlib3::aContiBlock.
Definition at line 420 of file simlib3D.cc.
References input, SIMLIB_internal_error, simlib3::Input3D::Value(), which, x, simlib3::Value3D::x(), y, simlib3::Value3D::y(), z, and simlib3::Value3D::z().
Member Data Documentation
input
Input3D simlib3::_XYZpart::input private
Definition at line 416 of file simlib3D.cc.
Referenced by Value().
which
WhichPart simlib3::_XYZpart::which private
Definition at line 431 of file simlib3D.cc.
Referenced by Value().
The documentation for this class was generated from the following file:
src/simlib3D.cc