SIMLIB/C++: simlib3::RegulaFalsi Class Reference
simlib3::RegulaFalsi Class Reference
SIMLIB/C++
solve using regula falsi method
#include <simlib.h>
Public Member Functions
RegulaFalsi (Input i, double eps, unsigned long max_it, double t_min, double t_max)
virtual double Value () override
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::AlgLoop
AlgLoop (Input i, double eps, unsigned long max_it, double t_min, double t_max, double t0)
void Set (double eps, unsigned long max_it, double t_min, double t_max, double t0)
void Set (double eps, unsigned long max_it, double t_min, double t_max)
Public Member Functions inherited from simlib3::aContiBlock1
aContiBlock1 (Input i)
constructor for blocks with single input
double InputValue ()
Public Member Functions inherited from simlib3::aContiBlock
aContiBlock ()
virtual void _Eval ()
evaluate block (with loop detection)
virtual double Value ()=0
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Attributes
double eps_root
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::AlgLoop
double Eps
unsigned long MaxIt
double TA
double TB
double T0
bool was_cycle
int phase
double root
Protected Attributes inherited from simlib3::aContiBlock
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
solve using regula falsi method
Definition at line 1699 of file simlib.h.
Constructor & Destructor Documentation
RegulaFalsi()
simlib3::RegulaFalsi::RegulaFalsi (Input i, double eps, unsigned long max_it, double t_min, double t_max) inline
Definition at line 1702 of file simlib.h.
Member Function Documentation
Value()
double simlib3::RegulaFalsi::Value () override virtual
get block output value
this method should be defined in classes derived from aContiBlock
Implements simlib3::aContiBlock.
Definition at line 285 of file algloop.cc.
References AL_MaxCount, AL_NotInLoop, dbgprnt, simlib3::AlgLoop::Eps, eps_root, simlib3::aContiBlock1::InputValue(), simlib3::AlgLoop::MaxIt, simlib3::AlgLoop::phase, simlib3::AlgLoop::root, simlib3::SIMLIB_error(), simlib3::SIMLIB_warning(), simlib3::AlgLoop::TA, simlib3::AlgLoop::TB, and simlib3::AlgLoop::was_cycle.
Member Data Documentation
eps_root
double simlib3::RegulaFalsi::eps_root private
Definition at line 1700 of file simlib.h.
Referenced by Value().
The documentation for this class was generated from the following files:
src/simlib.h
src/algloop.cc