SIMLIB/C++: simlib3::Input2D Class Reference
simlib3::Input2D Class Reference
SIMLIB/C++ 2D extension
Continuous block connection (transparent reference)
#include <simlib2D.h>
Public Member Functions
Input2D & operator= (const Input2D &x)
Input2D (const Input2D &in)
Input2D (aContiBlock2D &cb)
Input2D (aContiBlock2D *cb)
Input2D Set (Input2D i)
Value2D Value ()
bool operator== (void *p)
Private Attributes
aContiBlock2D * bp
Detailed Description
Continuous block connection (transparent reference)
Definition at line 109 of file simlib2D.h.
Constructor & Destructor Documentation
Input2D() [1/3]
simlib3::Input2D::Input2D (const Input2D & in) inline
Definition at line 113 of file simlib2D.h.
Input2D() [2/3]
simlib3::Input2D::Input2D (aContiBlock2D & cb) inline
Definition at line 114 of file simlib2D.h.
Input2D() [3/3]
simlib3::Input2D::Input2D (aContiBlock2D * cb) inline
Definition at line 115 of file simlib2D.h.
Member Function Documentation
operator=()
Input2D & simlib3::Input2D::operator= (const Input2D & x) inline
Definition at line 112 of file simlib2D.h.
References bp.
operator==()
bool simlib3::Input2D::operator== (void * p) inline
Definition at line 118 of file simlib2D.h.
References bp.
Set()
Input2D simlib3::Input2D::Set (Input2D i) inline
Definition at line 116 of file simlib2D.h.
References bp.
Referenced by simlib3::aContiBlock2D1::SetInput(), and simlib3::Integrator2D::SetInput().
Value()
Value2D simlib3::Input2D::Value () inline
Definition at line 117 of file simlib2D.h.
References bp, and simlib3::aContiBlock2D::Value().
Referenced by simlib3::aContiBlock2D2::Input1Value(), simlib3::aContiBlock2D2::Input2Value(), simlib3::aContiBlock2D3::Input3Value(), simlib3::aContiBlock2D1::InputValue(), simlib3::Integrator2D::operator=(), simlib3::_Abs2D::Value(), simlib3::_ScalarProduct2D::Value(), simlib3::_XYpart::Value(), and simlib3::Integrator2D::special_input::Value().
Member Data Documentation
bp
aContiBlock2D* simlib3::Input2D::bp private
Definition at line 110 of file simlib2D.h.
Referenced by operator=(), operator==(), Set(), and Value().
The documentation for this class was generated from the following file:
src/simlib2D.h