SIMLIB/C++: simlib3::StatusContainer Class Reference
simlib3::StatusContainer Class Reference
StatusContainer - internal container of status variables (singleton)
#include <simlib.h>
Public Types
typedef std::list< Status * >::iterator iterator
Static Public Member Functions
static bool isAny (void)
static size_t Size (void)
static iterator Begin (void)
static iterator End (void)
static iterator Insert (Status *ptr)
static void Erase (iterator it)
static void InitAll ()
static void ClearAllValueOK ()
static void EvaluateAll ()
static void LtoN ()
static void NtoL ()
Private Member Functions
StatusContainer ()
Static Private Member Functions
static std::list< Status * > * Instance (void)
Static Private Attributes
static std::list< Status * > * ListPtr =NULL
list of status variables
Detailed Description
StatusContainer - internal container of status variables (singleton)
Definition at line 1021 of file simlib.h.
Member Typedef Documentation
iterator
typedef std::list<Status*>::iterator simlib3::StatusContainer::iterator
Definition at line 1027 of file simlib.h.
Constructor & Destructor Documentation
StatusContainer()
simlib3::StatusContainer::StatusContainer () private
Member Function Documentation
Begin()
static iterator simlib3::StatusContainer::Begin (void) inline static
Definition at line 1037 of file simlib.h.
References Instance().
Referenced by simlib3::StatusMethod::FirstStatus(), simlib3::StatusMethod::GoToState(), simlib3::StatusMethod::RestoreState(), and simlib3::StatusMethod::StoreState().
ClearAllValueOK()
void simlib3::StatusContainer::ClearAllValueOK () static
Definition at line 589 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::SIMLIB_Dynamic().
End()
static iterator simlib3::StatusContainer::End (void) inline static
Definition at line 1041 of file simlib.h.
References Instance().
Referenced by simlib3::StatusMethod::GoToState(), simlib3::StatusMethod::LastStatus(), simlib3::StatusMethod::RestoreState(), and simlib3::StatusMethod::StoreState().
Erase()
void simlib3::StatusContainer::Erase (StatusContainer::iterator it) static
Definition at line 514 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::Status::~Status().
EvaluateAll()
void simlib3::StatusContainer::EvaluateAll () static
Definition at line 573 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::SIMLIB_Dynamic().
InitAll()
void simlib3::StatusContainer::InitAll () static
Definition at line 557 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::SIMLIB_ContinueInit().
Insert()
StatusContainer::iterator simlib3::StatusContainer::Insert (Status * ptr) static
Definition at line 503 of file intg.cc.
References Dprintf, Instance(), and ListPtr.
Referenced by simlib3::Status::CtrInit().
Instance()
std::list< Status * > * simlib3::StatusContainer::Instance (void) static private
Definition at line 488 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by Begin(), End(), and Insert().
isAny()
static bool simlib3::StatusContainer::isAny (void) inline static
Definition at line 1029 of file simlib.h.
References ListPtr.
Referenced by simlib3::Run(), and simlib3::SIMLIB_ContinueInit().
LtoN()
void simlib3::StatusContainer::LtoN () static
Definition at line 542 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::IntegrationMethod::Iterate().
NtoL()
void simlib3::StatusContainer::NtoL () static
Definition at line 527 of file intg.cc.
References Dprintf, and ListPtr.
Referenced by simlib3::IntegrationMethod::Prepare(), and simlib3::IntegrationMethod::Summarize().
Size()
static size_t simlib3::StatusContainer::Size (void) inline static
Definition at line 1033 of file simlib.h.
References ListPtr.
Referenced by simlib3::Status::CtrInit(), simlib3::StatusMethod::PrepareStep(), and simlib3::Status::~Status().
Member Data Documentation
ListPtr
std::list< Status * > * simlib3::StatusContainer::ListPtr =NULL static private
list of status variables
Definition at line 1023 of file simlib.h.
Referenced by ClearAllValueOK(), Erase(), EvaluateAll(), InitAll(), Insert(), Instance(), isAny(), LtoN(), NtoL(), and Size().
The documentation for this class was generated from the following files:
src/simlib.h
src/intg.cc