SIMLIB/C++: simlib3::aContiBlock3D2 Class Reference
simlib3::aContiBlock3D2 Class Reference
SIMLIB/C++ 3D extension
continuous block vith 2 inputs and alg.
#include <simlib3D.h>
Public Member Functions
aContiBlock3D2 (Input3D i1, Input3D i2)
Value3D Input1Value ()
Value3D Input2Value ()
Public Member Functions inherited from simlib3::aContiBlock3D
aContiBlock3D ()
~aContiBlock3D ()
virtual void _Eval ()
virtual Value3D Value ()=0
void Print ()
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Attributes
Input3D input1
Input3D input2
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::aContiBlock3D
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
continuous block vith 2 inputs and alg.
loop check
Definition at line 144 of file simlib3D.h.
Constructor & Destructor Documentation
aContiBlock3D2()
simlib3::aContiBlock3D2::aContiBlock3D2 (Input3D i1, Input3D i2)
Definition at line 221 of file simlib3D.cc.
References AlgLoopDetected, input1, input2, and simlib3::SIMLIB_error().
Member Function Documentation
Input1Value()
Value3D simlib3::aContiBlock3D2::Input1Value () inline
Definition at line 149 of file simlib3D.h.
References input1, and simlib3::Input3D::Value().
Referenced by simlib3::_Add3D::Value(), simlib3::_Sub3D::Value(), and simlib3::_Mul3D::Value().
Input2Value()
Value3D simlib3::aContiBlock3D2::Input2Value () inline
Definition at line 150 of file simlib3D.h.
References input2, and simlib3::Input3D::Value().
Referenced by simlib3::_Add3D::Value(), simlib3::_Sub3D::Value(), and simlib3::_Mul3D::Value().
Member Data Documentation
input1
Input3D simlib3::aContiBlock3D2::input1 private
Definition at line 145 of file simlib3D.h.
Referenced by aContiBlock3D2(), and Input1Value().
input2
Input3D simlib3::aContiBlock3D2::input2 private
Definition at line 146 of file simlib3D.h.
Referenced by aContiBlock3D2(), and Input2Value().
The documentation for this class was generated from the following files:
src/simlib3D.h
src/simlib3D.cc