SIMLIB/C++: simlib3::CalendarQueue Class Reference
simlib3::CalendarQueue Class Reference
CQ implementation of calendar.
Public Member Functions
virtual void ScheduleAt (Entity *p, double t) override
enqueue
virtual Entity * Get (Entity *p) override
dequeue
virtual Entity * GetFirst () override
dequeue first
virtual void clear (bool destroy=false) override
remove all
virtual const char * Name () override
virtual void debug_print () override
for debugging only
void visualize (const char *msg)
CalendarQueue::visualize – output suitable for Gnuplot.
Public Member Functions inherited from simlib3::Calendar
bool Empty () const
unsigned Size () const
virtual void ScheduleAt (Entity *e, double t)=0
enqueue
virtual Entity * GetFirst ()=0
dequeue first
virtual Entity * Get (Entity *e)=0
dequeue
virtual void clear (bool destroy_entities=false)=0
remove all scheduled entities
virtual const char * Name ()=0
virtual void debug_print ()=0
for debugging only
double MinTime () const
time of activation of first item
Static Public Member Functions
static CalendarQueue * create ()
create calendar instance
Static Public Member Functions inherited from simlib3::Calendar
static Calendar * instance ()
create/get single instance (singleton)
static bool instance_exists ()
check if the instance exists
Private Types
typedef CalendarListImplementation BucketList
Private Member Functions
bool list_impl ()
int time2bucket (double t)
Convert time to bucket number.
double time2bucket_top (double t)
Compute bucket top limit.
double estimate_bucket_width ()
compute new bucket width — EXPERIMENTAL
void switchtocq ()
switch to calendar queue implementation
void switchtolist ()
switch to list implementation
CalendarQueue ()
Initialize calendar queue.
~CalendarQueue ()
Destroy calendar queue.
void Resize (int grow=0)
Resize bucket array.
void SearchMinTime (double starttime)
compute new mintime
Private Attributes
BucketList * buckets
BucketList list
unsigned nbuckets
unsigned hi_bucket_mark
unsigned low_bucket_mark
unsigned nextbucket
unsigned numop
double bucket_width
double buckettop
double last_dequeue_time
double sumdelta
unsigned ndelta
Additional Inherited Members
Protected Member Functions inherited from simlib3::Calendar
void SetMinTime (double t)
set cache for faster access
Calendar ()
virtual ~Calendar ()
clear is called in derived class dtr
Static Protected Member Functions inherited from simlib3::Calendar
static void delete_instance ()
destroy single instance
Protected Attributes inherited from simlib3::Calendar
unsigned _size
number of scheduled items
Detailed Description
CQ implementation of calendar.
Definition at line 547 of file calendar.cc.
Member Typedef Documentation
BucketList
typedef CalendarListImplementation simlib3::CalendarQueue::BucketList private
Definition at line 548 of file calendar.cc.
Constructor & Destructor Documentation
CalendarQueue()
simlib3::CalendarQueue::CalendarQueue () private
Initialize calendar queue.
Definition at line 625 of file calendar.cc.
References Dprintf, simlib3::Calendar::SetMinTime(), and simlib3::SIMLIB_MAXTIME.
Referenced by create().
~CalendarQueue()
simlib3::CalendarQueue::~CalendarQueue () private
Destroy calendar queue.
Definition at line 1121 of file calendar.cc.
References simlib3::allocator, simlib3::EventNoticeAllocator::clear(), clear(), and Dprintf.
Member Function Documentation
clear()
void simlib3::CalendarQueue::clear (bool destroy = false) override virtual
remove all
clear calendar queue
Implements simlib3::Calendar.
Definition at line 1089 of file calendar.cc.
References simlib3::Calendar::_size, buckets, simlib3::CalendarListImplementation::clear(), clear(), Dprintf, simlib3::Calendar::Empty(), last_dequeue_time, list, list_impl(), nbuckets, ndelta, numop, simlib3::Calendar::SetMinTime(), simlib3::SIMLIB_MAXTIME, and sumdelta.
Referenced by clear(), and ~CalendarQueue().
create()
static CalendarQueue * simlib3::CalendarQueue::create () inline static
create calendar instance
Definition at line 596 of file calendar.cc.
References CalendarQueue(), simlib3::Calendar::delete_instance(), Dprintf, and simlib3::SIMLIB_atexit().
Referenced by simlib3::Calendar::instance().
debug_print()
void simlib3::CalendarQueue::debug_print () override virtual
for debugging only
Implements simlib3::Calendar.
Definition at line 1157 of file calendar.cc.
References buckets, simlib3::CalendarListImplementation::debug_print(), simlib3::Calendar::instance_exists(), nbuckets, and simlib3::Print().
estimate_bucket_width()
double simlib3::CalendarQueue::estimate_bucket_width () private
compute new bucket width — EXPERIMENTAL
Definition at line 837 of file calendar.cc.
References simlib3::CalendarListImplementation::begin(), bucket_width, buckets, Dprintf, simlib3::CalendarListImplementation::end(), simlib3::Calendar::MinTime(), simlib3::MUL_PAR, nbuckets, ndelta, simlib3::SIMLIB_error(), simlib3::SIMLIB_MAXTIME, sumdelta, t, time2bucket(), and time2bucket_top().
Referenced by Resize().
Get()
Entity * simlib3::CalendarQueue::Get (Entity * p) override virtual
dequeue
remove entity e from calendar
called only if rescheduling
Implements simlib3::Calendar.
Definition at line 735 of file calendar.cc.
References simlib3::Calendar::_size, simlib3::Entity::ActivationTime(), buckets, simlib3::Calendar::Empty(), EmptyCalendar, EntityIsNotScheduled, simlib3::CalendarListImplementation::first_time(), simlib3::Entity::Idle(), list, list_impl(), simlib3::LIST_MIN, low_bucket_mark, MAX_OP, simlib3::Calendar::MinTime(), numop, simlib3::CalendarListImplementation::remove(), Resize(), SearchMinTime(), simlib3::Calendar::SetMinTime(), simlib3::SIMLIB_error(), simlib3::SIMLIB_MAXTIME, switchtolist(), t, and time2bucket().
GetFirst()
Entity * simlib3::CalendarQueue::GetFirst () override virtual
dequeue first
dequeue
Implements simlib3::Calendar.
Definition at line 683 of file calendar.cc.
References simlib3::Calendar::_size, buckets, simlib3::Calendar::Empty(), EmptyCalendar, simlib3::CalendarListImplementation::first_time(), last_dequeue_time, list, list_impl(), simlib3::LIST_MIN, low_bucket_mark, MAX_OP, simlib3::Calendar::MinTime(), ndelta, nextbucket, numop, simlib3::CalendarListImplementation::remove_first(), Resize(), SearchMinTime(), simlib3::Calendar::SetMinTime(), simlib3::SIMLIB_error(), simlib3::SIMLIB_MAXTIME, sumdelta, switchtolist(), and time2bucket().
list_impl()
bool simlib3::CalendarQueue::list_impl () inline private
Definition at line 564 of file calendar.cc.
References buckets.
Referenced by clear(), Get(), GetFirst(), ScheduleAt(), and visualize().
Name()
virtual const char * simlib3::CalendarQueue::Name () inline override virtual
Implements simlib3::Calendar.
Definition at line 604 of file calendar.cc.
Resize()
void simlib3::CalendarQueue::Resize (int grow = 0) private
Resize bucket array.
Definition at line 920 of file calendar.cc.
References simlib3::Calendar::_size, bucket_width, buckets, simlib3::COEF_PAR, Dprintf, simlib3::CalendarListImplementation::empty(), estimate_bucket_width(), simlib3::CalendarListImplementation::extract_first(), hi_bucket_mark, simlib3::CalendarListImplementation::insert_extracted(), low_bucket_mark, simlib3::MINBUCKETS, nbuckets, numop, simlib3::EventNotice::time, and time2bucket().
Referenced by Get(), GetFirst(), and ScheduleAt().
ScheduleAt()
void simlib3::CalendarQueue::ScheduleAt (Entity * p, double t) override virtual
enqueue
schedule
Implements simlib3::Calendar.
Definition at line 646 of file calendar.cc.
References simlib3::Calendar::_size, buckets, Dprintf, hi_bucket_mark, simlib3::CalendarListImplementation::insert(), list, list_impl(), simlib3::LIST_MAX, MAX_OP, simlib3::Calendar::MinTime(), simlib3::SimObject::Name(), numop, Resize(), SchedulingBeforeTime, simlib3::Calendar::SetMinTime(), simlib3::SIMLIB_error(), switchtocq(), t, simlib3::Time, and time2bucket().
SearchMinTime()
void simlib3::CalendarQueue::SearchMinTime (double starttime) private
compute new mintime
Definition at line 782 of file calendar.cc.
References bucket_width, buckets, buckettop, simlib3::CalendarListImplementation::empty(), simlib3::Calendar::Empty(), simlib3::CalendarListImplementation::first_time(), nbuckets, nextbucket, simlib3::Calendar::SetMinTime(), simlib3::SIMLIB_error(), simlib3::SIMLIB_MAXTIME, t, time2bucket(), and time2bucket_top().
Referenced by Get(), and GetFirst().
switchtocq()
void simlib3::CalendarQueue::switchtocq () private
switch to calendar queue implementation
Definition at line 1020 of file calendar.cc.
References simlib3::Calendar::_size, simlib3::CalendarListImplementation::begin(), bucket_width, buckets, simlib3::COEF_PAR, simlib3::CalendarListImplementation::empty(), simlib3::CalendarListImplementation::end(), simlib3::CalendarListImplementation::extract_first(), hi_bucket_mark, simlib3::CalendarListImplementation::insert_extracted(), last_dequeue_time, list, low_bucket_mark, simlib3::Calendar::MinTime(), simlib3::MUL_PAR, nbuckets, ndelta, numop, simlib3::SIMLIB_warning(), sumdelta, simlib3::EventNotice::time, and time2bucket().
Referenced by ScheduleAt().
switchtolist()
void simlib3::CalendarQueue::switchtolist () private
switch to list implementation
Definition at line 993 of file calendar.cc.
References buckets, simlib3::CalendarListImplementation::empty(), simlib3::CalendarListImplementation::extract_first(), simlib3::CalendarListImplementation::insert_extracted(), list, and nbuckets.
Referenced by Get(), and GetFirst().
time2bucket()
int simlib3::CalendarQueue::time2bucket (double t) inline private
Convert time to bucket number.
Definition at line 567 of file calendar.cc.
References bucket_width, nbuckets, and t.
Referenced by estimate_bucket_width(), Get(), GetFirst(), Resize(), ScheduleAt(), SearchMinTime(), and switchtocq().
time2bucket_top()
double simlib3::CalendarQueue::time2bucket_top (double t) inline private
Compute bucket top limit.
Definition at line 575 of file calendar.cc.
References bucket_width, and t.
Referenced by estimate_bucket_width(), and SearchMinTime().
visualize()
void simlib3::CalendarQueue::visualize (const char * msg)
CalendarQueue::visualize – output suitable for Gnuplot.
Definition at line 1170 of file calendar.cc.
References simlib3::CalendarListImplementation::begin(), bucket_width, buckets, simlib3::Calendar::Empty(), simlib3::CalendarListImplementation::end(), list_impl(), simlib3::Calendar::MinTime(), nbuckets, numop, simlib3::Print(), and simlib3::Calendar::Size().
Member Data Documentation
bucket_width
double simlib3::CalendarQueue::bucket_width private
Definition at line 557 of file calendar.cc.
Referenced by estimate_bucket_width(), Resize(), SearchMinTime(), switchtocq(), time2bucket(), time2bucket_top(), and visualize().
buckets
BucketList* simlib3::CalendarQueue::buckets private
Definition at line 549 of file calendar.cc.
Referenced by clear(), debug_print(), estimate_bucket_width(), Get(), GetFirst(), list_impl(), Resize(), ScheduleAt(), SearchMinTime(), switchtocq(), switchtolist(), and visualize().
buckettop
double simlib3::CalendarQueue::buckettop private
Definition at line 558 of file calendar.cc.
Referenced by SearchMinTime().
hi_bucket_mark
unsigned simlib3::CalendarQueue::hi_bucket_mark private
Definition at line 552 of file calendar.cc.
Referenced by Resize(), ScheduleAt(), and switchtocq().
last_dequeue_time
double simlib3::CalendarQueue::last_dequeue_time private
Definition at line 559 of file calendar.cc.
Referenced by clear(), GetFirst(), and switchtocq().
list
BucketList simlib3::CalendarQueue::list private
Definition at line 550 of file calendar.cc.
Referenced by clear(), Get(), GetFirst(), ScheduleAt(), switchtocq(), and switchtolist().
low_bucket_mark
unsigned simlib3::CalendarQueue::low_bucket_mark private
Definition at line 553 of file calendar.cc.
Referenced by Get(), GetFirst(), Resize(), and switchtocq().
nbuckets
unsigned simlib3::CalendarQueue::nbuckets private
Definition at line 551 of file calendar.cc.
Referenced by clear(), debug_print(), estimate_bucket_width(), Resize(), SearchMinTime(), switchtocq(), switchtolist(), time2bucket(), and visualize().
ndelta
unsigned simlib3::CalendarQueue::ndelta private
Definition at line 561 of file calendar.cc.
Referenced by clear(), estimate_bucket_width(), GetFirst(), and switchtocq().
nextbucket
unsigned simlib3::CalendarQueue::nextbucket private
Definition at line 554 of file calendar.cc.
Referenced by GetFirst(), and SearchMinTime().
numop
unsigned simlib3::CalendarQueue::numop private
Definition at line 556 of file calendar.cc.
Referenced by clear(), Get(), GetFirst(), Resize(), ScheduleAt(), switchtocq(), and visualize().
sumdelta
double simlib3::CalendarQueue::sumdelta private
Definition at line 560 of file calendar.cc.
Referenced by clear(), estimate_bucket_width(), GetFirst(), and switchtocq().
The documentation for this class was generated from the following file:
src/calendar.cc