SIMLIB/C++: simlib3::aContiBlock2 Class Reference
simlib3::aContiBlock2 Class Reference
SIMLIB/C++
base for continuous blocks with two inputs
#include <simlib.h>
Public Member Functions
aContiBlock2 (Input i1, Input i2)
ctr for blocks with 2 inputs
double Input1Value ()
double Input2Value ()
Public Member Functions inherited from simlib3::aContiBlock
aContiBlock ()
virtual void _Eval ()
evaluate block (with loop detection)
virtual double Value ()=0
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Attributes
Input input1
Input input2
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::aContiBlock
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
base for continuous blocks with two inputs
Definition at line 959 of file simlib.h.
Constructor & Destructor Documentation
aContiBlock2()
simlib3::aContiBlock2::aContiBlock2 (Input i1, Input i2)
ctr for blocks with 2 inputs
Definition at line 79 of file continuous.cc.
References AlgLoopDetected, input1, input2, and simlib3::SIMLIB_error().
Member Function Documentation
Input1Value()
double simlib3::aContiBlock2::Input1Value () inline
Definition at line 964 of file simlib.h.
References input1, and simlib3::Input::Value().
Referenced by simlib3::_Add::Value(), simlib3::_Sub::Value(), simlib3::_Mul::Value(), simlib3::_Div::Value(), and simlib3::Function2::Value().
Input2Value()
double simlib3::aContiBlock2::Input2Value () inline
Definition at line 965 of file simlib.h.
References input2, and simlib3::Input::Value().
Referenced by simlib3::_Add::Value(), simlib3::_Sub::Value(), simlib3::_Mul::Value(), simlib3::_Div::Value(), and simlib3::Function2::Value().
Member Data Documentation
input1
Input simlib3::aContiBlock2::input1 private
Definition at line 960 of file simlib.h.
Referenced by aContiBlock2(), and Input1Value().
input2
Input simlib3::aContiBlock2::input2 private
Definition at line 961 of file simlib.h.
Referenced by aContiBlock2(), and Input2Value().
The documentation for this class was generated from the following files:
src/simlib.h
src/continuous.cc