SIMLIB/C++: simlib3::ABM4 Class Reference
simlib3::ABM4 Class Reference
#include <ni_abm4.h>
Public Member Functions
ABM4 (const char *name, const char *slave_name)
virtual ~ABM4 ()
virtual void Integrate (void) override
virtual bool PrepareStep (void) override
prepare the object for the step of integration
Public Member Functions inherited from simlib3::MultiStepMethod
MultiStepMethod (const char *name, const char *slave_name)
initialize multistep method
~MultiStepMethod ()
free dynamic data
virtual bool IsSingleStep (void) override
virtual void SetStarter (const char *slave_name)
set starting method for the multi-step method
virtual bool PrepareStep (void) override
prepare the object for the step of integration
virtual void TurnOff (void) override
turn off integration method and its slave (starter)
Public Member Functions inherited from simlib3::IntegrationMethod
IntegrationMethod (const char *name)
register method to list of methods and name it
virtual ~IntegrationMethod ()
destroy integration method (remove from list)
virtual bool IsSingleStep (void)=0
virtual void TurnOff (void)
turn off integration method: flush memories etc...
virtual void Integrate (void)=0
virtual bool PrepareStep (void)
prepare object for integration step
virtual void Resize (size_t size)
resize all the memories to the given size
Private Attributes
int ABM_Count
Memory Z [abm_ord]
Memory PRED
Additional Inherited Members
Static Public Member Functions inherited from simlib3::MultiStepMethod
static void SetStarter (const char *name, const char *slave_name)
set starting method for given multi-step method
static const char * GetStarter (const char *name)
obtain the name of the starting method of given method
Static Public Member Functions inherited from simlib3::IntegrationMethod
static void StepSim (void)
step of numerical integration method
static void IntegrationDone (void)
static void SetMethod (const char *name)
set method which will be used
static const char * GetMethod (void)
static void InitStep (double step_frag)
initialize step
static void FunCall (double step_frag)
static void SetOptStep (double opt_step)
static void SetStepSize (double step_size)
static bool IsConditionFlag (void)
static int GetErrNo (void)
static void SetErrNo (int num)
Protected Types inherited from simlib3::IntegrationMethod
typedef IntegratorContainer::iterator Iterator
Protected Member Functions inherited from simlib3::MultiStepMethod
SingleStepMethod * SlavePtr (void)
return pointer to the starting method (initialize it also)
Static Protected Member Functions inherited from simlib3::IntegrationMethod
static Iterator FirstIntegrator (void)
static Iterator LastIntegrator (void)
static bool StateCond (void)
check on changes of state conditions
static IntegrationMethod * SearchMethod (const char *name)
search method in the list of registrated methods
Static Protected Attributes inherited from simlib3::IntegrationMethod
static bool IsEndStepEvent =false
Detailed Description
Definition at line 26 of file ni_abm4.h.
Constructor & Destructor Documentation
ABM4()
simlib3::ABM4::ABM4 (const char * name, const char * slave_name) inline
Definition at line 32 of file ni_abm4.h.
~ABM4()
virtual simlib3::ABM4::~ABM4 () inline virtual
Definition at line 36 of file ni_abm4.h.
Member Function Documentation
Integrate()
void simlib3::ABM4::Integrate (void) override virtual
Implements simlib3::IntegrationMethod.
Definition at line 53 of file ni_abm4.cc.
References simlib3::_Print(), _SetTime, ABM_Count, simlib3::abm_ord, AccuracyError, Dprintf, simlib3::IntegrationMethod::FirstIntegrator(), simlib3::IntegrationMethod::Integrate(), simlib3::IntegrationMethod::IsEndStepEvent, simlib3::IntegrationMethod::LastIntegrator(), simlib3::max(), simlib3::min(), simlib3::OptStep, PRED, simlib3::SIMLIB_AbsoluteError, simlib3::SIMLIB_ConditionFlag, simlib3::SIMLIB_ContractStep, simlib3::SIMLIB_ContractStepFlag, simlib3::SIMLIB_DeltaTime, simlib3::SIMLIB_Dynamic(), simlib3::SIMLIB_ERRNO, simlib3::SIMLIB_MaxStep, simlib3::SIMLIB_MinStep, simlib3::SIMLIB_OptStep, simlib3::SIMLIB_RelativeError, simlib3::SIMLIB_StepSize, simlib3::SIMLIB_StepStartTime, simlib3::SIMLIB_warning(), simlib3::MultiStepMethod::SlavePtr(), simlib3::IntegrationMethod::StateCond(), simlib3::Time, and Z.
PrepareStep()
bool simlib3::ABM4::PrepareStep (void) override virtual
prepare the object for the step of integration
Reimplemented from simlib3::MultiStepMethod.
Definition at line 217 of file ni_abm4.cc.
References ABM_Count, Dprintf, and simlib3::MultiStepMethod::PrepareStep().
Member Data Documentation
ABM_Count
int simlib3::ABM4::ABM_Count private
Definition at line 28 of file ni_abm4.h.
Referenced by Integrate(), and PrepareStep().
PRED
Memory simlib3::ABM4::PRED private
Definition at line 30 of file ni_abm4.h.
Referenced by Integrate().
Z
Memory simlib3::ABM4::Z[abm_ord] private
Definition at line 29 of file ni_abm4.h.
Referenced by Integrate().
The documentation for this class was generated from the following files:
src/ni_abm4.h
src/ni_abm4.cc