SIMLIB/C++: simlib3::Entity Class Reference
simlib3::Entity Class Reference abstract
SIMLIB/C++
abstract base class for active entities (Process, Event) instances of derived classes provide Behavior() method implementation, execution can be scheduled in calendar
#include <simlib.h>
Public Types
typedef EntityPriority_t Priority_t
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Public Member Functions
unsigned long id () const
Entity (Priority_t p=DEFAULT_PRIORITY)
constructor
virtual ~Entity ()
destructor
operator Entity * ()
double ActivationTime ()
get activation time of entity - iff scheduled
it is here, because Entity has no knowledge of calendar activation record structure
void Activate ()
activate now
virtual void Activate (double t)
activate at time t (schedule)
virtual void Passivate ()
deactivation
virtual void Terminate ()=0
end Behavior() and remove entity
bool Idle ()
entity activation is not scheduled in calendar
void Cancel ()
end Behavior() and remove entity
virtual void Out () override
remove entity from queue
EventNotice * GetEventNotice ()
Public Member Functions inherited from simlib3::Link
Link ()
virtual ~Link ()
virtual void Into (List *l)
insert last
virtual void Out ()
remove from list
List * Where ()
where is linked
virtual bool isInQueue ()
present in queue
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Public Attributes
Priority_t Priority
priority of the entity (scheduling,queues)
Protected Attributes
unsigned long _Ident
unique identification number of entity
double _MarkTime
union {
double _RemainingTime
unsigned long _RequiredCapacity
};
ServicePriority_t _SPrio
priority of service in Facility
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Static Protected Attributes
static unsigned long _Number = 0L
current number of entities
Private Member Functions
virtual void _Run () noexcept=0
run the Behavior() function
Private Attributes
EventNotice * _evn
points to calendar item, iff scheduled
Friends
class Queue
class Facility
class Store
struct EventNotice
void SIMLIB_DoActions ()
Additional Inherited Members
Protected Member Functions inherited from simlib3::Link
Link (Link *p, Link *s, List *h)
Detailed Description
abstract base class for active entities (Process, Event) instances of derived classes provide Behavior() method implementation, execution can be scheduled in calendar
Definition at line 375 of file simlib.h.
Member Typedef Documentation
Priority_t
typedef EntityPriority_t simlib3::Entity::Priority_t
Definition at line 397 of file simlib.h.
Constructor & Destructor Documentation
Entity()
simlib3::Entity::Entity (Priority_t p = DEFAULT_PRIORITY)
constructor
Definition at line 33 of file entity.cc.
References _Ident, _Number, and Dprintf.
~Entity()
simlib3::Entity::~Entity () virtual
destructor
Definition at line 46 of file entity.cc.
References _Ident, _Number, Dprintf, simlib3::SQS::Get(), and Idle().
Member Function Documentation
_Run()
virtual void simlib3::Entity::_Run () private pure virtual noexcept
run the Behavior() function
Implemented in simlib3::Process, and simlib3::Event.
Activate() [1/2]
void simlib3::Entity::Activate () inline
activate now
Definition at line 408 of file simlib.h.
References Activate(), and simlib3::Time.
Referenced by Activate(), simlib3::Process::Activate(), simlib3::Event::Activate(), simlib3::Activate(), simlib3::Barrier::Break(), simlib3::Barrier::Enter(), simlib3::Process::Interrupt(), simlib3::Store::Leave(), simlib3::Facility::Release(), simlib3::Semaphore::V(), simlib3::Barrier::Wait(), and simlib3::Process::Wait().
Activate() [2/2]
void simlib3::Entity::Activate (double t) virtual
activate at time t (schedule)
entity activation at given time
Reimplemented in simlib3::Process, simlib3::Event, simlib3::Process, and simlib3::Event.
Definition at line 56 of file entity.cc.
References simlib3::SQS::Get(), Idle(), simlib3::SQS::ScheduleAt(), and t.
ActivationTime()
double simlib3::Entity::ActivationTime ()
get activation time of entity - iff scheduled
it is here, because Entity has no knowledge of calendar activation record structure
Definition at line 1358 of file calendar.cc.
References GetEventNotice(), Idle(), simlib3::SIMLIB_MAXTIME, and simlib3::EventNotice::time.
Referenced by simlib3::CalendarQueue::Get(), and simlib3::Facility::Seize().
Cancel()
void simlib3::Entity::Cancel () inline
end Behavior() and remove entity
Definition at line 413 of file simlib.h.
References Terminate().
GetEventNotice()
EventNotice * simlib3::Entity::GetEventNotice () inline
Definition at line 427 of file simlib.h.
References _evn.
Referenced by ActivationTime(), simlib3::EventNotice::Create(), and simlib3::CalendarListImplementation::remove().
id()
unsigned long simlib3::Entity::id () const inline
Definition at line 396 of file simlib.h.
References _Ident.
Referenced by simlib3::WaitUntilList::GetCurrent(), simlib3::WaitUntilList::InsertCurrent(), and simlib3::WaitUntilList::Remove().
Idle()
bool simlib3::Entity::Idle () inline
entity activation is not scheduled in calendar
Definition at line 412 of file simlib.h.
References _evn.
Referenced by simlib3::Process::_Run(), simlib3::Event::_Run(), Activate(), ActivationTime(), simlib3::CalendarList::Get(), simlib3::CalendarQueue::Get(), Passivate(), simlib3::SQS::ScheduleAt(), simlib3::Facility::Seize(), simlib3::Process::Terminate(), simlib3::Event::Terminate(), Terminate(), ~Entity(), and simlib3::Process::~Process().
operator Entity *()
simlib3::Entity::operator Entity * () inline
Definition at line 404 of file simlib.h.
Out()
void simlib3::Entity::Out () override virtual
remove entity from queue
Reimplemented from simlib3::Link.
Definition at line 90 of file entity.cc.
References simlib3::Link::Out().
Referenced by simlib3::Process::_Run(), simlib3::Process::Into(), simlib3::Store::Leave(), simlib3::Facility::Release(), simlib3::Process::Terminate(), and simlib3::Process::~Process().
Passivate()
void simlib3::Entity::Passivate () virtual
deactivation
Reimplemented in simlib3::Process.
Definition at line 68 of file entity.cc.
References simlib3::SQS::Get(), and Idle().
Referenced by simlib3::Sampler::Behavior(), simlib3::Barrier::Enter(), simlib3::Store::Enter(), simlib3::Process::Passivate(), simlib3::Passivate(), simlib3::Facility::Seize(), simlib3::Sampler::Stop(), simlib3::ZDelayTimer::Stop(), and simlib3::Barrier::Wait().
Terminate()
void simlib3::Entity::Terminate () pure virtual
end Behavior() and remove entity
passivate and destroy entity
Implemented in simlib3::Process, and simlib3::Event.
Definition at line 97 of file entity.cc.
References Dprintf, simlib3::SQS::Get(), Idle(), simlib3::SimObject::isAllocated(), simlib3::SimObject::Name(), and simlib3::SIMLIB_Current.
Referenced by Cancel().
Friends And Related Symbol Documentation
EventNotice
friend struct EventNotice friend
Definition at line 424 of file simlib.h.
Facility
friend class Facility friend
Definition at line 386 of file simlib.h.
Queue
friend class Queue friend
Definition at line 383 of file simlib.h.
SIMLIB_DoActions
void SIMLIB_DoActions () friend
Definition at line 135 of file run.cc.
Store
friend class Store friend
Definition at line 387 of file simlib.h.
Member Data Documentation
[union]
union { ... } simlib3::Entity
_evn
EventNotice* simlib3::Entity::_evn private
points to calendar item, iff scheduled
Definition at line 425 of file simlib.h.
Referenced by simlib3::EventNotice::create_reverse_link(), simlib3::EventNotice::delete_reverse_link(), GetEventNotice(), and Idle().
_Ident
unsigned long simlib3::Entity::_Ident protected
unique identification number of entity
Definition at line 378 of file simlib.h.
Referenced by simlib3::Process::_Run(), simlib3::Process::Activate(), simlib3::Event::Activate(), Entity(), id(), simlib3::Process::Interrupt(), simlib3::Process::Name(), simlib3::Event::Name(), simlib3::Process::Terminate(), simlib3::Process::Wait(), and ~Entity().
_MarkTime
double simlib3::Entity::_MarkTime protected
Definition at line 384 of file simlib.h.
Referenced by simlib3::Queue::Get(), and simlib3::Queue::PredIns().
_Number
unsigned long simlib3::Entity::_Number = 0L static protected
current number of entities
serial number of created entity
Definition at line 377 of file simlib.h.
Referenced by Entity(), and ~Entity().
_RemainingTime
double simlib3::Entity::_RemainingTime
Definition at line 390 of file simlib.h.
Referenced by simlib3::Facility::Release(), and simlib3::Facility::Seize().
_RequiredCapacity
unsigned long simlib3::Entity::_RequiredCapacity
Definition at line 391 of file simlib.h.
Referenced by simlib3::Store::Leave(), and simlib3::Store::QueueIn().
_SPrio
ServicePriority_t simlib3::Entity::_SPrio protected
priority of service in Facility
Definition at line 393 of file simlib.h.
Referenced by simlib3::Facility::QueueIn(), simlib3::Facility::QueueIn2(), simlib3::Facility::Release(), and simlib3::Facility::Seize().
Priority
Priority_t simlib3::Entity::Priority
priority of the entity (scheduling,queues)
priority of the entity
Definition at line 399 of file simlib.h.
Referenced by simlib3::EventNotice::Create(), simlib3::Queue::Insert(), simlib3::WaitUntilList::InsertCurrent(), simlib3::Facility::QueueIn(), simlib3::Facility::QueueIn2(), and simlib3::EventNotice::Set().
The documentation for this class was generated from the following files:
src/simlib.h
src/calendar.cc
src/entity.cc