SIMLIB/C++: simlib3::RKF5 Class Reference
simlib3::RKF5 Class Reference
#include <ni_rkf5.h>
Public Member Functions
RKF5 (const char *name)
virtual ~RKF5 ()
virtual void Integrate (void) override
Public Member Functions inherited from simlib3::SingleStepMethod
SingleStepMethod (const char *name)
virtual bool IsSingleStep (void) override
void SetStartMode (bool start_mode)
bool IsStartMode (void)
Public Member Functions inherited from simlib3::IntegrationMethod
IntegrationMethod (const char *name)
register method to list of methods and name it
virtual ~IntegrationMethod ()
destroy integration method (remove from list)
virtual bool IsSingleStep (void)=0
virtual void TurnOff (void)
turn off integration method: flush memories etc...
virtual void Integrate (void)=0
virtual bool PrepareStep (void)
prepare object for integration step
virtual void Resize (size_t size)
resize all the memories to the given size
Private Attributes
Memory A1
Memory A2
Memory A3
Memory A4
Memory A5
Memory A6
Additional Inherited Members
Static Public Member Functions inherited from simlib3::IntegrationMethod
static void StepSim (void)
step of numerical integration method
static void IntegrationDone (void)
static void SetMethod (const char *name)
set method which will be used
static const char * GetMethod (void)
static void InitStep (double step_frag)
initialize step
static void FunCall (double step_frag)
static void SetOptStep (double opt_step)
static void SetStepSize (double step_size)
static bool IsConditionFlag (void)
static int GetErrNo (void)
static void SetErrNo (int num)
Protected Types inherited from simlib3::IntegrationMethod
typedef IntegratorContainer::iterator Iterator
Static Protected Member Functions inherited from simlib3::IntegrationMethod
static Iterator FirstIntegrator (void)
static Iterator LastIntegrator (void)
static bool StateCond (void)
check on changes of state conditions
static IntegrationMethod * SearchMethod (const char *name)
search method in the list of registrated methods
Static Protected Attributes inherited from simlib3::IntegrationMethod
static bool IsEndStepEvent =false
Detailed Description
Definition at line 22 of file ni_rkf5.h.
Constructor & Destructor Documentation
RKF5()
simlib3::RKF5::RKF5 (const char * name) inline
Definition at line 26 of file ni_rkf5.h.
~RKF5()
virtual simlib3::RKF5::~RKF5 () inline virtual
Definition at line 29 of file ni_rkf5.h.
Member Function Documentation
Integrate()
void simlib3::RKF5::Integrate (void) override virtual
Implements simlib3::IntegrationMethod.
Definition at line 59 of file ni_rkf5.cc.
References simlib3::_Print(), _SetTime, A1, A2, A3, A4, A5, A6, AccuracyError, Dprintf, simlib3::IntegrationMethod::FirstIntegrator(), simlib3::IntegrationMethod::IsEndStepEvent, simlib3::SingleStepMethod::IsStartMode(), simlib3::IntegrationMethod::LastIntegrator(), simlib3::max(), simlib3::min(), simlib3::OptStep, simlib3::SIMLIB_AbsoluteError, simlib3::SIMLIB_ContractStep, simlib3::SIMLIB_ContractStepFlag, simlib3::SIMLIB_DeltaTime, simlib3::SIMLIB_Dynamic(), simlib3::SIMLIB_ERRNO, simlib3::SIMLIB_MaxStep, simlib3::SIMLIB_MinStep, simlib3::SIMLIB_OptStep, simlib3::SIMLIB_RelativeError, simlib3::SIMLIB_StepSize, simlib3::SIMLIB_StepStartTime, simlib3::SIMLIB_warning(), simlib3::IntegrationMethod::StateCond(), and simlib3::Time.
Member Data Documentation
A1
Memory simlib3::RKF5::A1 private
Definition at line 24 of file ni_rkf5.h.
Referenced by Integrate().
A2
Memory simlib3::RKF5::A2 private
Definition at line 24 of file ni_rkf5.h.
Referenced by Integrate().
A3
Memory simlib3::RKF5::A3 private
Definition at line 24 of file ni_rkf5.h.
Referenced by Integrate().
A4
Memory simlib3::RKF5::A4 private
Definition at line 24 of file ni_rkf5.h.
Referenced by Integrate().
A5
Memory simlib3::RKF5::A5 private
Definition at line 24 of file ni_rkf5.h.
Referenced by Integrate().
A6
Memory simlib3::RKF5::A6 private
Definition at line 24 of file ni_rkf5.h.
Referenced by Integrate().
The documentation for this class was generated from the following files:
src/ni_rkf5.h
src/ni_rkf5.cc