SIMLIB/C++: simlib3::ParameterVector Class Reference
simlib3::ParameterVector Class Reference
#include <optimize.h>
Public Member Functions
ParameterVector (int sz, Param *a)
ParameterVector (const ParameterVector &a)
ParameterVector & operator= (const ParameterVector &a)
~ParameterVector ()
Param & operator[] (int i)
const Param & operator[] (int i) const
int size () const
void PrintValues () const
void Print () const
Param & operator[] (const char *name)
Private Member Functions
int search (const char *name)
Private Attributes
int n
Param * p
Friends
bool operator== (const ParameterVector &p1, const ParameterVector &p2)
Detailed Description
Definition at line 57 of file optimize.h.
Constructor & Destructor Documentation
ParameterVector() [1/2]
simlib3::ParameterVector::ParameterVector (int sz, Param * a)
Definition at line 53 of file opt-param.cc.
References n, and p.
ParameterVector() [2/2]
simlib3::ParameterVector::ParameterVector (const ParameterVector & a)
Definition at line 61 of file opt-param.cc.
References n, and p.
~ParameterVector()
simlib3::ParameterVector::~ParameterVector ()
Definition at line 80 of file opt-param.cc.
References p.
Member Function Documentation
operator=()
ParameterVector & simlib3::ParameterVector::operator= (const ParameterVector & a)
Definition at line 69 of file opt-param.cc.
References n, and p.
operator[]() [1/3]
Param & simlib3::ParameterVector::operator[] (const char * name) inline
Definition at line 75 of file optimize.h.
References p, and search().
operator[]() [2/3]
Param & simlib3::ParameterVector::operator[] (int i) inline
Definition at line 69 of file optimize.h.
References p.
operator[]() [3/3]
const Param & simlib3::ParameterVector::operator[] (int i) const inline
Definition at line 70 of file optimize.h.
References p.
Print()
void simlib3::ParameterVector::Print () const
Definition at line 103 of file opt-param.cc.
References n, p, and Print().
Referenced by Print(), and PrintValues().
PrintValues()
void simlib3::ParameterVector::PrintValues () const
Definition at line 97 of file opt-param.cc.
References n, p, and Print().
Referenced by simlib3::Optimize_hooke().
search()
int simlib3::ParameterVector::search (const char * name) private
Definition at line 40 of file opt-param.cc.
References n, and p.
Referenced by operator[]().
size()
int simlib3::ParameterVector::size () const inline
Definition at line 71 of file optimize.h.
References n.
Referenced by simlib3::hooke_step(), simlib3::move_to_next_point(), and simlib3::Optimize_hooke().
Friends And Related Symbol Documentation
operator==
bool operator== (const ParameterVector & p1, const ParameterVector & p2) friend
Definition at line 86 of file opt-param.cc.
Member Data Documentation
n
int simlib3::ParameterVector::n private
Definition at line 59 of file optimize.h.
Referenced by operator=(), ParameterVector(), ParameterVector(), Print(), PrintValues(), search(), and size().
p
Param* simlib3::ParameterVector::p private
Definition at line 60 of file optimize.h.
Referenced by operator=(), operator[](), operator[](), operator[](), ParameterVector(), ParameterVector(), Print(), PrintValues(), search(), and ~ParameterVector().
The documentation for this class was generated from the following files:
src/optimize.h
src/opt-param.cc