SIMLIB/C++: simlib3::Value2D Class Reference
simlib3::Value2D Class Reference
SIMLIB/C++ 2D extension
2D vector value
#include <simlib2D.h>
Public Member Functions
Value2D (double x, double y)
double x () const
double y () const
Value2D operator+ (Value2D b)
Value2D operator- (Value2D b)
void Print ()
Private Attributes
double _x
double _y
Friends
double abs (const Value2D &a)
Value2D operator+ (const Value2D &a, const Value2D &b)
Value2D operator- (const Value2D &a, const Value2D &b)
Value2D operator- (const Value2D &a)
Value2D operator* (const Value2D &a, const double b)
Value2D operator* (const double a, const Value2D &b)
double scalar_product (const Value2D &a, const Value2D &b)
Value2D operator/ (const Value2D &a, const double b)
Detailed Description
2D vector value
Definition at line 31 of file simlib2D.h.
Constructor & Destructor Documentation
Value2D()
simlib3::Value2D::Value2D (double x, double y) inline
Definition at line 34 of file simlib2D.h.
Member Function Documentation
operator+()
Value2D simlib3::Value2D::operator+ (Value2D b) inline
Definition at line 40 of file simlib2D.h.
References _x, and _y.
operator-()
Value2D simlib3::Value2D::operator- (Value2D b) inline
Definition at line 41 of file simlib2D.h.
References _x, and _y.
Print()
void simlib3::Value2D::Print () inline
Definition at line 42 of file simlib2D.h.
References _x, _y, and Print().
Referenced by Print(), simlib3::aContiBlock2D::Print(), and simlib3::Print().
x()
double simlib3::Value2D::x () const inline
Definition at line 35 of file simlib2D.h.
References _x.
Referenced by simlib3::Integrator2D::operator=(), simlib3::Integrator2D::operator=(), simlib3::_XYpart::Value(), and simlib3::Integrator2D::special_input::Value().
y()
double simlib3::Value2D::y () const inline
Definition at line 36 of file simlib2D.h.
References _y.
Referenced by simlib3::Integrator2D::operator=(), simlib3::Integrator2D::operator=(), simlib3::_XYpart::Value(), and simlib3::Integrator2D::special_input::Value().
Friends And Related Symbol Documentation
abs
double abs (const Value2D & a) friend
Definition at line 38 of file simlib2D.cc.
operator* [1/2]
Value2D operator* (const double a, const Value2D & b) friend
Definition at line 73 of file simlib2D.cc.
operator* [2/2]
Value2D operator* (const Value2D & a, const double b) friend
Definition at line 68 of file simlib2D.cc.
operator+
Value2D operator+ (const Value2D & a, const Value2D & b) friend
Definition at line 43 of file simlib2D.cc.
operator- [1/2]
Value2D operator- (const Value2D & a) friend
Definition at line 53 of file simlib2D.cc.
operator- [2/2]
Value2D operator- (const Value2D & a, const Value2D & b) friend
Definition at line 48 of file simlib2D.cc.
operator/
Value2D operator/ (const Value2D & a, const double b) friend
Definition at line 83 of file simlib2D.cc.
scalar_product
double scalar_product (const Value2D & a, const Value2D & b) friend
Definition at line 78 of file simlib2D.cc.
Member Data Documentation
_x
double simlib3::Value2D::_x private
Definition at line 32 of file simlib2D.h.
Referenced by operator+(), operator-(), Print(), and x().
_y
double simlib3::Value2D::_y private
Definition at line 32 of file simlib2D.h.
Referenced by operator+(), operator-(), Print(), and y().
The documentation for this class was generated from the following file:
src/simlib2D.h