SIMLIB/C++: simlib3::SingleStepMethod Class Reference
simlib3::SingleStepMethod Class Reference
base for single-step integration methods
#include <simlib.h>
Public Member Functions
SingleStepMethod (const char *name)
virtual bool IsSingleStep (void) override
void SetStartMode (bool start_mode)
bool IsStartMode (void)
Public Member Functions inherited from simlib3::IntegrationMethod
IntegrationMethod (const char *name)
register method to list of methods and name it
virtual ~IntegrationMethod ()
destroy integration method (remove from list)
virtual bool IsSingleStep (void)=0
virtual void TurnOff (void)
turn off integration method: flush memories etc...
virtual void Integrate (void)=0
virtual bool PrepareStep (void)
prepare object for integration step
virtual void Resize (size_t size)
resize all the memories to the given size
Private Attributes
bool StartMode
Additional Inherited Members
Static Public Member Functions inherited from simlib3::IntegrationMethod
static void StepSim (void)
step of numerical integration method
static void IntegrationDone (void)
static void SetMethod (const char *name)
set method which will be used
static const char * GetMethod (void)
static void InitStep (double step_frag)
initialize step
static void FunCall (double step_frag)
static void SetOptStep (double opt_step)
static void SetStepSize (double step_size)
static bool IsConditionFlag (void)
static int GetErrNo (void)
static void SetErrNo (int num)
Protected Types inherited from simlib3::IntegrationMethod
typedef IntegratorContainer::iterator Iterator
Static Protected Member Functions inherited from simlib3::IntegrationMethod
static Iterator FirstIntegrator (void)
static Iterator LastIntegrator (void)
static bool StateCond (void)
check on changes of state conditions
static IntegrationMethod * SearchMethod (const char *name)
search method in the list of registrated methods
Static Protected Attributes inherited from simlib3::IntegrationMethod
static bool IsEndStepEvent =false
Detailed Description
base for single-step integration methods
Definition at line 1141 of file simlib.h.
Constructor & Destructor Documentation
SingleStepMethod()
simlib3::SingleStepMethod::SingleStepMethod (const char * name) inline explicit
Definition at line 1147 of file simlib.h.
Member Function Documentation
IsSingleStep()
virtual bool simlib3::SingleStepMethod::IsSingleStep (void) inline override virtual
Implements simlib3::IntegrationMethod.
Definition at line 1150 of file simlib.h.
IsStartMode()
bool simlib3::SingleStepMethod::IsStartMode (void) inline
Definition at line 1154 of file simlib.h.
References StartMode.
Referenced by simlib3::EULER::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), and simlib3::RKF8::Integrate().
SetStartMode()
void simlib3::SingleStepMethod::SetStartMode (bool start_mode) inline
Definition at line 1151 of file simlib.h.
References StartMode.
Referenced by simlib3::MultiStepMethod::PrepareStep(), and simlib3::MultiStepMethod::TurnOff().
Member Data Documentation
StartMode
bool simlib3::SingleStepMethod::StartMode private
Definition at line 1145 of file simlib.h.
Referenced by IsStartMode(), and SetStartMode().
The documentation for this class was generated from the following file:
src/simlib.h