SIMLIB/C++: simlib3::aCondition Class Reference
simlib3::aCondition Class Reference abstract
SIMLIB/C++
abstract base class for all state-condition blocks State event in combined model is executed at the time when the condition changes its boolean value
#include <simlib.h>
Public Member Functions
aCondition ()
~aCondition ()
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Static Public Member Functions
static void InitAll ()
static void SetAll ()
static void TestAll ()
static void AllActions ()
static bool isAny ()
Private Member Functions
void operator= (const aCondition &)=delete
aCondition (const aCondition &)=delete
virtual void Init ()=0
initialize
virtual void SetNewStatus ()=0
update
virtual bool Test ()=0
test of the condition
virtual void Action ()=0
state event description
Private Attributes
aCondition * Next
Static Private Attributes
static aCondition * First = 0
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
abstract base class for all state-condition blocks State event in combined model is executed at the time when the condition changes its boolean value
Definition at line 1484 of file simlib.h.
Constructor & Destructor Documentation
aCondition() [1/2]
simlib3::aCondition::aCondition (const aCondition &) private delete
aCondition() [2/2]
simlib3::aCondition::aCondition ()
Definition at line 36 of file cond.cc.
References First.
~aCondition()
simlib3::aCondition::~aCondition ()
Definition at line 42 of file cond.cc.
References First, and Next.
Member Function Documentation
Action()
virtual void simlib3::aCondition::Action () private pure virtual
state event description
AllActions()
void simlib3::aCondition::AllActions () static
Change???? ### !!!!
Definition at line 130 of file cond.cc.
References First, and Next.
Referenced by simlib3::SIMLIB_DoConditions().
Init()
virtual void simlib3::aCondition::Init () private pure virtual
initialize
Implemented in simlib3::Condition.
InitAll()
void simlib3::aCondition::InitAll () static
Definition at line 56 of file cond.cc.
References First, Next, and simlib3::SIMLIB_ConditionFlag.
Referenced by simlib3::SIMLIB_ContinueInit().
isAny()
bool simlib3::aCondition::isAny () static
Definition at line 70 of file cond.cc.
References First.
Referenced by simlib3::SIMLIB_ContinueInit().
operator=()
void simlib3::aCondition::operator= (const aCondition &) private delete
SetAll()
void simlib3::aCondition::SetAll () static
Definition at line 65 of file cond.cc.
References First, and Next.
Referenced by simlib3::SIMLIB_ContinueInit(), and simlib3::SIMLIB_DoConditions().
SetNewStatus()
virtual void simlib3::aCondition::SetNewStatus () private pure virtual
update
Implemented in simlib3::Condition.
Test()
virtual bool simlib3::aCondition::Test () private pure virtual
test of the condition
Implemented in simlib3::Condition, simlib3::ConditionUp, and simlib3::ConditionDown.
TestAll()
void simlib3::aCondition::TestAll () static
Definition at line 123 of file cond.cc.
References First, Next, and simlib3::SIMLIB_ConditionFlag.
Referenced by simlib3::IntegrationMethod::Iterate(), simlib3::IntegrationMethod::Prepare(), simlib3::SIMLIB_ContinueInit(), and simlib3::IntegrationMethod::StateCond().
Member Data Documentation
First
aCondition * simlib3::aCondition::First = 0 static private
Definition at line 1485 of file simlib.h.
Referenced by aCondition(), AllActions(), InitAll(), isAny(), SetAll(), TestAll(), and ~aCondition().
Next
aCondition* simlib3::aCondition::Next private
Definition at line 1486 of file simlib.h.
Referenced by AllActions(), InitAll(), SetAll(), TestAll(), and ~aCondition().
The documentation for this class was generated from the following files:
src/simlib.h
src/cond.cc