SIMLIB/C++: simlib3::aContiBlock3 Class Reference
simlib3::aContiBlock3 Class Reference
SIMLIB/C++
base for continuous blocks vith three inputs and algebraic loop check
#include <simlib.h>
Public Member Functions
aContiBlock3 (Input i1, Input i2, Input i3)
ctr for blocks with 3 inputs
double Input1Value ()
double Input2Value ()
double Input3Value ()
Public Member Functions inherited from simlib3::aContiBlock
aContiBlock ()
virtual void _Eval ()
evaluate block (with loop detection)
virtual double Value ()=0
get block output value
this method should be defined in classes derived from aContiBlock
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Private Attributes
Input input1
Input input2
Input input3
Additional Inherited Members
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Protected Attributes inherited from simlib3::aContiBlock
bool isEvaluated
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Detailed Description
base for continuous blocks vith three inputs and algebraic loop check
Definition at line 971 of file simlib.h.
Constructor & Destructor Documentation
aContiBlock3()
simlib3::aContiBlock3::aContiBlock3 (Input i1, Input i2, Input i3)
ctr for blocks with 3 inputs
Definition at line 88 of file continuous.cc.
References AlgLoopDetected, input1, input2, input3, and simlib3::SIMLIB_error().
Member Function Documentation
Input1Value()
double simlib3::aContiBlock3::Input1Value () inline
Definition at line 977 of file simlib.h.
References input1, and simlib3::Input::Value().
Input2Value()
double simlib3::aContiBlock3::Input2Value () inline
Definition at line 978 of file simlib.h.
References input2, and simlib3::Input::Value().
Input3Value()
double simlib3::aContiBlock3::Input3Value () inline
Definition at line 979 of file simlib.h.
References input3, and simlib3::Input::Value().
Member Data Documentation
input1
Input simlib3::aContiBlock3::input1 private
Definition at line 972 of file simlib.h.
Referenced by aContiBlock3(), and Input1Value().
input2
Input simlib3::aContiBlock3::input2 private
Definition at line 973 of file simlib.h.
Referenced by aContiBlock3(), and Input2Value().
input3
Input simlib3::aContiBlock3::input3 private
Definition at line 974 of file simlib.h.
Referenced by aContiBlock3(), and Input3Value().
The documentation for this class was generated from the following files:
src/simlib.h
src/continuous.cc