SIMLIB/C++: simlib3::Value3D Class Reference
simlib3::Value3D Class Reference
SIMLIB/C++ 3D extension
3D vector value
#include <simlib3D.h>
Public Member Functions
Value3D (double x, double y, double z)
double x () const
double y () const
double z () const
Value3D operator+ (Value3D b)
Value3D operator- (Value3D b)
void Print ()
Private Attributes
double _x
double _y
double _z
Friends
double abs (const Value3D &a)
Value3D operator+ (const Value3D &a, const Value3D &b)
Value3D operator- (const Value3D &a, const Value3D &b)
Value3D operator- (const Value3D &a)
Value3D operator* (const Value3D &a, const Value3D &b)
Value3D operator* (const Value3D &a, const double b)
Value3D operator* (const double a, const Value3D &b)
double scalar_product (const Value3D &a, const Value3D &b)
Value3D operator/ (const Value3D &a, const double b)
Detailed Description
3D vector value
Definition at line 31 of file simlib3D.h.
Constructor & Destructor Documentation
Value3D()
simlib3::Value3D::Value3D (double x, double y, double z) inline
Definition at line 34 of file simlib3D.h.
Member Function Documentation
operator+()
Value3D simlib3::Value3D::operator+ (Value3D b) inline
Definition at line 41 of file simlib3D.h.
References _x, _y, and _z.
operator-()
Value3D simlib3::Value3D::operator- (Value3D b) inline
Definition at line 42 of file simlib3D.h.
References _x, _y, and _z.
Print()
void simlib3::Value3D::Print () inline
Definition at line 43 of file simlib3D.h.
References _x, _y, _z, and Print().
Referenced by Print(), simlib3::aContiBlock3D::Print(), and simlib3::Print().
x()
double simlib3::Value3D::x () const inline
Definition at line 35 of file simlib3D.h.
References _x.
Referenced by simlib3::Integrator3D::Init(), simlib3::Integrator3D::operator=(), simlib3::Integrator3D::operator=(), simlib3::_XYZpart::Value(), and simlib3::Integrator3D::special_input::Value().
y()
double simlib3::Value3D::y () const inline
Definition at line 36 of file simlib3D.h.
References _y.
Referenced by simlib3::Integrator3D::Init(), simlib3::Integrator3D::operator=(), simlib3::Integrator3D::operator=(), simlib3::_XYZpart::Value(), and simlib3::Integrator3D::special_input::Value().
z()
double simlib3::Value3D::z () const inline
Definition at line 37 of file simlib3D.h.
References _z.
Referenced by simlib3::Integrator3D::Init(), simlib3::Integrator3D::operator=(), simlib3::Integrator3D::operator=(), simlib3::_XYZpart::Value(), and simlib3::Integrator3D::special_input::Value().
Friends And Related Symbol Documentation
abs
double abs (const Value3D & a) friend
Definition at line 38 of file simlib3D.cc.
operator* [1/3]
Value3D operator* (const double a, const Value3D & b) friend
Definition at line 71 of file simlib3D.cc.
operator* [2/3]
Value3D operator* (const Value3D & a, const double b) friend
Definition at line 66 of file simlib3D.cc.
operator* [3/3]
Value3D operator* (const Value3D & a, const Value3D & b) friend
Definition at line 58 of file simlib3D.cc.
operator+
Value3D operator+ (const Value3D & a, const Value3D & b) friend
Definition at line 43 of file simlib3D.cc.
operator- [1/2]
Value3D operator- (const Value3D & a) friend
Definition at line 53 of file simlib3D.cc.
operator- [2/2]
Value3D operator- (const Value3D & a, const Value3D & b) friend
Definition at line 48 of file simlib3D.cc.
operator/
Value3D operator/ (const Value3D & a, const double b) friend
Definition at line 81 of file simlib3D.cc.
scalar_product
double scalar_product (const Value3D & a, const Value3D & b) friend
Definition at line 76 of file simlib3D.cc.
Member Data Documentation
_x
double simlib3::Value3D::_x private
Definition at line 32 of file simlib3D.h.
Referenced by operator+(), operator-(), Print(), and x().
_y
double simlib3::Value3D::_y private
Definition at line 32 of file simlib3D.h.
Referenced by operator+(), operator-(), Print(), and y().
_z
double simlib3::Value3D::_z private
Definition at line 32 of file simlib3D.h.
Referenced by operator+(), operator-(), Print(), and z().
The documentation for this class was generated from the following file:
src/simlib3D.h