SIMLIB/C++: simlib3::EventNoticeAllocator Class Reference
simlib3::EventNoticeAllocator Class Reference
allocate activation records fast
Public Member Functions
EventNoticeAllocator ()
~EventNoticeAllocator ()
void free (EventNotice *en)
free EventNotice, add to freelist for future allocation
EventNotice * alloc (Entity *p, double t)
EventNotice allocation or reuse from freelist.
void clear ()
clear: delete all free-list items
Private Attributes
EventNoticeLinkBase * l
unsigned freed
Static Private Attributes
static const unsigned MAXSIZELIMIT = 1000000
Detailed Description
allocate activation records fast
Definition at line 199 of file calendar.cc.
Constructor & Destructor Documentation
EventNoticeAllocator()
simlib3::EventNoticeAllocator::EventNoticeAllocator () inline
Definition at line 204 of file calendar.cc.
~EventNoticeAllocator()
simlib3::EventNoticeAllocator::~EventNoticeAllocator () inline
Definition at line 205 of file calendar.cc.
References clear().
Member Function Documentation
alloc()
EventNotice * simlib3::EventNoticeAllocator::alloc (Entity * p, double t) inline
EventNotice allocation or reuse from freelist.
Definition at line 225 of file calendar.cc.
References freed, l, simlib3::EventNotice::Set(), simlib3::EventNoticeLinkBase::succ, and t.
Referenced by simlib3::EventNotice::Create().
clear()
void simlib3::EventNoticeAllocator::clear () inline
clear: delete all free-list items
Definition at line 238 of file calendar.cc.
References l, and simlib3::EventNoticeLinkBase::succ.
Referenced by simlib3::CalendarListImplementation::~CalendarListImplementation(), simlib3::CalendarQueue::~CalendarQueue(), and ~EventNoticeAllocator().
free()
void simlib3::EventNoticeAllocator::free (EventNotice * en) inline
free EventNotice, add to freelist for future allocation
Definition at line 210 of file calendar.cc.
References simlib3::EventNotice::delete_reverse_link(), freed, l, MAXSIZELIMIT, simlib3::EventNoticeLinkBase::pred, simlib3::EventNoticeLinkBase::remove(), and simlib3::EventNoticeLinkBase::succ.
Referenced by simlib3::EventNotice::Destroy().
Member Data Documentation
freed
unsigned simlib3::EventNoticeAllocator::freed private
Definition at line 202 of file calendar.cc.
Referenced by alloc(), and free().
l
EventNoticeLinkBase* simlib3::EventNoticeAllocator::l private
Definition at line 201 of file calendar.cc.
Referenced by alloc(), clear(), and free().
MAXSIZELIMIT
const unsigned simlib3::EventNoticeAllocator::MAXSIZELIMIT = 1000000 static private
Definition at line 200 of file calendar.cc.
Referenced by free().
The documentation for this class was generated from the following file:
src/calendar.cc