SIMLIB/C++: simlib3::Input Class Reference
simlib3::Input Class Reference
SIMLIB/C++
continuous block connection (transparent reference) wrapper for pointer to objects of aContiBlock derived classes
(small object, without virtual methods)
It is used for referencing of continuous blocks in block-expressions.
#include <simlib.h>
Public Member Functions
Input (const Input &i)
transparent copy of block reference
Input (aContiBlock &cb)
reference to block
Input (aContiBlock *cb)
pointer to block
Input (const double c)
create block of type Constant WARNING: using C++ variable in block expression creates Constant block
~Input ()
Input Set (Input i)
Redirect the reference.
Input & operator= (const Input &x)
Redirect the reference.
double Value () const
get target block value
bool operator== (aContiBlock *p) const
Private Member Functions
Input ()=delete
Private Attributes
aContiBlock * bp
Detailed Description
continuous block connection (transparent reference) wrapper for pointer to objects of aContiBlock derived classes
(small object, without virtual methods)
It is used for referencing of continuous blocks in block-expressions.
All references are transparent. There is a problem with initialization order. Using uninitialized Input is an error. If you need a block independent on initialization order, use Expression.
Definition at line 895 of file simlib.h.
Constructor & Destructor Documentation
Input() [1/5]
simlib3::Input::Input () private delete
Input() [2/5]
simlib3::Input::Input (const Input & i) inline
transparent copy of block reference
Definition at line 900 of file simlib.h.
References bp, and RegisterReference.
Input() [3/5]
simlib3::Input::Input (aContiBlock & cb) inline
reference to block
Definition at line 903 of file simlib.h.
References bp, and RegisterReference.
Input() [4/5]
simlib3::Input::Input (aContiBlock * cb) inline
pointer to block
Definition at line 904 of file simlib.h.
References bp, and RegisterReference.
Input() [5/5]
simlib3::Input::Input (const double c) inline
create block of type Constant WARNING: using C++ variable in block expression creates Constant block
Definition at line 908 of file simlib.h.
References bp, and RegisterReference.
~Input()
simlib3::Input::~Input () inline
Definition at line 910 of file simlib.h.
References bp, and UnRegisterReference.
Member Function Documentation
operator=()
Input & simlib3::Input::operator= (const Input & x) inline
Redirect the reference.
Definition at line 923 of file simlib.h.
References bp, RegisterReference, and UnRegisterReference.
operator==()
bool simlib3::Input::operator== (aContiBlock * p) const inline
Definition at line 933 of file simlib.h.
References bp.
Set()
Input simlib3::Input::Set (Input i) inline
Redirect the reference.
Definition at line 913 of file simlib.h.
References bp, RegisterReference, and UnRegisterReference.
Referenced by simlib3::Integrator::SetInput(), and simlib3::Condition::SetInput().
Value()
double simlib3::Input::Value () const inline
get target block value
Definition at line 931 of file simlib.h.
References bp, and simlib3::aContiBlock::Value().
Referenced by simlib3::aContiBlock2::Input1Value(), simlib3::aContiBlock3::Input1Value(), simlib3::aContiBlock2::Input2Value(), simlib3::aContiBlock3::Input2Value(), simlib3::aContiBlock3::Input3Value(), simlib3::aContiBlock1::InputValue(), simlib3::Integrator::InputValue(), simlib3::Condition::Test(), simlib3::_Mul2D1D::Value(), simlib3::_Div2D::Value(), simlib3::Adaptor2D::Value(), simlib3::_Mul3D1D::Value(), simlib3::_Div3D::Value(), and simlib3::Adaptor3D::Value().
Member Data Documentation
bp
aContiBlock* simlib3::Input::bp private
Definition at line 896 of file simlib.h.
Referenced by Input(), Input(), Input(), Input(), operator=(), operator==(), Set(), Value(), and ~Input().
The documentation for this class was generated from the following file:
src/simlib.h