SIMLIB/C++: simlib3::Calendar Class Reference
simlib3::Calendar Class Reference abstract
common interface for all calendar (PES) implementations
Public Member Functions
bool Empty () const
unsigned Size () const
virtual void ScheduleAt (Entity *e, double t)=0
enqueue
virtual Entity * GetFirst ()=0
dequeue first
virtual Entity * Get (Entity *e)=0
dequeue
virtual void clear (bool destroy_entities=false)=0
remove all scheduled entities
virtual const char * Name ()=0
virtual void debug_print ()=0
for debugging only
double MinTime () const
time of activation of first item
Static Public Member Functions
static Calendar * instance ()
create/get single instance (singleton)
static bool instance_exists ()
check if the instance exists
Protected Member Functions
void SetMinTime (double t)
set cache for faster access
Calendar ()
virtual ~Calendar ()
clear is called in derived class dtr
Static Protected Member Functions
static void delete_instance ()
destroy single instance
Protected Attributes
unsigned _size
number of scheduled items
Private Attributes
double mintime
activation time of first event
Static Private Attributes
static Calendar * _instance = 0
pointer to single instance
Friends
void SetCalendar (const char *name)
choose calendar implementation default is list
Detailed Description
common interface for all calendar (PES) implementations
Definition at line 67 of file calendar.cc.
Constructor & Destructor Documentation
Calendar()
simlib3::Calendar::Calendar () inline protected
Definition at line 105 of file calendar.cc.
~Calendar()
virtual simlib3::Calendar::~Calendar () inline protected virtual
clear is called in derived class dtr
Definition at line 106 of file calendar.cc.
Member Function Documentation
clear()
virtual void simlib3::Calendar::clear (bool destroy_entities = false) pure virtual
remove all scheduled entities
Implemented in simlib3::CalendarList, and simlib3::CalendarQueue.
Referenced by simlib3::SQS::Clear().
debug_print()
virtual void simlib3::Calendar::debug_print () pure virtual
for debugging only
Implemented in simlib3::CalendarList, and simlib3::CalendarQueue.
Referenced by simlib3::SQS::debug_print().
delete_instance()
void simlib3::Calendar::delete_instance () static protected
destroy single instance
Definition at line 1216 of file calendar.cc.
References _instance, and Dprintf.
Referenced by simlib3::CalendarList::create(), and simlib3::CalendarQueue::create().
Empty()
bool simlib3::Calendar::Empty () const inline
Definition at line 69 of file calendar.cc.
References _size.
Referenced by simlib3::CalendarQueue::clear(), simlib3::SQS::Empty(), simlib3::CalendarList::Get(), simlib3::CalendarQueue::Get(), simlib3::CalendarList::GetFirst(), simlib3::CalendarQueue::GetFirst(), simlib3::CalendarQueue::SearchMinTime(), and simlib3::CalendarQueue::visualize().
Get()
virtual Entity * simlib3::Calendar::Get (Entity * e) pure virtual
dequeue
Implemented in simlib3::CalendarList, and simlib3::CalendarQueue.
Referenced by simlib3::SQS::Get().
GetFirst()
virtual Entity * simlib3::Calendar::GetFirst () pure virtual
dequeue first
Implemented in simlib3::CalendarList, and simlib3::CalendarQueue.
Referenced by simlib3::SQS::GetFirst().
instance()
Calendar * simlib3::Calendar::instance () inline static
create/get single instance (singleton)
interface to singleton instance
Definition at line 1204 of file calendar.cc.
References _instance, simlib3::CalendarList::create(), and simlib3::CalendarQueue::create().
Referenced by simlib3::SQS::Clear(), simlib3::SQS::debug_print(), simlib3::SQS::Empty(), simlib3::SQS::Get(), simlib3::SQS::GetFirst(), and simlib3::SQS::ScheduleAt().
instance_exists()
static bool simlib3::Calendar::instance_exists () inline static
check if the instance exists
Definition at line 101 of file calendar.cc.
References _instance.
Referenced by simlib3::CalendarList::debug_print(), and simlib3::CalendarQueue::debug_print().
MinTime()
double simlib3::Calendar::MinTime () const inline
time of activation of first item
Definition at line 85 of file calendar.cc.
References mintime.
Referenced by simlib3::CalendarQueue::estimate_bucket_width(), simlib3::CalendarQueue::Get(), simlib3::CalendarQueue::GetFirst(), simlib3::CalendarList::ScheduleAt(), simlib3::CalendarQueue::ScheduleAt(), simlib3::CalendarQueue::switchtocq(), and simlib3::CalendarQueue::visualize().
Name()
virtual const char * simlib3::Calendar::Name () pure virtual
Implemented in simlib3::CalendarList, and simlib3::CalendarQueue.
ScheduleAt()
virtual void simlib3::Calendar::ScheduleAt (Entity * e, double t) pure virtual
enqueue
Implemented in simlib3::CalendarList, and simlib3::CalendarQueue.
Referenced by simlib3::SQS::ScheduleAt().
SetMinTime()
void simlib3::Calendar::SetMinTime (double t) inline protected
set cache for faster access
Definition at line 88 of file calendar.cc.
References mintime, and t.
Referenced by simlib3::CalendarList::CalendarList(), simlib3::CalendarQueue::CalendarQueue(), simlib3::CalendarList::clear(), simlib3::CalendarQueue::clear(), simlib3::CalendarList::Get(), simlib3::CalendarQueue::Get(), simlib3::CalendarList::GetFirst(), simlib3::CalendarQueue::GetFirst(), simlib3::CalendarList::ScheduleAt(), simlib3::CalendarQueue::ScheduleAt(), and simlib3::CalendarQueue::SearchMinTime().
Size()
unsigned simlib3::Calendar::Size () const inline
Definition at line 70 of file calendar.cc.
References _size.
Referenced by simlib3::SQS::debug_print(), simlib3::SQS::Get(), simlib3::SQS::GetFirst(), simlib3::SQS::ScheduleAt(), and simlib3::CalendarQueue::visualize().
Friends And Related Symbol Documentation
SetCalendar
void SetCalendar (const char * name) friend
choose calendar implementation default is list
Set calendar implementation.
Parameters
name String identification of calendar: "list", "cq"
Definition at line 1250 of file calendar.cc.
Member Data Documentation
_instance
Calendar * simlib3::Calendar::_instance = 0 static private
pointer to single instance
static pointer to singleton instance
Definition at line 109 of file calendar.cc.
Referenced by delete_instance(), instance(), and instance_exists().
_size
unsigned simlib3::Calendar::_size protected
number of scheduled items
Definition at line 93 of file calendar.cc.
Referenced by simlib3::CalendarList::clear(), simlib3::CalendarQueue::clear(), Empty(), simlib3::CalendarList::Get(), simlib3::CalendarQueue::Get(), simlib3::CalendarList::GetFirst(), simlib3::CalendarQueue::GetFirst(), simlib3::CalendarQueue::Resize(), simlib3::CalendarList::ScheduleAt(), simlib3::CalendarQueue::ScheduleAt(), Size(), and simlib3::CalendarQueue::switchtocq().
mintime
double simlib3::Calendar::mintime private
activation time of first event
Definition at line 95 of file calendar.cc.
Referenced by MinTime(), and SetMinTime().
The documentation for this class was generated from the following file:
src/calendar.cc