SIMLIB/C++: simlib3::FW Class Reference
simlib3::FW Class Reference
#include <ni_fw.h>
Public Member Functions
FW (const char *name)
virtual ~FW ()
virtual bool PrepareStep (void) override
prepare object for integration step
virtual void Integrate (void) override
Public Member Functions inherited from simlib3::SingleStepMethod
SingleStepMethod (const char *name)
virtual bool IsSingleStep (void) override
void SetStartMode (bool start_mode)
bool IsStartMode (void)
Public Member Functions inherited from simlib3::IntegrationMethod
IntegrationMethod (const char *name)
register method to list of methods and name it
virtual ~IntegrationMethod ()
destroy integration method (remove from list)
virtual bool IsSingleStep (void)=0
virtual void TurnOff (void)
turn off integration method: flush memories etc...
virtual void Integrate (void)=0
virtual bool PrepareStep (void)
prepare object for integration step
virtual void Resize (size_t size)
resize all the memories to the given size
Static Protected Attributes
static const double prec = DBL_EPSILON
Static Protected Attributes inherited from simlib3::IntegrationMethod
static bool IsEndStepEvent =false
Private Attributes
bool FW_First
Memory Y1
Memory ERR
Additional Inherited Members
Static Public Member Functions inherited from simlib3::IntegrationMethod
static void StepSim (void)
step of numerical integration method
static void IntegrationDone (void)
static void SetMethod (const char *name)
set method which will be used
static const char * GetMethod (void)
static void InitStep (double step_frag)
initialize step
static void FunCall (double step_frag)
static void SetOptStep (double opt_step)
static void SetStepSize (double step_size)
static bool IsConditionFlag (void)
static int GetErrNo (void)
static void SetErrNo (int num)
Protected Types inherited from simlib3::IntegrationMethod
typedef IntegratorContainer::iterator Iterator
Static Protected Member Functions inherited from simlib3::IntegrationMethod
static Iterator FirstIntegrator (void)
static Iterator LastIntegrator (void)
static bool StateCond (void)
check on changes of state conditions
static IntegrationMethod * SearchMethod (const char *name)
search method in the list of registrated methods
Detailed Description
Definition at line 22 of file ni_fw.h.
Constructor & Destructor Documentation
FW()
simlib3::FW::FW (const char * name) inline
Definition at line 29 of file ni_fw.h.
~FW()
virtual simlib3::FW::~FW () inline virtual
Definition at line 33 of file ni_fw.h.
Member Function Documentation
Integrate()
void simlib3::FW::Integrate (void) override virtual
Implements simlib3::IntegrationMethod.
Definition at line 38 of file ni_fw.cc.
References simlib3::_Print(), _SetTime, AccuracyError, Dprintf, ERR, simlib3::IntegrationMethod::FirstIntegrator(), FW_First, simlib3::IntegrationMethod::IsEndStepEvent, simlib3::IntegrationMethod::LastIntegrator(), simlib3::max(), simlib3::min(), simlib3::OptStep, prec, simlib3::SIMLIB_AbsoluteError, simlib3::SIMLIB_ConditionFlag, simlib3::SIMLIB_ContractStep, simlib3::SIMLIB_ContractStepFlag, simlib3::SIMLIB_DeltaTime, simlib3::SIMLIB_Dynamic(), simlib3::SIMLIB_ERRNO, simlib3::SIMLIB_MaxStep, simlib3::SIMLIB_MinStep, simlib3::SIMLIB_OptStep, simlib3::SIMLIB_RelativeError, simlib3::SIMLIB_StepSize, simlib3::SIMLIB_StepStartTime, simlib3::SIMLIB_warning(), simlib3::IntegrationMethod::StateCond(), simlib3::Time, and Y1.
PrepareStep()
bool simlib3::FW::PrepareStep (void) override virtual
prepare object for integration step
Reimplemented from simlib3::IntegrationMethod.
Definition at line 305 of file ni_fw.cc.
References Dprintf, FW_First, and simlib3::IntegrationMethod::PrepareStep().
Member Data Documentation
ERR
Memory simlib3::FW::ERR private
Definition at line 25 of file ni_fw.h.
Referenced by Integrate().
FW_First
bool simlib3::FW::FW_First private
Definition at line 24 of file ni_fw.h.
Referenced by Integrate(), and PrepareStep().
prec
const double simlib3::FW::prec = DBL_EPSILON static protected
Definition at line 27 of file ni_fw.h.
Referenced by Integrate().
Y1
Memory simlib3::FW::Y1 private
Definition at line 25 of file ni_fw.h.
Referenced by Integrate().
The documentation for this class was generated from the following files:
src/ni_fw.h
src/ni_fw.cc