SIMLIB/C++: simlib3::ZDelayTimer Class Reference
simlib3::ZDelayTimer Class Reference
#include <zdelay.h>
Classes
class ZDelayContainer
Public Member Functions
ZDelayTimer (double dt, bool is_default=false)
operator ZDelayTimer * ()
void Behavior () override
behavior description
void Init ()
void Start ()
void Stop ()
void Set (double new_dt)
~ZDelayTimer ()
Public Member Functions inherited from simlib3::Event
Event (Priority_t p=DEFAULT_PRIORITY)
constructor, default priority if not specified
virtual ~Event ()
destructor
virtual void Behavior ()=0
behavior description
virtual void Output () const override
print object to default output
virtual std::string Name () const override
name of object
virtual void Activate (double t) override
activate at time t (schedule)
void Activate ()
activate now
virtual void Activate (double t)
activate at time t (schedule)
Public Member Functions inherited from simlib3::Entity
unsigned long id () const
Entity (Priority_t p=DEFAULT_PRIORITY)
constructor
virtual ~Entity ()
destructor
operator Entity * ()
double ActivationTime ()
get activation time of entity - iff scheduled
it is here, because Entity has no knowledge of calendar activation record structure
void Activate ()
activate now
virtual void Activate (double t)
activate at time t (schedule)
virtual void Passivate ()
deactivation
virtual void Terminate ()=0
end Behavior() and remove entity
bool Idle ()
entity activation is not scheduled in calendar
void Cancel ()
end Behavior() and remove entity
virtual void Out () override
remove entity from queue
EventNotice * GetEventNotice ()
Public Member Functions inherited from simlib3::Link
Link ()
virtual ~Link ()
virtual void Into (List *l)
insert last
virtual void Out ()
remove from list
List * Where ()
where is linked
virtual bool isInQueue ()
present in queue
Public Member Functions inherited from simlib3::SimObject
bool TestAndSetFlag (bool new_value, unsigned n)
internal method for flag manipulation is used for algebraic loop checking in continuous blocks
SimObject ()
constructor
virtual ~SimObject ()
virtual destructor
void * operator new (size_t size)
allocate object, set _flags
void operator delete (void *ptr)
deallocate object
void * operator new[] (size_t size)=delete
void operator delete[] (void *ptr)=delete
bool isAllocated () const
virtual std::string Name () const
get object name
bool HasName () const
void SetName (const std::string &name)
assign the name
virtual void Output () const
print object to default output
Static Public Attributes
static const bool Default = true
Private Member Functions
ZDelayTimer (const ZDelayTimer &)
ZDelayTimer & operator= (const ZDelayTimer &)
void Register (ZDelay *)
void UnRegister (ZDelay *)
Private Attributes
double dt
ZDelayContainer * c
Friends
class ZDelay
Additional Inherited Members
Public Types inherited from simlib3::Entity
typedef EntityPriority_t Priority_t
Public Types inherited from simlib3::SimObject
enum _Flags { _CLEAR_ALL_FLAGS = 0 , _ALLOCATED_FLAG = 1<<0 , _EVAL_FLAG = 1<<1 , _HAS_NAME_FLAG = 1<<2 }
Public Attributes inherited from simlib3::Entity
Priority_t Priority
priority of the entity (scheduling,queues)
Protected Member Functions inherited from simlib3::Link
Link (Link *p, Link *s, List *h)
Protected Attributes inherited from simlib3::Entity
unsigned long _Ident
unique identification number of entity
double _MarkTime
union {
double _RemainingTime
unsigned long _RequiredCapacity
};
ServicePriority_t _SPrio
priority of service in Facility
Protected Attributes inherited from simlib3::SimObject
unsigned _flags
bool flags for internal use (TODO bitfield?)
Static Protected Attributes inherited from simlib3::Entity
static unsigned long _Number = 0L
current number of entities
Detailed Description
Definition at line 30 of file zdelay.h.
Constructor & Destructor Documentation
ZDelayTimer() [1/2]
simlib3::ZDelayTimer::ZDelayTimer (const ZDelayTimer &) private
ZDelayTimer() [2/2]
simlib3::ZDelayTimer::ZDelayTimer (double dt, bool is_default = false)
Definition at line 106 of file zdelay.cc.
References simlib3::ZDelay::default_clock, and simlib3::SIMLIB_ZDelayTimer::Register().
~ZDelayTimer()
simlib3::ZDelayTimer::~ZDelayTimer ()
Definition at line 116 of file zdelay.cc.
References simlib3::ZDelayTimer::ZDelayContainer::begin(), c, simlib3::ZDelayTimer::ZDelayContainer::clear(), simlib3::ZDelay::default_clock, simlib3::ZDelayTimer::ZDelayContainer::end(), and simlib3::SIMLIB_ZDelayTimer::UnRegister().
Member Function Documentation
Behavior()
void simlib3::ZDelayTimer::Behavior () override virtual
behavior description
Implements simlib3::Event.
Definition at line 159 of file zdelay.cc.
References simlib3::Event::Activate(), simlib3::ZDelayTimer::ZDelayContainer::begin(), c, dt, simlib3::ZDelayTimer::ZDelayContainer::end(), and simlib3::Time.
Init()
void simlib3::ZDelayTimer::Init ()
Definition at line 132 of file zdelay.cc.
References simlib3::ZDelayTimer::ZDelayContainer::begin(), c, simlib3::ZDelayTimer::ZDelayContainer::end(), and Start().
operator ZDelayTimer *()
simlib3::ZDelayTimer::operator ZDelayTimer * () inline
Definition at line 43 of file zdelay.h.
operator=()
ZDelayTimer & simlib3::ZDelayTimer::operator= (const ZDelayTimer &) private
Register()
void simlib3::ZDelayTimer::Register (ZDelay * p) private
Definition at line 172 of file zdelay.cc.
References c, simlib3::ZDelay::clock, and simlib3::ZDelayTimer::ZDelayContainer::insert().
Referenced by simlib3::ZDelay::ZDelay(), and simlib3::ZDelay::ZDelay().
Set()
void simlib3::ZDelayTimer::Set (double new_dt) inline
Definition at line 48 of file zdelay.h.
References dt.
Start()
void simlib3::ZDelayTimer::Start ()
Definition at line 143 of file zdelay.cc.
References simlib3::Event::Activate().
Referenced by Init().
Stop()
void simlib3::ZDelayTimer::Stop ()
Definition at line 151 of file zdelay.cc.
References simlib3::Entity::Passivate().
UnRegister()
void simlib3::ZDelayTimer::UnRegister (ZDelay * p) private
Definition at line 181 of file zdelay.cc.
References c, simlib3::ZDelay::clock, and simlib3::ZDelayTimer::ZDelayContainer::erase().
Referenced by simlib3::ZDelay::~ZDelay().
Friends And Related Symbol Documentation
ZDelay
friend class ZDelay friend
Definition at line 38 of file zdelay.h.
Member Data Documentation
c
ZDelayContainer* simlib3::ZDelayTimer::c private
Definition at line 35 of file zdelay.h.
Referenced by Behavior(), Init(), Register(), UnRegister(), and ~ZDelayTimer().
Default
const bool simlib3::ZDelayTimer::Default = true static
Definition at line 40 of file zdelay.h.
dt
double simlib3::ZDelayTimer::dt private
Definition at line 33 of file zdelay.h.
Referenced by Behavior(), and Set().
The documentation for this class was generated from the following files:
src/zdelay.h
src/zdelay.cc