SIMLIB/C++: simlib3::Input3D Class Reference
simlib3::Input3D Class Reference
SIMLIB/C++ 3D extension
Continuous block connection (transparent reference)
#include <simlib3D.h>
Public Member Functions
Input3D (const Input3D &inp)
Input3D (aContiBlock3D &cb)
Input3D (aContiBlock3D *cb)
Input3D & operator= (const Input3D &in)
Input3D Set (Input3D i)
Value3D Value ()
bool operator== (void *p)
Private Attributes
aContiBlock3D * bp
Detailed Description
Continuous block connection (transparent reference)
Definition at line 110 of file simlib3D.h.
Constructor & Destructor Documentation
Input3D() [1/3]
simlib3::Input3D::Input3D (const Input3D & inp) inline
Definition at line 113 of file simlib3D.h.
Input3D() [2/3]
simlib3::Input3D::Input3D (aContiBlock3D & cb) inline
Definition at line 114 of file simlib3D.h.
Input3D() [3/3]
simlib3::Input3D::Input3D (aContiBlock3D * cb) inline
Definition at line 115 of file simlib3D.h.
Member Function Documentation
operator=()
Input3D & simlib3::Input3D::operator= (const Input3D & in) inline
Definition at line 116 of file simlib3D.h.
References bp.
operator==()
bool simlib3::Input3D::operator== (void * p) inline
Definition at line 119 of file simlib3D.h.
References bp.
Set()
Input3D simlib3::Input3D::Set (Input3D i) inline
Definition at line 117 of file simlib3D.h.
References bp.
Referenced by simlib3::aContiBlock3D1::SetInput(), and simlib3::Integrator3D::SetInput().
Value()
Value3D simlib3::Input3D::Value () inline
Definition at line 118 of file simlib3D.h.
References bp, and simlib3::aContiBlock3D::Value().
Referenced by simlib3::aContiBlock3D2::Input1Value(), simlib3::aContiBlock3D2::Input2Value(), simlib3::aContiBlock3D3::Input3Value(), simlib3::aContiBlock3D1::InputValue(), simlib3::Integrator3D::operator=(), simlib3::_Abs3D::Value(), simlib3::_ScalarProduct3D::Value(), simlib3::_XYZpart::Value(), and simlib3::Integrator3D::special_input::Value().
Member Data Documentation
bp
aContiBlock3D* simlib3::Input3D::bp private
Definition at line 111 of file simlib3D.h.
Referenced by operator=(), operator==(), Set(), and Value().
The documentation for this class was generated from the following file:
src/simlib3D.h