SIMLIB/C++: simlib3::SQS Namespace Reference
simlib3::SQS Namespace Reference
Special namespace for calendar implementation.
Functions
void ScheduleAt (Entity *e, double t)
schedule entity e at given time t using scheduling priority from e
Entity * GetFirst ()
remove entity with minimum activation time
void Get (Entity *e)
remove selected entity activation record from calendar
bool Empty ()
empty calendar predicate
void Clear ()
remove all scheduled entities
int debug_print ()
Detailed Description
Special namespace for calendar implementation.
This is for internal use only.
Function Documentation
Clear()
void simlib3::SQS::Clear ()
remove all scheduled entities
Definition at line 1346 of file calendar.cc.
References _SetTime, simlib3::Calendar::clear(), simlib3::Calendar::instance(), and simlib3::NextTime.
Referenced by simlib3::Run(), and simlib3::SIMLIB_Init().
debug_print()
int simlib3::SQS::debug_print ()
Definition at line 1351 of file calendar.cc.
References simlib3::Calendar::debug_print(), simlib3::Calendar::instance(), and simlib3::Calendar::Size().
Empty()
bool simlib3::SQS::Empty ()
empty calendar predicate
Definition at line 1280 of file calendar.cc.
References simlib3::Calendar::Empty(), and simlib3::Calendar::instance().
Referenced by simlib3::Run().
Get()
void simlib3::SQS::Get (Entity * e)
remove selected entity activation record from calendar
Definition at line 1308 of file calendar.cc.
References _SetTime, simlib3::Calendar::Get(), simlib3::Calendar::instance(), simlib3::NextTime, and simlib3::Calendar::Size().
Referenced by simlib3::Process::_Run(), simlib3::Entity::Activate(), simlib3::Entity::Passivate(), simlib3::Process::Terminate(), simlib3::Event::Terminate(), simlib3::Entity::Terminate(), simlib3::Entity::~Entity(), and simlib3::Process::~Process().
GetFirst()
Entity * simlib3::SQS::GetFirst ()
remove entity with minimum activation time
Returns
pointer to entity
Definition at line 1327 of file calendar.cc.
References _SetTime, simlib3::Calendar::GetFirst(), simlib3::Calendar::instance(), simlib3::NextTime, and simlib3::Calendar::Size().
Referenced by simlib3::Run().
ScheduleAt()
void simlib3::SQS::ScheduleAt (Entity * e, double t)
schedule entity e at given time t using scheduling priority from e
Parameters
e entity
t time of activation
Definition at line 1287 of file calendar.cc.
References _SetTime, simlib3::Entity::Idle(), simlib3::Calendar::instance(), simlib3::NextTime, simlib3::Calendar::ScheduleAt(), simlib3::SIMLIB_error(), simlib3::Calendar::Size(), and t.
Referenced by simlib3::Entity::Activate().