SIMLIB/C++: simlib3 Namespace Reference
simlib3 Namespace Reference
Implementation of class CalendarList
interface is static - using global functions in SQS namespace.
Namespaces
namespace SQS
Special namespace for calendar implementation.
Classes
class _Abs2D
class _Abs3D
class _Add
block sum of two inputs
class _Add2D
class _Add3D
class _Div
divider block
class _Div2D
class _Div3D
class _FileWrap
class _Mul
multiplier block
class _Mul2D1D
class _Mul3D
class _Mul3D1D
class _Norm2D
class _Norm3D
class _ScalarProduct2D
class _ScalarProduct3D
class _Sub
block to subtract two inputs
class _Sub2D
class _Sub3D
class _Time
block wrapper for simulation time
class _UMinus
unary minus block
class _UMinus2D
class _UMinus3D
class _XYpart
class _XYZpart
class aBlock
abstract base class for all blocksblocks/SimObject have not copy semantics (TODO: add move semantics)
class ABM4
class aCondition
abstract base class for all state-condition blocks State event in combined model is executed at the time when the condition changes its boolean value
class aContiBlock
abstract base for continuous blocks with single output suitable for expression-tree building and evaluation
class aContiBlock1
base for continuous blocks with single input and algebraic loop check
class aContiBlock2
base for continuous blocks with two inputs
class aContiBlock2D
Abstract 2D block with single 2D output.
class aContiBlock2D1
continuous block with single input and alg.
class aContiBlock2D2
continuous block vith 2 inputs and alg.
class aContiBlock2D3
continuous block with 3 inputs and alg.
class aContiBlock3
base for continuous blocks vith three inputs and algebraic loop check
class aContiBlock3D
Abstract 3D block with single 3D output.
class aContiBlock3D1
continuous 3D block with single input
class aContiBlock3D2
continuous block vith 2 inputs and alg.
class aContiBlock3D3
continuous block with 3 inputs and alg.
class Adaptor2D
Convert 2 scalar inputs to single 2D vector output.
class Adaptor3D
Converts 3 scalar inputs to single 3D vector output.
class AlgLoop
abstract base for algebraic loop solvers
class AlgLoopDetector
class for algebraic loop detection AlgLoopDetector object should be used in Value() method only it checks for recursion in continuous block expression evaluation
User should remove algebraic loop manualy using special block (see AlgLoop solvers)
class Barrier
synchronization tool for processes
class Bisect
solve using bisection method
class Blash
nonlinear block - backlash
class Calendar
common interface for all calendar (PES) implementations
class CalendarList
class CalendarList — list implementation of calendar
class CalendarListImplementation
class CalendarListImplementation — sorted list
class CalendarQueue
CQ implementation of calendar.
class Condition
change detector - Boolean version (int)
class ConditionDown
detector of TRUE-->FALSE
class ConditionUp
detector of FALSE-->TRUE
class Constant
block: constant (value can not be changed)
class Constant2D
2D vector value that can't be changed
class Constant3D
3D vector value that can't be changed
class Delay
continuous signal delay block
class Entity
abstract base class for active entities (Process, Event) instances of derived classes provide Behavior() method implementation, execution can be scheduled in calendar
class EULER
class Event
abstract base class for events Event behavior is simple function (can not be interrupted)
struct EventNotice
activation record
class EventNoticeAllocator
allocate activation records fast
struct EventNoticeLinkBase
calendar item - PRIVATE for any implementation
we use double-linked circular list
struct Expression
reference to block expression This block can be used as handle for block expression trees
struct Expression2D
Reference to 2D vector block-expression.
struct Expression3D
3D vector block-expression handle
class Facility
(SOL-like) facility Facility with exclusive access and service priority
class Frict
nonlinear block: friction
class Function1
block parametrized by function with single argument
class Function2
block parametrized by function with two arguments
class FW
class Histogram
histogram statistics
class Hyst
nonlinear block - hysteresis
class Input
continuous block connection (transparent reference) wrapper for pointer to objects of aContiBlock derived classes
(small object, without virtual methods)
It is used for referencing of continuous blocks in block-expressions.
class Input2D
Continuous block connection (transparent reference)
class Input3D
Continuous block connection (transparent reference)
class Insv
nonlinear block: dead zone
class IntegrationMethod
IntegrationMethod - Abstract base class for integration methods.
class Integrator
block for numerical integration input is derivative, output is state
class Integrator2D
2D vector integrator
class Integrator3D
3D vector integrator
class IntegratorContainer
IntegratorContainer - internal container of integrators (singleton)
class Iterations
solve using iterations
class Lim
nonlinear block: limitation
class Link
base class for all double-linked list items
item can be at single place only (identified by where() method)
used for Queue implementation
class List
list of Link* items, uses data from Link
class MultiStepMethod
base for multi-step integration method
class NameDict
class Newton
solve using modified Newton's method
struct P_Context_t
internal structure for storing of process context
class Param
class Parameter
block: parameter (can not be changed during simulation run)
class Parameter2D
Special variable (can't be changed at simulation time)
class Parameter3D
Special variable (can't be changed at simulation time)
class ParameterVector
class Process
Abstract base class for all simulation processesProcess behavior is specified by Behavior method and can be interrupted during execution by e.g.
class Qntzr
nonlinear block: quantizer
class Queue
priority queue
class RegulaFalsi
solve using regula falsi method
class Relay
Relay this implementation detects exact time of switch.
class RKE
class RKF3
class RKF5
class RKF8
class Rline
nonlinear block: function defined by given table of values
class Sampler
objects of this class call global function periodically (typicaly used for output of continuous model)
class Semaphore
basic synchronization tool for processes simplified implementation
class SIMLIB_Delay
continuous delay block
class SIMLIB_DelayBuffer
memory for delayed pairs (Time,value)
class SIMLIB_module
Class for internal registration of modules.
struct SIMLIB_statistics_t
internal statistics structure
contains basic statistics of simulator execution
class SIMLIB_ZDelayTimer
class SimObject
Base class for almost all SIMLIB classes.
class SingleStepMethod
base for single-step integration methods
class Stat
class for statistical information gathering
class Status
State variables (memory) base for blocks with internal state (Relay, ...)
class StatusContainer
StatusContainer - internal container of status variables (singleton)
class StatusMethod
Abstract base class for integration methods with status auxiliary memories.
class Store
(SOL-like) store store capacity can be changed dynamically
class TStat
time dependent statistic
class Value2D
2D vector value
class Value3D
3D vector value
class Variable
block: variable (value can be changed)
class Variable2D
2D vector variable
class Variable3D
3D vector variable
class WaitUntilList
class ZDelay
class ZDelayTimer
Typedefs
typedef void(* SIMLIB_atexit_function_t) ()
typedef void(* VoidFunctionPtr) ()
typedef double(* opt_function_t) (const ParameterVector &p)
typedef long myint32
typedef signed char EntityPriority_t
Priority of the process/event.
typedef unsigned char ServicePriority_t
Service priority (see Facility::Seize)
typedef Hyst Hysteresis
typedef Blash Backlash
typedef Lim Limitation
typedef Insv DeadZone
typedef Qntzr Quantizer
typedef Frict Friction
Enumerations
enum SIMLIB_Phase_t {
START , INITIALIZATION , SIMULATION , TERMINATION ,
ERROREXIT
}
values indicate current phase of experiment
enum { LOWEST_PRIORITY = -127 , HIGHEST_PRIORITY = 127 , DEFAULT_PRIORITY = 0 }
entity/process priority values
(Warning: changed from 0..255 in SIMLIB v 3.03)
Functions
void SIMLIB_atexit (SIMLIB_atexit_function_t p)
static void SIMLIB_atexit_call ()
void SetCalendar (const char *name)
choose calendar implementation default is list
void SIMLIB_DoConditions ()
void SIMLIB_Dynamic ()
performs evaluation of integrators and status blocks
Input operator+ (Input a, Input b)
block operator +
Input operator- (Input a, Input b)
block operator -
Input operator* (Input a, Input b)
block operator *
Input operator/ (Input a, Input b)
block operator /
Input Sqr (Input x)
square function
Input operator- (Input a)
unary - block operator
void DebugON ()
start debugging output
void DebugOFF ()
stop debugging output
unsigned long Debug (unsigned long mode)
void SIMLIB_error (const enum _ErrEnum N)
print error message and abort program
void SIMLIB_error (const char *fmt,...)
print error message and abort program
void SIMLIB_error (const char *filename, const int linenum)
print error message and abort program
void SIMLIB_warning (const enum _ErrEnum N)
print warning message and continue
void SIMLIB_warning (const char *fmt,...)
print warning message and continue
const char * _ErrMsg (enum _ErrEnum N)
static double sign (double x)
Input Abs (Input x)
Input Sin (Input x)
Input Cos (Input x)
Input Tan (Input x)
Input ASin (Input x)
Input ACos (Input x)
Input ATan (Input x)
Input ATan2 (Input y, Input x)
Input Exp (Input x)
Input Log10 (Input x)
Input Ln (Input x)
Input Pow (Input x, Input y)
Input Sign (Input x)
Input Sqrt (Input x)
Input Min (Input x, Input y)
Input Max (Input x, Input y)
static unsigned * Alloc (unsigned n)
void SIMLIB_DoActions ()
void SIMLIB_ContinueInit ()
void SIMLIB_WUClear ()
double min (double a, double b)
double max (double a, double b)
std::string SIMLIB_create_tmp_name (const char *fmt,...)
printf-like function to create temporary name (the length of temporary names is limited)
used only for printing
void ContractStep ()
contract step of integration
void ContractStep (double time)
contract step of integration to end step time
void SetStep (double dtmin, double dtmax)
Set integration step interval.
void SetAccuracy (double abserr, double relerr)
set max.
void SetAccuracy (double relerr)
set max.
void SetName (SimObject &o, const std::string &name)
assign name to object
void SetName (SimObject *o, const std::string &name)
assign name to object
void RemoveName (SimObject &o)
remove name
void RemoveName (SimObject *o)
remove name
std::string GetName (SimObject &o)
get name of object
std::string GetName (SimObject *o)
get name of object
void SetErrNo (int num)
static double hooke_step (double *delta, opt_function_t f, ParameterVector &p, double min0)
double Optimize_hooke (opt_function_t f, ParameterVector &parameter, double rho, double epsilon, int itermax)
bool operator== (const ParameterVector &p1, const ParameterVector &p2)
bool accept_bad (double eps)
void move_to_next_point (ParameterVector &p, double eps)
double Optimize_simann (double(*f)(const ParameterVector &p), ParameterVector &p, int MAXT)
double Optimize_simann (opt_function_t f, ParameterVector &p, int MAXT)
double Optimize_gradient (opt_function_t f, ParameterVector &p, double MAXITER)
void SetOutput (const char *name)
redirects Output(), Print() to file
int _Print (const char *fmt,...)
output of messages to stdout, too
int Print (const char *fmt,...)
for Output methods, can be redirected
int Print (const double x)
output single value
int Print (const double x, const double y)
output 2 values
int Print (const double x, const double y, const double z)
output 3 values
void Error (const char *fmt,...)
print message and terminate program
static void THREAD_INTERRUPT_f () __attribute__((noinline))
static void FREE_CONTEXT () __attribute__((noinline))
non-inline function for deallocating saved process context
void RandomSeed (long seed)
initialize random number seed
double Random ()
base uniform generator (range 0-0.999999...) the default implementation is simple LCG 32bit
void SetBaseRandomGenerator (double(*new_gen)())
set another random generator default Random() implementation can be replaced
double SIMLIB_RandomBase ()
static double _gam (double AK)
double Uniform (double l, double h)
Uniform distribution generator.
double Normal (double mi, double sigma)
Gauss distribution generator.
double Weibul (double lambda, double alfa)
Weibul distribution generator.
double Erlang (double alfa, int beta)
Erlang distribution generator.
int NegBin (double q, int k)
double Gamma (double alfa, double beta)
Gamma distribution generator.
double Exponential (double mv)
Exponential distribution generator.
int NegBinM (double p, int m)
double Beta (double th, double fi, double min, double max)
Beta distribution generator.
double Triag (double mod, double min, double max)
double Logar (double mi, double delta)
double Rayle (double delta)
int Poisson (double lambda)
Poisson distribution generator.
int Geom (double q)
int HyperGeom (double p, int n, int m)
DEFINE_HOOK (Delay)
DEFINE_HOOK (DelayInit)
void SampleDelays ()
DEFINE_HOOK (ZDelayTimerInit)
DEFINE_HOOK (Break)
void InstallBreak (void(*f)())
InstallBreak — set function for checking if user breaks simulation.
DEFINE_HOOK (SamplerAct)
DEFINE_HOOK (SamplerInit)
DEFINE_HOOK (WUclear)
DEFINE_HOOK (WUget_next)
void Stop ()
stop current simulation run
void Abort ()
end simulation program
void SIMLIB_Init (double T0, double T1, unsigned version)
void Run ()
run simulation experiment
const char * SIMLIB_version_string ()
Get version of SIMLIB.
void Init (double t0, double t1=SIMLIB_MAXTIME)
Initialize simulator and model time.
void SetStep (double dt)
set fixed integration step
void Activate (Entity *e)
activate entity e
void Passivate (Entity *e)
passivate entity e
void SetMethod (const char *name)
select the integration method
const char * GetMethod (void)
get the name of the method which is used
void SetStarter (const char *name, const char *slave_name)
set the method which will be used to start given multistep method
void SetStarter (const char *slave_name)
set the method which will be used to start currently used multistep method
const char * GetStarter (const char *name)
get the name of the method which is used to start given multistep method
const char * GetStarter (void)
get the name of the method which is used to start currently used multistep method
double abs (const Value2D &a)
Value2D operator+ (const Value2D &a, const Value2D &b)
Value2D operator- (const Value2D &a, const Value2D &b)
Value2D operator- (const Value2D &a)
Value2D operator* (const Value2D &a, const double b)
Value2D operator* (const double a, const Value2D &b)
double scalar_product (const Value2D &a, const Value2D &b)
Value2D operator/ (const Value2D &a, const double b)
Input2D operator+ (Input2D a, Input2D b)
Input2D operator- (Input2D a, Input2D b)
Input2D operator* (Input2D a, Input b)
Input2D operator* (Input a, Input2D b)
Input2D operator/ (Input2D a, Input b)
Input2D operator- (Input2D a)
Input Abs (Input2D x)
absolute value of vector (1D block)
Input2D UnitVector (Input2D v)
make unit vector from input (Abs(output_vec)==1)
Input ScalarProduct (Input2D x, Input2D y)
dot product: xvec . yvec
Input Xpart (Input2D a)
get x part of (x,y) vector value
Input Ypart (Input2D a)
get y part of (x,y) vector value
void Print (Value2D a)
double abs (const Value3D &a)
Value3D operator+ (const Value3D &a, const Value3D &b)
Value3D operator- (const Value3D &a, const Value3D &b)
Value3D operator- (const Value3D &a)
Value3D operator* (const Value3D &a, const Value3D &b)
Value3D operator* (const Value3D &a, const double b)
Value3D operator* (const double a, const Value3D &b)
double scalar_product (const Value3D &a, const Value3D &b)
Value3D operator/ (const Value3D &a, const double b)
Input3D operator+ (Input3D a, Input3D b)
Input3D operator- (Input3D a, Input3D b)
Input3D operator* (Input3D a, Input3D b)
Input3D operator* (Input3D a, Input b)
Input3D operator* (Input a, Input3D b)
Input3D operator/ (Input3D a, Input b)
Input3D operator- (Input3D a)
Input Abs (Input3D x)
absolute value of vector (1D block)
Input3D UnitVector (Input3D x)
make unit vector from input (Abs(output_vec)==1)
Input ScalarProduct (Input3D x, Input3D y)
dot product: xvec . yvec
Input Xpart (Input3D a)
get x part of (x,y,z) vector value
Input Ypart (Input3D a)
get y part of (x,y,z) vector value
Input Zpart (Input3D a)
get z part of (x,y,z) vector value
void Print (Value3D a)
void WU_print ()
Variables
SIMLIB_IMPLEMENTATION
static const int MAX_ATEXIT = 10
static int counter = 0
static SIMLIB_atexit_function_t atexit_array [MAX_ATEXIT] = { 0, }
class simlib3::EventNoticeAllocator allocator
const unsigned LIST_MAX = 512
const unsigned MINBUCKETS = LIST_MAX>4?LIST_MAX:4
const unsigned LIST_MIN = LIST_MAX/2
const double COEF_PAR = 1.5
const double MUL_PAR = 1.0
bool SIMLIB_ConditionFlag = false
static class _Time _T
block – simulation time
aContiBlock & T = _T
simulation time block reference
unsigned long SIMLIB_debug_flag = 0UL
static unsigned long SIMLIB_Entity_Count = 0L
current number of entities in model
static const char _Errors []
const unsigned MAXHISTOCOUNT = 10000
static SIMLIB_module SIMLIB_module_id
Create single global registration object in each SIMLIB module.
const SIMLIB_Phase_t & Phase = SIMLIB_Phase
This variable contains the current phase of experiment (used for internal checking)
double SIMLIB_Time
bool SIMLIB_DynamicFlag = false
in dynamic section
bool SIMLIB_ResetStatus = false
flag set if there is a need for integration method restart
SIMLIB_Phase_t SIMLIB_Phase = START
Entity * SIMLIB_Current = NULL
int SIMLIB_ERRNO =0
bool SIMLIB_ContractStepFlag = false
requests shorter step
double SIMLIB_ContractStep = SIMLIB_MAXTIME
requested step size
double SIMLIB_StepStartTime
last step time
double SIMLIB_DeltaTime
Time-SIMLIB_StepStartTime.
double SIMLIB_OptStep
optimal step
double SIMLIB_MinStep =1e-10
minimal step
double SIMLIB_MaxStep =1
max. step
double SIMLIB_StepSize
actual step
double SIMLIB_AbsoluteError =0
absolute error
double SIMLIB_RelativeError =0.001
relative error
double SIMLIB_StartTime
double SIMLIB_NextTime
double SIMLIB_EndTime
const double & MinStep =SIMLIB_MinStep
minimal integration step
const double & MaxStep =SIMLIB_MaxStep
maximal integration step
const double & StepSize =SIMLIB_StepSize
actual integration step
const double & OptStep =SIMLIB_OptStep
optimal integration step
const double & AbsoluteError =SIMLIB_AbsoluteError
max. abs. error of integration
const double & RelativeError =SIMLIB_RelativeError
max. rel. error
Constant SIMLIB_Integrator_0input (0)
dummy input with zero value
const int abm_ord =4
ABM4 abm4 ("abm4", "rkf5")
Adams-Bashforth-Moulton, 4th order.
EULER euler ("euler")
Euler method.
FW fw ("fw")
Fowler-Warten (Warning: needs testing, do not use)
RKE rke ("rke")
Runge-Kutta-England, 4th order?
RKF3 rkf3 ("rkf3")
Runge-Kutta-Fehlberg, 3rd order.
RKF5 rkf5 ("rkf5")
Runge-Kutta-Fehlberg, 5th order.
RKF8 rkf8 ("rkf8")
Runge-Kutta-Fehlberg, 8th order.
static bool SimObject_allocated = false
static NameDict name_dict
class simlib3::_FileWrap OutFile
static jmp_buf P_DispatcherStatusBuffer
setjmp() state before dispatch
static char *volatile P_StackBase = 0
global start of stack area
static char *volatile P_StackBase2 = 0
for checking start of stack
static P_Context_t *volatile P_Context = 0
temporary global process state
static volatile size_t P_StackSize = 0
temporary global stack size
const myint32 INICONST = 1537L
const myint32 MULCONST = 1220703125L
const myint32 MAXLONGINT = 0x7FFFFFFFUL
const myint32 SIGNBIT = 0x80000000UL
static myint32 SIMLIB_RandomSeed = INICONST
static double(* SIMLIB_RandomBasePtr)() = SIMLIB_RandomBase
const double & StartTime = SIMLIB_StartTime
time of simulation start
const double & Time = SIMLIB_Time
model time (is NOT the block)
const double & NextTime = SIMLIB_NextTime
next-event time
const double & EndTime = SIMLIB_EndTime
time of simulation end
Entity *const & Current = SIMLIB_Current
pointer to active (now running) entity
unsigned long SIMLIB_experiment_no = 0
static SIMLIB_statistics_t SIMLIB_run_statistics
const SIMLIB_statistics_t & SIMLIB_statistics = SIMLIB_run_statistics
interface to internal run-time statistics structure
static bool StopFlag = false
const unsigned SIMLIB_version = __SIMLIB__
library version
const double SIMLIB_MINTIME = 0.0
minimal time value
const double SIMLIB_MAXTIME = 1.0e30
maximum time (1e30 works for float, too)
static Constant2D Zero2D (0, 0)
static Constant3D Zero3D (0, 0, 0)
static bool flag = false
Detailed Description
Implementation of class CalendarList
interface is static - using global functions in SQS namespace.
Main SIMLIB (version 3+) namespace.
uses double-linked list and dynamic calendar queue [brown1988]
Usage: using namespace simlib3;
Typedef Documentation
Backlash
typedef Blash simlib3::Backlash
Definition at line 1396 of file simlib.h.
DeadZone
typedef Insv simlib3::DeadZone
Definition at line 1584 of file simlib.h.
EntityPriority_t
typedef signed char simlib3::EntityPriority_t
Priority of the process/event.
Definition at line 363 of file simlib.h.
Friction
typedef Frict simlib3::Friction
Definition at line 1617 of file simlib.h.
Hysteresis
typedef Hyst simlib3::Hysteresis
Definition at line 1380 of file simlib.h.
Limitation
typedef Lim simlib3::Limitation
Definition at line 1567 of file simlib.h.
myint32
typedef long simlib3::myint32
Definition at line 39 of file random1.cc.
opt_function_t
typedef double(* simlib3::opt_function_t) (const ParameterVector &p)
Definition at line 83 of file optimize.h.
Quantizer
typedef Qntzr simlib3::Quantizer
Definition at line 1600 of file simlib.h.
ServicePriority_t
typedef unsigned char simlib3::ServicePriority_t
Service priority (see Facility::Seize)
Definition at line 365 of file simlib.h.
SIMLIB_atexit_function_t
typedef void(* simlib3::SIMLIB_atexit_function_t) ()
Definition at line 150 of file internal.h.
VoidFunctionPtr
typedef void(* simlib3::VoidFunctionPtr) ()
Definition at line 177 of file internal.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
entity/process priority values
(Warning: changed from 0..255 in SIMLIB v 3.03)
Enumerator
LOWEST_PRIORITY
HIGHEST_PRIORITY
DEFAULT_PRIORITY
Definition at line 357 of file simlib.h.
SIMLIB_Phase_t
enum simlib3::SIMLIB_Phase_t
values indicate current phase of experiment
Enumerator
START
INITIALIZATION
SIMULATION
TERMINATION
ERROREXIT
Definition at line 76 of file internal.h.
Function Documentation
_ErrMsg()
const char * simlib3::_ErrMsg (enum _ErrEnum N)
Definition at line 97 of file errors.cc.
References _Errors.
Referenced by SIMLIB_error(), SIMLIB_error(), and SIMLIB_warning().
_gam()
static double simlib3::_gam (double AK) static
Definition at line 35 of file random2.cc.
References Random().
Referenced by Beta(), and Gamma().
_Print()
int simlib3::_Print (const char * fmt, ...)
output of messages to stdout, too
Parameters
fmt format string (the same as for printf())
Definition at line 68 of file print.cc.
References OutFile.
Referenced by Error(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), SIMLIB_error(), SIMLIB_error(), SIMLIB_error(), SIMLIB_warning(), and SIMLIB_warning().
Abort()
void simlib3::Abort ()
end simulation program
Definition at line 159 of file run.cc.
References Dprintf, ERROREXIT, and SIMLIB_Phase.
abs() [1/2]
double simlib3::abs (const Value2D & a)
Definition at line 38 of file simlib2D.cc.
Referenced by simlib3::_Abs2D::Value(), simlib3::_Norm2D::Value(), simlib3::_Abs3D::Value(), and simlib3::_Norm3D::Value().
abs() [2/2]
double simlib3::abs (const Value3D & a)
Definition at line 38 of file simlib3D.cc.
Abs() [1/3]
Input simlib3::Abs (Input x)
Definition at line 94 of file fun.cc.
Abs() [2/3]
Input simlib3::Abs (Input2D x)
absolute value of vector (1D block)
Definition at line 387 of file simlib2D.cc.
Abs() [3/3]
Input simlib3::Abs (Input3D x)
absolute value of vector (1D block)
Definition at line 406 of file simlib3D.cc.
accept_bad()
bool simlib3::accept_bad (double eps)
Definition at line 30 of file opt-simann.cc.
References Random().
Referenced by Optimize_simann().
ACos()
Input simlib3::ACos (Input x)
Definition at line 101 of file fun.cc.
Activate()
void simlib3::Activate (Entity * e) inline
activate entity e
Definition at line 431 of file simlib.h.
References simlib3::Entity::Activate().
Referenced by main().
Alloc()
static unsigned * simlib3::Alloc (unsigned n) static
Definition at line 35 of file histo.cc.
Referenced by simlib3::Histogram::Histogram(), simlib3::Histogram::Histogram(), simlib3::Histogram::Histogram(), and simlib3::Histogram::Init().
ASin()
Input simlib3::ASin (Input x)
Definition at line 100 of file fun.cc.
ATan()
Input simlib3::ATan (Input x)
Definition at line 102 of file fun.cc.
ATan2()
Input simlib3::ATan2 (Input y, Input x)
Definition at line 103 of file fun.cc.
Beta()
double simlib3::Beta (double th, double fi, double min, double max)
Beta distribution generator.
Parameters
th
param fi
Parameters
min
param max
Definition at line 181 of file random2.cc.
References _gam(), max(), and min().
ContractStep() [1/2]
void simlib3::ContractStep ()
contract step of integration
request for shorter step of num. integ.
Definition at line 64 of file intg.cc.
References SIMLIB_ContractStepFlag.
Referenced by simlib3::Relay::Eval(), and simlib3::Condition::Test().
ContractStep() [2/2]
void simlib3::ContractStep (double time)
contract step of integration to end step time
request for step end (at most) at given time
Parameters
time expected end of step time
Definition at line 72 of file intg.cc.
References SIMLIB_ContractStep, SIMLIB_ContractStepFlag, SIMLIB_MinStep, and SIMLIB_StepStartTime.
Cos()
Input simlib3::Cos (Input x)
Definition at line 97 of file fun.cc.
Debug()
unsigned long simlib3::Debug (unsigned long mode)
Definition at line 48 of file debug.cc.
References NoDebugErr, SIMLIB_debug_flag, and SIMLIB_warning().
Referenced by DebugOFF(), and DebugON().
DebugOFF()
void simlib3::DebugOFF ()
stop debugging output
Definition at line 42 of file debug.cc.
References Debug().
DebugON()
void simlib3::DebugON ()
start debugging output
Definition at line 36 of file debug.cc.
References Debug().
DEFINE_HOOK() [1/8]
simlib3::DEFINE_HOOK (Break)
DEFINE_HOOK() [2/8]
simlib3::DEFINE_HOOK (Delay)
DEFINE_HOOK() [3/8]
simlib3::DEFINE_HOOK (DelayInit)
DEFINE_HOOK() [4/8]
simlib3::DEFINE_HOOK (SamplerAct)
DEFINE_HOOK() [5/8]
simlib3::DEFINE_HOOK (SamplerInit)
DEFINE_HOOK() [6/8]
simlib3::DEFINE_HOOK (WUclear)
DEFINE_HOOK() [7/8]
simlib3::DEFINE_HOOK (WUget_next)
DEFINE_HOOK() [8/8]
simlib3::DEFINE_HOOK (ZDelayTimerInit)
Erlang()
double simlib3::Erlang (double alfa, int beta)
Erlang distribution generator.
Parameters
alfa
param beta
Definition at line 109 of file random2.cc.
References ErlangError, Random(), and SIMLIB_error().
Error()
void simlib3::Error (const char * fmt, ...)
print message and terminate program
Definition at line 123 of file print.cc.
References _Print(), OutFile, SIMLIB_error(), and UserError.
Referenced by simlib3::Barrier::ChangeHeight(), and simlib3::Barrier::Init().
Exp()
Input simlib3::Exp (Input x)
Definition at line 105 of file fun.cc.
Exponential()
double simlib3::Exponential (double mv)
Exponential distribution generator.
Parameters
mv mean value
Definition at line 152 of file random2.cc.
References Random().
FREE_CONTEXT()
static void simlib3::FREE_CONTEXT () static
non-inline function for deallocating saved process context
Definition at line 241 of file process.cc.
References P_Context.
Referenced by THREAD_INTERRUPT_f().
Gamma()
double simlib3::Gamma (double alfa, double beta)
Gamma distribution generator.
Parameters
alfa
param beta
Definition at line 141 of file random2.cc.
References _gam().
Geom()
int simlib3::Geom (double q)
Definition at line 257 of file random2.cc.
References GeomError, Random(), and SIMLIB_error().
GetName() [1/2]
std::string simlib3::GetName (SimObject & o)
get name of object
Definition at line 66 of file name.cc.
References simlib3::SimObject::Name().
GetName() [2/2]
std::string simlib3::GetName (SimObject * o)
get name of object
Definition at line 72 of file name.cc.
References simlib3::SimObject::Name().
hooke_step()
static double simlib3::hooke_step (double * delta, opt_function_t f, ParameterVector & p, double min0) static
Definition at line 29 of file opt-hooke.cc.
References simlib3::ParameterVector::size().
Referenced by Optimize_hooke().
HyperGeom()
int simlib3::HyperGeom (double p, int n, int m)
Definition at line 270 of file random2.cc.
References HyperGeomError1, HyperGeomError2, Random(), and SIMLIB_error().
Init()
void simlib3::Init (double t0, double t1 = SIMLIB_MAXTIME) inline
Initialize simulator and model time.
Parameters
t0 simulation start time
t1 simulation end time
Definition at line 181 of file simlib.h.
References __SIMLIB__, and SIMLIB_Init().
Referenced by main().
Ln()
Input simlib3::Ln (Input x)
Definition at line 107 of file fun.cc.
Log10()
Input simlib3::Log10 (Input x)
Definition at line 106 of file fun.cc.
Logar()
double simlib3::Logar (double mi, double delta)
Definition at line 210 of file random2.cc.
References Normal().
max()
double simlib3::max (double a, double b) inline
Definition at line 286 of file internal.h.
Referenced by Beta(), simlib3::Hyst::Eval(), simlib3::Blash::Eval(), simlib3::IntegrationMethod::InitStep(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Iterate(), Max(), and Triag().
Max()
Input simlib3::Max (Input x, Input y)
Definition at line 115 of file fun.cc.
References max().
min()
double simlib3::min (double a, double b) inline
Definition at line 285 of file internal.h.
Referenced by Beta(), simlib3::Hyst::Eval(), simlib3::Blash::Eval(), simlib3::IntegrationMethod::InitStep(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), Min(), and Triag().
Min()
Input simlib3::Min (Input x, Input y)
Definition at line 114 of file fun.cc.
References min().
move_to_next_point()
void simlib3::move_to_next_point (ParameterVector & p, double eps)
Definition at line 39 of file opt-simann.cc.
References Random(), and simlib3::ParameterVector::size().
Referenced by Optimize_simann().
NegBin()
int simlib3::NegBin (double q, int k)
Definition at line 121 of file random2.cc.
References NegBinError, Random(), and SIMLIB_error().
NegBinM()
int simlib3::NegBinM (double p, int m)
Definition at line 164 of file random2.cc.
References NegBinMError1, NegBinMError2, Random(), and SIMLIB_error().
Normal()
double simlib3::Normal (double mi, double sigma)
Gauss distribution generator.
Parameters
mi mean value
sigma std. deviation
Definition at line 82 of file random2.cc.
References Random().
Referenced by Logar(), and Poisson().
operator*() [1/11]
Value2D simlib3::operator* (const double a, const Value2D & b)
Definition at line 73 of file simlib2D.cc.
operator*() [2/11]
Value3D simlib3::operator* (const double a, const Value3D & b)
Definition at line 71 of file simlib3D.cc.
operator*() [3/11]
Value2D simlib3::operator* (const Value2D & a, const double b)
Definition at line 68 of file simlib2D.cc.
operator*() [4/11]
Value3D simlib3::operator* (const Value3D & a, const double b)
Definition at line 66 of file simlib3D.cc.
operator*() [5/11]
Value3D simlib3::operator* (const Value3D & a, const Value3D & b)
Definition at line 58 of file simlib3D.cc.
operator*() [6/11]
Input simlib3::operator* (Input a, Input b)
block operator *
Definition at line 228 of file continuous.cc.
operator*() [7/11]
Input2D simlib3::operator* (Input a, Input2D b)
Definition at line 313 of file simlib2D.cc.
operator*() [8/11]
Input3D simlib3::operator* (Input a, Input3D b)
Definition at line 332 of file simlib3D.cc.
operator*() [9/11]
Input2D simlib3::operator* (Input2D a, Input b)
Definition at line 312 of file simlib2D.cc.
operator*() [10/11]
Input3D simlib3::operator* (Input3D a, Input b)
Definition at line 331 of file simlib3D.cc.
operator*() [11/11]
Input3D simlib3::operator* (Input3D a, Input3D b)
Definition at line 330 of file simlib3D.cc.
operator+() [1/5]
Value2D simlib3::operator+ (const Value2D & a, const Value2D & b)
Definition at line 43 of file simlib2D.cc.
operator+() [2/5]
Value3D simlib3::operator+ (const Value3D & a, const Value3D & b)
Definition at line 43 of file simlib3D.cc.
operator+() [3/5]
Input simlib3::operator+ (Input a, Input b)
block operator +
Definition at line 224 of file continuous.cc.
operator+() [4/5]
Input2D simlib3::operator+ (Input2D a, Input2D b)
Definition at line 310 of file simlib2D.cc.
operator+() [5/5]
Input3D simlib3::operator+ (Input3D a, Input3D b)
Definition at line 328 of file simlib3D.cc.
operator-() [1/10]
Value2D simlib3::operator- (const Value2D & a)
Definition at line 53 of file simlib2D.cc.
operator-() [2/10]
Value2D simlib3::operator- (const Value2D & a, const Value2D & b)
Definition at line 48 of file simlib2D.cc.
operator-() [3/10]
Value3D simlib3::operator- (const Value3D & a)
Definition at line 53 of file simlib3D.cc.
operator-() [4/10]
Value3D simlib3::operator- (const Value3D & a, const Value3D & b)
Definition at line 48 of file simlib3D.cc.
operator-() [5/10]
Input simlib3::operator- (Input a)
unary - block operator
Definition at line 262 of file continuous.cc.
operator-() [6/10]
Input simlib3::operator- (Input a, Input b)
block operator -
Definition at line 226 of file continuous.cc.
operator-() [7/10]
Input2D simlib3::operator- (Input2D a)
Definition at line 334 of file simlib2D.cc.
operator-() [8/10]
Input2D simlib3::operator- (Input2D a, Input2D b)
Definition at line 311 of file simlib2D.cc.
operator-() [9/10]
Input3D simlib3::operator- (Input3D a)
Definition at line 353 of file simlib3D.cc.
operator-() [10/10]
Input3D simlib3::operator- (Input3D a, Input3D b)
Definition at line 329 of file simlib3D.cc.
operator/() [1/5]
Value2D simlib3::operator/ (const Value2D & a, const double b)
Definition at line 83 of file simlib2D.cc.
operator/() [2/5]
Value3D simlib3::operator/ (const Value3D & a, const double b)
Definition at line 81 of file simlib3D.cc.
operator/() [3/5]
Input simlib3::operator/ (Input a, Input b)
block operator /
Definition at line 230 of file continuous.cc.
operator/() [4/5]
Input2D simlib3::operator/ (Input2D a, Input b)
Definition at line 314 of file simlib2D.cc.
operator/() [5/5]
Input3D simlib3::operator/ (Input3D a, Input b)
Definition at line 333 of file simlib3D.cc.
operator==()
bool simlib3::operator== (const ParameterVector & p1, const ParameterVector & p2)
Definition at line 86 of file opt-param.cc.
Optimize_gradient()
double simlib3::Optimize_gradient (opt_function_t f, ParameterVector & p, double MAXITER)
Optimize_hooke()
double simlib3::Optimize_hooke (opt_function_t f, ParameterVector & parameter, double rho, double epsilon, int itermax)
Definition at line 57 of file opt-hooke.cc.
References hooke_step(), Print(), simlib3::ParameterVector::PrintValues(), and simlib3::ParameterVector::size().
Optimize_simann() [1/2]
double simlib3::Optimize_simann (double(*)(const ParameterVector &p) f, ParameterVector & p, int MAXT)
Definition at line 52 of file opt-simann.cc.
References accept_bad(), move_to_next_point(), and Print().
Optimize_simann() [2/2]
double simlib3::Optimize_simann (opt_function_t f, ParameterVector & p, int MAXT)
Passivate()
void simlib3::Passivate (Entity * e) inline
passivate entity e
Definition at line 432 of file simlib.h.
References simlib3::Entity::Passivate().
Referenced by simlib3::Semaphore::P().
Poisson()
int simlib3::Poisson (double lambda)
Poisson distribution generator.
Parameters
lambda
Definition at line 229 of file random2.cc.
References Normal(), PoissonError, Random(), and SIMLIB_error().
Pow()
Input simlib3::Pow (Input x, Input y)
Definition at line 108 of file fun.cc.
Print() [1/6]
int simlib3::Print (const char * fmt, ...)
for Output methods, can be redirected
Definition at line 92 of file print.cc.
References OutFile.
Referenced by simlib3::CalendarListImplementation::debug_print(), simlib3::CalendarList::debug_print(), simlib3::CalendarQueue::debug_print(), main(), Optimize_hooke(), Optimize_simann(), simlib3::SimObject::Output(), simlib3::SIMLIB_statistics_t::Output(), simlib3::Process::Output(), simlib3::Event::Output(), simlib3::Sampler::Output(), simlib3::Stat::Output(), simlib3::TStat::Output(), simlib3::List::Output(), simlib3::Queue::Output(), simlib3::Histogram::Output(), simlib3::Facility::Output(), simlib3::Store::Output(), simlib3::Semaphore::Output(), simlib3::Barrier::Output(), Print(), Print(), Print(), Sample(), and simlib3::CalendarQueue::visualize().
Print() [2/6]
int simlib3::Print (const double x)
output single value
Parameters
x value to print
Definition at line 105 of file print.cc.
References Print().
Print() [3/6]
int simlib3::Print (const double x, const double y)
output 2 values
Parameters
x value to print
y value to print
Definition at line 110 of file print.cc.
References Print().
Print() [4/6]
int simlib3::Print (const double x, const double y, const double z)
output 3 values
Parameters
x value to print
y value to print
z value to print
Definition at line 115 of file print.cc.
References Print().
Print() [5/6]
void simlib3::Print (Value2D a) inline
Definition at line 237 of file simlib2D.h.
References simlib3::Value2D::Print().
Print() [6/6]
void simlib3::Print (Value3D a) inline
Definition at line 245 of file simlib3D.h.
References simlib3::Value3D::Print().
Random()
double simlib3::Random ()
base uniform generator (range 0-0.999999...) the default implementation is simple LCG 32bit
Definition at line 95 of file random1.cc.
References SIMLIB_RandomBasePtr.
Referenced by _gam(), accept_bad(), Erlang(), Exponential(), Geom(), HyperGeom(), move_to_next_point(), NegBin(), NegBinM(), Normal(), Poisson(), Rayle(), Triag(), Uniform(), and Weibul().
RandomSeed()
void simlib3::RandomSeed (long seed)
initialize random number seed
Parameters
seed initial value of generator state
Definition at line 64 of file random1.cc.
References SIMLIB_RandomSeed.
Rayle()
double simlib3::Rayle (double delta)
Definition at line 219 of file random2.cc.
References Random().
RemoveName() [1/2]
void simlib3::RemoveName (SimObject & o)
remove name
Definition at line 54 of file name.cc.
References simlib3::SimObject::SetName().
RemoveName() [2/2]
void simlib3::RemoveName (SimObject * o)
remove name
Definition at line 60 of file name.cc.
References simlib3::SimObject::SetName().
Run()
void simlib3::Run ()
run simulation experiment
Definition at line 228 of file run.cc.
References _SetTime, CALL_HOOK, simlib3::SQS::Clear(), Dprintf, simlib3::SQS::Empty(), EndTime, simlib3::SIMLIB_statistics_t::EndTime, simlib3::SIMLIB_statistics_t::EventCount, simlib3::SQS::GetFirst(), simlib3::SIMLIB_statistics_t::Init(), INITIALIZATION, simlib3::IntegrationMethod::IntegrationDone(), simlib3::IntegratorContainer::isAny(), simlib3::StatusContainer::isAny(), simlib3::SIMLIB_statistics_t::MaxStep, simlib3::SIMLIB_statistics_t::MinStep, NextTime, RunUseError, SIMLIB_ContinueInit(), SIMLIB_Current, SIMLIB_DoActions(), SIMLIB_DoConditions(), SIMLIB_error(), SIMLIB_internal_error, SIMLIB_Phase, SIMLIB_ResetStatus, SIMLIB_run_statistics, SIMULATION, StartTime, simlib3::SIMLIB_statistics_t::StartTime, simlib3::SIMLIB_statistics_t::StepCount, simlib3::IntegrationMethod::StepSim(), StepSize, StopFlag, TERMINATION, and Time.
Referenced by main().
SampleDelays()
void simlib3::SampleDelays ()
Definition at line 92 of file run.cc.
References CALL_HOOK.
Referenced by SIMLIB_DoConditions().
scalar_product() [1/2]
double simlib3::scalar_product (const Value2D & a, const Value2D & b)
Definition at line 78 of file simlib2D.cc.
Referenced by simlib3::_ScalarProduct2D::Value(), and simlib3::_ScalarProduct3D::Value().
scalar_product() [2/2]
double simlib3::scalar_product (const Value3D & a, const Value3D & b)
Definition at line 76 of file simlib3D.cc.
ScalarProduct() [1/2]
Input simlib3::ScalarProduct (Input2D x, Input2D y)
dot product: xvec . yvec
Definition at line 389 of file simlib2D.cc.
ScalarProduct() [2/2]
Input simlib3::ScalarProduct (Input3D x, Input3D y)
dot product: xvec . yvec
Definition at line 408 of file simlib3D.cc.
SetAccuracy() [1/2]
void simlib3::SetAccuracy (double abserr, double relerr)
set max.
error estimate for numerical integration method used for adaptive stepsize control
Parameters
abserr absolute tolerance
relerr tolerance relative to integrator value
Definition at line 106 of file intg.cc.
References Dprintf, SetAccuracyError, SIMLIB_AbsoluteError, SIMLIB_error(), and SIMLIB_RelativeError.
Referenced by main(), and SetAccuracy().
SetAccuracy() [2/2]
void simlib3::SetAccuracy (double relerr)
set max.
relative error estimate for numerical integration method
Parameters
relerr tolerance relative to integrator value
Definition at line 116 of file intg.cc.
References SetAccuracy().
SetBaseRandomGenerator()
void simlib3::SetBaseRandomGenerator (double(*)() new_gen)
set another random generator default Random() implementation can be replaced
Parameters
new_gen pointer to user-defined function
Definition at line 103 of file random1.cc.
References SIMLIB_RandomBase(), and SIMLIB_RandomBasePtr.
SetCalendar()
void simlib3::SetCalendar (const char * name)
choose calendar implementation default is list
Set calendar implementation.
Parameters
name String identification of calendar: "list", "cq"
Definition at line 1250 of file calendar.cc.
SetErrNo()
void simlib3::SetErrNo (int num)
Definition at line 327 of file numint.cc.
References SIMLIB_ERRNO.
SetName() [1/2]
void simlib3::SetName (SimObject & o, const std::string & name)
assign name to object
Definition at line 42 of file name.cc.
References simlib3::SimObject::SetName().
Referenced by simlib3::List::List(), and simlib3::Queue::Queue().
SetName() [2/2]
void simlib3::SetName (SimObject * o, const std::string & name)
assign name to object
Definition at line 48 of file name.cc.
References simlib3::SimObject::SetName().
SetOutput()
void simlib3::SetOutput (const char * name)
redirects Output(), Print() to file
Parameters
name name of output file
Definition at line 50 of file print.cc.
References OutFile.
SetStep() [1/2]
void simlib3::SetStep (double dt) inline
set fixed integration step
Parameters
dt (almost) fixed step size
Definition at line 196 of file simlib.h.
References SetStep().
SetStep() [2/2]
void simlib3::SetStep (double dtmin, double dtmax)
Set integration step interval.
Parameters
dtmin min. step size
dtmax max. step size (can be slightly increased)
Definition at line 92 of file intg.cc.
References Dprintf, SetStepError, SIMLIB_error(), SIMLIB_MaxStep, and SIMLIB_MinStep.
Referenced by main(), and SetStep().
sign()
static double simlib3::sign (double x) static
Definition at line 78 of file fun.cc.
Referenced by Sign().
Sign()
Input simlib3::Sign (Input x)
Definition at line 110 of file fun.cc.
References sign().
SIMLIB_atexit()
void simlib3::SIMLIB_atexit (SIMLIB_atexit_function_t p)
Definition at line 26 of file atexit.cc.
References atexit_array, DBG_ATEXIT, DEBUG, MAX_ATEXIT, and SIMLIB_internal_error.
Referenced by simlib3::CalendarList::create(), simlib3::CalendarQueue::create(), and simlib3::WaitUntilList::create().
SIMLIB_atexit_call()
static void simlib3::SIMLIB_atexit_call () static
Definition at line 39 of file atexit.cc.
References atexit_array, DBG_ATEXIT, DEBUG, and MAX_ATEXIT.
Referenced by simlib3::SIMLIB_module::~SIMLIB_module().
SIMLIB_ContinueInit()
void simlib3::SIMLIB_ContinueInit ()
Definition at line 125 of file intg.cc.
References simlib3::IntegratorContainer::InitAll(), simlib3::StatusContainer::InitAll(), simlib3::aCondition::InitAll(), simlib3::aCondition::isAny(), simlib3::IntegratorContainer::isAny(), simlib3::StatusContainer::isAny(), simlib3::aCondition::SetAll(), SIMLIB_DeltaTime, SIMLIB_Dynamic(), SIMLIB_DynamicFlag, SIMLIB_MaxStep, SIMLIB_OptStep, SIMLIB_StepStartTime, SIMLIB_Time, and simlib3::aCondition::TestAll().
Referenced by Run(), and SIMLIB_Init().
SIMLIB_create_tmp_name()
std::string simlib3::SIMLIB_create_tmp_name (const char * fmt, ...)
printf-like function to create temporary name (the length of temporary names is limited)
used only for printing
Definition at line 80 of file name.cc.
Referenced by simlib3::Process::Name(), and simlib3::Event::Name().
SIMLIB_DoActions()
void simlib3::SIMLIB_DoActions ()
Definition at line 135 of file run.cc.
Referenced by Run().
SIMLIB_DoConditions()
void simlib3::SIMLIB_DoConditions ()
Definition at line 139 of file cond.cc.
References simlib3::aCondition::AllActions(), SampleDelays(), simlib3::aCondition::SetAll(), SIMLIB_ConditionFlag, and SIMLIB_ResetStatus.
Referenced by Run().
SIMLIB_Dynamic()
void simlib3::SIMLIB_Dynamic ()
performs evaluation of integrators and status blocks
Definition at line 35 of file continuous.cc.
References simlib3::StatusContainer::ClearAllValueOK(), simlib3::IntegratorContainer::EvaluateAll(), and simlib3::StatusContainer::EvaluateAll().
Referenced by simlib3::IntegrationMethod::FunCall(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Iterate(), simlib3::IntegrationMethod::Prepare(), and SIMLIB_ContinueInit().
SIMLIB_error() [1/3]
void simlib3::SIMLIB_error (const char * filename, const int linenum)
print error message and abort program
print internal error messages
Definition at line 61 of file error.cc.
References _ABORT_TXT, _ErrMsg(), _INT_ERR_TXT, _Print(), ERROREXIT, InternalError, SIMLIB_DynamicFlag, SIMLIB_Phase, and Time.
SIMLIB_error() [2/3]
void simlib3::SIMLIB_error (const char * fmt, ...)
print error message and abort program
print formatted error messages
Definition at line 48 of file error.cc.
References _ABORT_TXT, _ERR_TXT, _Print(), and Time.
SIMLIB_error() [3/3]
void simlib3::SIMLIB_error (const enum _ErrEnum N)
print error message and abort program
print specific error messages
Definition at line 38 of file error.cc.
References _ABORT_TXT, _ERR_TXT, _ErrMsg(), _Print(), ERROREXIT, SIMLIB_DynamicFlag, SIMLIB_Phase, and Time.
Referenced by simlib3::aContiBlock::_Eval(), simlib3::aContiBlock2D::_Eval(), simlib3::aContiBlock3D::_Eval(), simlib3::Process::_Run(), simlib3::aContiBlock1::aContiBlock1(), simlib3::aContiBlock2::aContiBlock2(), simlib3::aContiBlock2D1::aContiBlock2D1(), simlib3::aContiBlock2D2::aContiBlock2D2(), simlib3::aContiBlock2D3::aContiBlock2D3(), simlib3::aContiBlock3::aContiBlock3(), simlib3::aContiBlock3D1::aContiBlock3D1(), simlib3::aContiBlock3D2::aContiBlock3D2(), simlib3::aContiBlock3D3::aContiBlock3D3(), simlib3::AlgLoop::AlgLoop(), simlib3::Integrator::CtrInit(), simlib3::Status::CtrInit(), simlib3::Store::Enter(), Erlang(), Error(), simlib3::CalendarQueue::estimate_bucket_width(), simlib3::Frict::Frict(), Geom(), simlib3::SIMLIB_DelayBuffer::get(), simlib3::CalendarList::Get(), simlib3::CalendarQueue::Get(), simlib3::List::Get(), simlib3::CalendarList::GetFirst(), simlib3::CalendarQueue::GetFirst(), simlib3::Histogram::Histogram(), simlib3::Histogram::Histogram(), HyperGeom(), simlib3::Histogram::Init(), simlib3::Insv::Insv(), simlib3::IntegrationMethod::IntegrationMethod(), simlib3::Store::Leave(), simlib3::Lim::Lim(), simlib3::AlgLoopDetector::lock(), simlib3::Stat::MeanValue(), simlib3::TStat::MeanValue(), NegBin(), NegBinM(), simlib3::Parameter2D::operator=(), simlib3::Parameter3D::operator=(), simlib3::Link::Out(), Poisson(), simlib3::List::PostIns(), simlib3::List::PredIns(), simlib3::IntegrationMethod::Prepare(), simlib3::Qntzr::Qntzr(), simlib3::Facility::Release(), simlib3::Rline::Rline(), Run(), simlib3::SQS::ScheduleAt(), simlib3::CalendarList::ScheduleAt(), simlib3::CalendarQueue::ScheduleAt(), simlib3::IntegrationMethod::SearchMethod(), simlib3::CalendarQueue::SearchMinTime(), simlib3::Facility::Seize(), simlib3::AlgLoop::Set(), simlib3::AlgLoop::Set(), SetAccuracy(), simlib3::Store::SetCapacity(), simlib3::IntegrationMethod::SetMethod(), simlib3::MultiStepMethod::SetStarter(), simlib3::MultiStepMethod::SetStarter(), SetStep(), SIMLIB_Init(), simlib3::MultiStepMethod::SlavePtr(), simlib3::Stat::StdDev(), Stop(), THREAD_INTERRUPT_f(), Uniform(), simlib3::Semaphore::V(), simlib3::Iterations::Value(), simlib3::Bisect::Value(), simlib3::RegulaFalsi::Value(), simlib3::Newton::Value(), Weibul(), simlib3::Integrator::~Integrator(), simlib3::Link::~Link(), and simlib3::Status::~Status().
SIMLIB_Init()
void simlib3::SIMLIB_Init (double T0, double T1, unsigned version)
Definition at line 177 of file run.cc.
References _SetTime, CALL_HOOK, simlib3::SQS::Clear(), Dprintf, EndTime, InconsistentHeader, InitError, INITIALIZATION, InitInRunError, SIMLIB_ContinueInit(), SIMLIB_error(), SIMLIB_experiment_no, SIMLIB_MAXTIME, SIMLIB_MINTIME, SIMLIB_Phase, SIMLIB_version, SIMLIB_WUClear(), SIMULATION, StartTime, Time, and TwiceInitError.
Referenced by Init().
SIMLIB_RandomBase()
double simlib3::SIMLIB_RandomBase ()
Definition at line 75 of file random1.cc.
References MAXLONGINT, MULCONST, and SIMLIB_RandomSeed.
Referenced by SetBaseRandomGenerator().
SIMLIB_version_string()
const char * simlib3::SIMLIB_version_string ()
Get version of SIMLIB.
Returns
string with version of SIMLIB/C++
Definition at line 13 of file version.cc.
References SIMLIB_VERSION.
SIMLIB_warning() [1/2]
void simlib3::SIMLIB_warning (const char * fmt, ...)
print warning message and continue
print warnings
Definition at line 80 of file error.cc.
References _ERR_TXT, _Print(), and Time.
SIMLIB_warning() [2/2]
void simlib3::SIMLIB_warning (const enum _ErrEnum N)
print warning message and continue
print warnings
Definition at line 74 of file error.cc.
References _ErrMsg(), _Print(), _WARNING_TXT, and Time.
Referenced by Debug(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::Process::Into(), simlib3::TStat::operator()(), simlib3::Store::SetQueue(), simlib3::Facility::SetQueue(), simlib3::CalendarQueue::switchtocq(), simlib3::Iterations::Value(), simlib3::Bisect::Value(), simlib3::RegulaFalsi::Value(), and simlib3::Newton::Value().
SIMLIB_WUClear()
void simlib3::SIMLIB_WUClear ()
Definition at line 123 of file run.cc.
References CALL_HOOK.
Referenced by SIMLIB_Init().
Sin()
Input simlib3::Sin (Input x)
Definition at line 96 of file fun.cc.
Sqr()
Input simlib3::Sqr (Input x)
square function
Definition at line 233 of file continuous.cc.
Sqrt()
Input simlib3::Sqrt (Input x)
Definition at line 112 of file fun.cc.
Stop()
void simlib3::Stop ()
stop current simulation run
Definition at line 147 of file run.cc.
References Dprintf, SFunctionUseError, SIMLIB_error(), SIMLIB_Phase, SIMULATION, and StopFlag.
Tan()
Input simlib3::Tan (Input x)
Definition at line 98 of file fun.cc.
THREAD_INTERRUPT_f()
static void simlib3::THREAD_INTERRUPT_f () static
Definition at line 603 of file process.cc.
References ALLOC_CONTEXT, CANARY2, FREE_CONTEXT(), P_Context, P_DispatcherStatusBuffer, P_StackBase, P_StackSize, SIMLIB_error(), simlib3::P_Context_t::stack, simlib3::P_Context_t::status, and THREAD_DEBUG.
Triag()
double simlib3::Triag (double mod, double min, double max)
Definition at line 193 of file random2.cc.
References max(), min(), and Random().
Uniform()
double simlib3::Uniform (double l, double h)
Uniform distribution generator.
Parameters
l low limit
h high limit
Definition at line 71 of file random2.cc.
References BadUniformParam, Random(), and SIMLIB_error().
UnitVector() [1/2]
Input2D simlib3::UnitVector (Input2D x)
make unit vector from input (Abs(output_vec)==1)
Definition at line 388 of file simlib2D.cc.
UnitVector() [2/2]
Input3D simlib3::UnitVector (Input3D x)
make unit vector from input (Abs(output_vec)==1)
Definition at line 407 of file simlib3D.cc.
Weibul()
double simlib3::Weibul (double lambda, double alfa)
Weibul distribution generator.
Parameters
lambda
param alfa
Definition at line 94 of file random2.cc.
References Random(), SIMLIB_error(), and WeibullError.
WU_print()
void simlib3::WU_print ()
Definition at line 75 of file waitunti.cc.
Xpart() [1/2]
Input simlib3::Xpart (Input2D a)
get x part of (x,y) vector value
Definition at line 420 of file simlib2D.cc.
References simlib3::_XYpart::x.
Xpart() [2/2]
Input simlib3::Xpart (Input3D a)
get x part of (x,y,z) vector value
Definition at line 440 of file simlib3D.cc.
References simlib3::_XYZpart::x.
Ypart() [1/2]
Input simlib3::Ypart (Input2D a)
get y part of (x,y) vector value
Definition at line 421 of file simlib2D.cc.
References simlib3::_XYpart::y.
Ypart() [2/2]
Input simlib3::Ypart (Input3D a)
get y part of (x,y,z) vector value
Definition at line 441 of file simlib3D.cc.
References simlib3::_XYZpart::y.
Zpart()
Input simlib3::Zpart (Input3D a)
get z part of (x,y,z) vector value
Definition at line 442 of file simlib3D.cc.
References simlib3::_XYZpart::z.
Variable Documentation
_Errors
const char simlib3::_Errors[] static
Definition at line 13 of file errors.cc.
Referenced by _ErrMsg().
_T
class _Time simlib3::_T static
block – simulation time
Definition at line 274 of file continuous.cc.
abm4
ABM4 simlib3::abm4("abm4", "rkf5") ("abm4" , "rkf5")
Adams-Bashforth-Moulton, 4th order.
abm_ord
const int simlib3::abm_ord =4
Definition at line 20 of file ni_abm4.h.
Referenced by simlib3::ABM4::Integrate().
AbsoluteError
const double & simlib3::AbsoluteError =SIMLIB_AbsoluteError
max. abs. error of integration
max absolute error
Definition at line 53 of file intg.cc.
allocator
class simlib3::EventNoticeAllocator simlib3::allocator
Referenced by simlib3::EventNotice::Create(), simlib3::EventNotice::Destroy(), simlib3::CalendarListImplementation::~CalendarListImplementation(), and simlib3::CalendarQueue::~CalendarQueue().
atexit_array
SIMLIB_atexit_function_t simlib3::atexit_array[MAX_ATEXIT] = { 0, } static
Definition at line 23 of file atexit.cc.
Referenced by SIMLIB_atexit(), and SIMLIB_atexit_call().
COEF_PAR
const double simlib3::COEF_PAR = 1.5
Definition at line 540 of file calendar.cc.
Referenced by simlib3::CalendarQueue::Resize(), and simlib3::CalendarQueue::switchtocq().
counter
int simlib3::counter = 0 static
Definition at line 22 of file atexit.cc.
Referenced by simlib3::SIMLIB_module::Init(), simlib3::SIMLIB_module::SIMLIB_module(), and simlib3::SIMLIB_module::~SIMLIB_module().
Current
Entity *const & simlib3::Current = SIMLIB_Current
pointer to active (now running) entity
Definition at line 54 of file run.cc.
Referenced by simlib3::Barrier::Enter(), simlib3::Store::Enter(), simlib3::Semaphore::P(), simlib3::Facility::Seize(), and simlib3::Barrier::Wait().
EndTime
const double & simlib3::EndTime = SIMLIB_EndTime
time of simulation end
Definition at line 50 of file run.cc.
Referenced by Run(), and SIMLIB_Init().
euler
EULER simlib3::euler("euler") ("euler")
Euler method.
flag
bool simlib3::flag = false static
Definition at line 89 of file waitunti.cc.
Referenced by simlib3::WaitUntilList::GetCurrent(), simlib3::WaitUntilList::InsertCurrent(), simlib3::Facility::Release(), simlib3::Status::SetValid(), and simlib3::WaitUntilList::WU_hook().
fw
FW simlib3::fw("fw") ("fw")
Fowler-Warten (Warning: needs testing, do not use)
INICONST
const myint32 simlib3::INICONST = 1537L
Definition at line 48 of file random1.cc.
LIST_MAX
const unsigned simlib3::LIST_MAX = 512
Definition at line 535 of file calendar.cc.
Referenced by simlib3::CalendarQueue::ScheduleAt().
LIST_MIN
const unsigned simlib3::LIST_MIN = LIST_MAX/2
Definition at line 537 of file calendar.cc.
Referenced by simlib3::CalendarQueue::Get(), and simlib3::CalendarQueue::GetFirst().
MAX_ATEXIT
const int simlib3::MAX_ATEXIT = 10 static
Definition at line 21 of file atexit.cc.
Referenced by SIMLIB_atexit(), and SIMLIB_atexit_call().
MAXHISTOCOUNT
const unsigned simlib3::MAXHISTOCOUNT = 10000
Definition at line 30 of file histo.cc.
Referenced by simlib3::Histogram::Histogram(), simlib3::Histogram::Histogram(), and simlib3::Histogram::Init().
MAXLONGINT
const myint32 simlib3::MAXLONGINT = 0x7FFFFFFFUL
Definition at line 52 of file random1.cc.
Referenced by SIMLIB_RandomBase().
MaxStep
const double & simlib3::MaxStep =SIMLIB_MaxStep
maximal integration step
maximal step size
Definition at line 47 of file intg.cc.
MINBUCKETS
const unsigned simlib3::MINBUCKETS = LIST_MAX>4?LIST_MAX:4
Definition at line 536 of file calendar.cc.
Referenced by simlib3::CalendarQueue::Resize().
MinStep
const double & simlib3::MinStep =SIMLIB_MinStep
minimal integration step
minimal step size
Definition at line 46 of file intg.cc.
MUL_PAR
const double simlib3::MUL_PAR = 1.0
Definition at line 543 of file calendar.cc.
Referenced by simlib3::CalendarQueue::estimate_bucket_width(), and simlib3::CalendarQueue::switchtocq().
MULCONST
const myint32 simlib3::MULCONST = 1220703125L
Definition at line 49 of file random1.cc.
Referenced by SIMLIB_RandomBase().
name_dict
NameDict simlib3::name_dict static
Definition at line 66 of file object.cc.
Referenced by simlib3::SimObject::Name(), simlib3::SimObject::SetName(), and simlib3::SimObject::~SimObject().
NextTime
const double & simlib3::NextTime = SIMLIB_NextTime
next-event time
Definition at line 49 of file run.cc.
Referenced by simlib3::SQS::Clear(), simlib3::SQS::Get(), simlib3::SQS::GetFirst(), simlib3::IntegrationMethod::Prepare(), Run(), simlib3::SQS::ScheduleAt(), and simlib3::IntegrationMethod::Summarize().
OptStep
const double & simlib3::OptStep =SIMLIB_OptStep
optimal integration step
optimal step size
Definition at line 49 of file intg.cc.
Referenced by simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), and simlib3::RKF8::Integrate().
OutFile
class simlib3::_FileWrap simlib3::OutFile
Referenced by _Print(), Error(), Print(), and SetOutput().
P_Context
P_Context_t* volatile simlib3::P_Context = 0 static
temporary global process state
Definition at line 132 of file process.cc.
Referenced by simlib3::Process::_Run(), FREE_CONTEXT(), and THREAD_INTERRUPT_f().
P_DispatcherStatusBuffer
jmp_buf simlib3::P_DispatcherStatusBuffer static
setjmp() state before dispatch
Definition at line 128 of file process.cc.
Referenced by simlib3::Process::_Run(), and THREAD_INTERRUPT_f().
P_StackBase
char* volatile simlib3::P_StackBase = 0 static
global start of stack area
Definition at line 129 of file process.cc.
Referenced by simlib3::Process::_Run(), and THREAD_INTERRUPT_f().
P_StackBase2
char* volatile simlib3::P_StackBase2 = 0 static
for checking start of stack
Definition at line 130 of file process.cc.
Referenced by simlib3::Process::_Run().
P_StackSize
volatile size_t simlib3::P_StackSize = 0 static
temporary global stack size
Definition at line 133 of file process.cc.
Referenced by simlib3::Process::_Run(), and THREAD_INTERRUPT_f().
Phase
const SIMLIB_Phase_t & simlib3::Phase = SIMLIB_Phase
This variable contains the current phase of experiment (used for internal checking)
Definition at line 58 of file run.cc.
RelativeError
const double & simlib3::RelativeError =SIMLIB_RelativeError
max. rel. error
max relative error
Definition at line 54 of file intg.cc.
rke
RKE simlib3::rke("rke") ("rke")
Runge-Kutta-England, 4th order?
rkf3
RKF3 simlib3::rkf3("rkf3") ("rkf3")
Runge-Kutta-Fehlberg, 3rd order.
rkf5
RKF5 simlib3::rkf5("rkf5") ("rkf5")
Runge-Kutta-Fehlberg, 5th order.
rkf8
RKF8 simlib3::rkf8("rkf8") ("rkf8")
Runge-Kutta-Fehlberg, 8th order.
SIGNBIT
const myint32 simlib3::SIGNBIT = 0x80000000UL
Definition at line 53 of file random1.cc.
SIMLIB_AbsoluteError
double simlib3::SIMLIB_AbsoluteError =0
absolute error
Definition at line 42 of file intg.cc.
Referenced by simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), and SetAccuracy().
SIMLIB_ConditionFlag
bool simlib3::SIMLIB_ConditionFlag = false
Definition at line 30 of file cond.cc.
Referenced by simlib3::aCondition::InitAll(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::IntegrationMethod::IsConditionFlag(), simlib3::IntegrationMethod::Prepare(), SIMLIB_DoConditions(), simlib3::Condition::Test(), and simlib3::aCondition::TestAll().
SIMLIB_ContractStep
double simlib3::SIMLIB_ContractStep = SIMLIB_MAXTIME
requested step size
Definition at line 59 of file intg.cc.
Referenced by ContractStep(), simlib3::IntegrationMethod::InitStep(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Iterate(), and simlib3::IntegrationMethod::StateCond().
SIMLIB_ContractStepFlag
bool simlib3::SIMLIB_ContractStepFlag = false
requests shorter step
Definition at line 58 of file intg.cc.
Referenced by ContractStep(), ContractStep(), simlib3::IntegrationMethod::InitStep(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Iterate(), and simlib3::IntegrationMethod::StateCond().
SIMLIB_Current
Entity * simlib3::SIMLIB_Current = NULL
Definition at line 53 of file run.cc.
Referenced by simlib3::Process::_WaitUntil(), simlib3::WaitUntilList::InsertCurrent(), Run(), simlib3::Event::Terminate(), simlib3::Entity::Terminate(), and simlib3::WaitUntilList::WU_hook().
SIMLIB_debug_flag
unsigned long simlib3::SIMLIB_debug_flag = 0UL
Definition at line 32 of file debug.cc.
Referenced by Debug().
SIMLIB_DeltaTime
double simlib3::SIMLIB_DeltaTime
Time-SIMLIB_StepStartTime.
Definition at line 35 of file intg.cc.
Referenced by simlib3::IntegrationMethod::FunCall(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Iterate(), simlib3::IntegrationMethod::Prepare(), SIMLIB_ContinueInit(), and simlib3::IntegrationMethod::Summarize().
SIMLIB_DynamicFlag
bool simlib3::SIMLIB_DynamicFlag = false
in dynamic section
Definition at line 56 of file intg.cc.
Referenced by simlib3::Integrator::CtrInit(), simlib3::Status::CtrInit(), simlib3::IntegrationMethod::SetMethod(), simlib3::MultiStepMethod::SetStarter(), SIMLIB_ContinueInit(), SIMLIB_error(), SIMLIB_error(), simlib3::IntegrationMethod::StepSim(), simlib3::Condition::Test(), simlib3::Integrator::~Integrator(), and simlib3::Status::~Status().
SIMLIB_EndTime
double simlib3::SIMLIB_EndTime
Definition at line 43 of file run.cc.
SIMLIB_Entity_Count
unsigned long simlib3::SIMLIB_Entity_Count = 0L static
current number of entities in model
Definition at line 27 of file entity.cc.
SIMLIB_ERRNO
int simlib3::SIMLIB_ERRNO =0
Definition at line 32 of file intg.cc.
Referenced by simlib3::IntegrationMethod::GetErrNo(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), and SetErrNo().
SIMLIB_experiment_no
unsigned long simlib3::SIMLIB_experiment_no = 0
Definition at line 61 of file run.cc.
Referenced by SIMLIB_Init().
SIMLIB_IMPLEMENTATION
simlib3::SIMLIB_IMPLEMENTATION
Definition at line 34 of file algloop.cc.
SIMLIB_Integrator_0input
Constant simlib3::SIMLIB_Integrator_0input(0) (0)
dummy input with zero value
SIMLIB_MaxStep
double simlib3::SIMLIB_MaxStep =1
max. step
Definition at line 39 of file intg.cc.
Referenced by simlib3::IntegrationMethod::InitStep(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), SetStep(), and SIMLIB_ContinueInit().
SIMLIB_MAXTIME
const double simlib3::SIMLIB_MAXTIME = 1.0e30
maximum time (1e30 works for float, too)
Definition at line 148 of file simlib.h.
Referenced by simlib3::Entity::ActivationTime(), simlib3::CalendarList::CalendarList(), simlib3::CalendarQueue::CalendarQueue(), simlib3::CalendarList::clear(), simlib3::CalendarQueue::clear(), simlib3::CalendarQueue::estimate_bucket_width(), simlib3::CalendarList::Get(), simlib3::CalendarQueue::Get(), simlib3::CalendarList::GetFirst(), simlib3::CalendarQueue::GetFirst(), simlib3::CalendarQueue::SearchMinTime(), and SIMLIB_Init().
SIMLIB_MinStep
double simlib3::SIMLIB_MinStep =1e-10
minimal step
Definition at line 38 of file intg.cc.
Referenced by ContractStep(), simlib3::IntegrationMethod::InitStep(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Iterate(), SetStep(), and simlib3::IntegrationMethod::StateCond().
SIMLIB_MINTIME
const double simlib3::SIMLIB_MINTIME = 0.0
minimal time value
Definition at line 147 of file simlib.h.
Referenced by SIMLIB_Init().
SIMLIB_module_id
SIMLIB_module simlib3::SIMLIB_module_id static
Create single global registration object in each SIMLIB module.
Should be first initialized object in the module
Definition at line 73 of file internal.h.
SIMLIB_NextTime
double simlib3::SIMLIB_NextTime
Definition at line 42 of file run.cc.
SIMLIB_OptStep
double simlib3::SIMLIB_OptStep
optimal step
Definition at line 37 of file intg.cc.
Referenced by simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Prepare(), simlib3::IntegrationMethod::SetOptStep(), and SIMLIB_ContinueInit().
SIMLIB_Phase
SIMLIB_Phase_t simlib3::SIMLIB_Phase = START
Definition at line 57 of file run.cc.
Referenced by Abort(), simlib3::Parameter2D::operator=(), simlib3::Parameter3D::operator=(), Run(), SIMLIB_error(), SIMLIB_error(), SIMLIB_Init(), and Stop().
SIMLIB_RandomBasePtr
double(* simlib3::SIMLIB_RandomBasePtr) () () = SIMLIB_RandomBase static
Definition at line 88 of file random1.cc.
Referenced by Random(), and SetBaseRandomGenerator().
SIMLIB_RandomSeed
myint32 simlib3::SIMLIB_RandomSeed = INICONST static
Definition at line 59 of file random1.cc.
Referenced by RandomSeed(), and SIMLIB_RandomBase().
SIMLIB_RelativeError
double simlib3::SIMLIB_RelativeError =0.001
relative error
Definition at line 43 of file intg.cc.
Referenced by simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), and SetAccuracy().
SIMLIB_ResetStatus
bool simlib3::SIMLIB_ResetStatus = false
flag set if there is a need for integration method restart
Definition at line 86 of file intg.cc.
Referenced by simlib3::Integrator::CtrInit(), simlib3::Status::CtrInit(), simlib3::Integrator::Init(), simlib3::IntegrationMethod::Prepare(), Run(), simlib3::Integrator::Set(), and SIMLIB_DoConditions().
SIMLIB_run_statistics
SIMLIB_statistics_t simlib3::SIMLIB_run_statistics static
Definition at line 77 of file run.cc.
Referenced by Run().
SIMLIB_StartTime
double simlib3::SIMLIB_StartTime
Definition at line 40 of file run.cc.
SIMLIB_statistics
const SIMLIB_statistics_t & simlib3::SIMLIB_statistics = SIMLIB_run_statistics
interface to internal run-time statistics structure
Definition at line 78 of file run.cc.
SIMLIB_StepSize
double simlib3::SIMLIB_StepSize
actual step
Definition at line 40 of file intg.cc.
Referenced by simlib3::IntegrationMethod::FunCall(), simlib3::IntegrationMethod::InitStep(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Iterate(), simlib3::IntegrationMethod::Prepare(), simlib3::IntegrationMethod::SetStepSize(), and simlib3::IntegrationMethod::StateCond().
SIMLIB_StepStartTime
double simlib3::SIMLIB_StepStartTime
last step time
Definition at line 34 of file intg.cc.
Referenced by ContractStep(), simlib3::IntegrationMethod::FunCall(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Iterate(), simlib3::IntegrationMethod::Prepare(), simlib3::StatusMethod::RestoreState(), SIMLIB_ContinueInit(), and simlib3::IntegrationMethod::Summarize().
SIMLIB_Time
double simlib3::SIMLIB_Time
Definition at line 209 of file internal.h.
Referenced by SIMLIB_ContinueInit().
SIMLIB_version
const unsigned simlib3::SIMLIB_version = __SIMLIB__
library version
Definition at line 9 of file version.cc.
Referenced by SIMLIB_Init().
SimObject_allocated
bool simlib3::SimObject_allocated = false static
Definition at line 24 of file object.cc.
Referenced by simlib3::SimObject::operator new(), and simlib3::SimObject::SimObject().
StartTime
const double & simlib3::StartTime = SIMLIB_StartTime
time of simulation start
Definition at line 47 of file run.cc.
Referenced by Run(), and SIMLIB_Init().
StepSize
const double & simlib3::StepSize =SIMLIB_StepSize
actual integration step
current step size
Definition at line 48 of file intg.cc.
Referenced by Run().
StopFlag
bool simlib3::StopFlag = false static
Definition at line 83 of file run.cc.
Referenced by Run(), and Stop().
T
aContiBlock & simlib3::T = _T
simulation time block reference
model time (continuous block)
Definition at line 276 of file continuous.cc.
Referenced by Sample().
Time
const double & simlib3::Time = SIMLIB_Time
model time (is NOT the block)
Definition at line 48 of file run.cc.
Referenced by simlib3::Entity::Activate(), TestProcess::Behavior(), simlib3::Sampler::Behavior(), simlib3::ZDelayTimer::Behavior(), simlib3::TStat::Clear(), simlib3::IntegrationMethod::FunCall(), simlib3::Queue::Get(), simlib3::Delay::Init(), simlib3::ABM4::Integrate(), simlib3::EULER::Integrate(), simlib3::FW::Integrate(), simlib3::RKE::Integrate(), simlib3::RKF3::Integrate(), simlib3::RKF5::Integrate(), simlib3::RKF8::Integrate(), simlib3::IntegrationMethod::Iterate(), main(), simlib3::TStat::MeanValue(), simlib3::TStat::operator()(), simlib3::TStat::Output(), simlib3::Queue::Output(), simlib3::Facility::Output(), simlib3::Store::Output(), simlib3::Queue::PredIns(), simlib3::IntegrationMethod::Prepare(), simlib3::Facility::Release(), simlib3::StatusMethod::RestoreState(), Run(), simlib3::Delay::Sample(), simlib3::Sampler::Sample(), simlib3::CalendarList::ScheduleAt(), simlib3::CalendarQueue::ScheduleAt(), simlib3::Facility::Seize(), simlib3::Delay::Set(), SIMLIB_error(), SIMLIB_error(), SIMLIB_error(), SIMLIB_Init(), SIMLIB_warning(), SIMLIB_warning(), simlib3::IntegrationMethod::StepSim(), simlib3::Sampler::Stop(), simlib3::IntegrationMethod::Summarize(), simlib3::_Time::Value(), simlib3::Delay::Value(), simlib3::Barrier::Wait(), and simlib3::Process::Wait().
Zero2D
Constant2D simlib3::Zero2D(0, 0) (0 , 0) static
Zero3D
Constant3D simlib3::Zero3D(0, 0, 0) (0 , 0 , 0) static