SIMLIB/C++: simlib3::Delay::Buffer Struct Reference
simlib3::Delay::Buffer Struct Reference abstract
abstract base class for delayed signal samples storage
Public Member Functions
virtual void put (double value, double time)=0
store value
virtual double get (double time)=0
read interpolated value
virtual void clear ()=0
initialize buffer
virtual ~Buffer ()
Detailed Description
abstract base class for delayed signal samples storage
Definition at line 91 of file delay.cc.
Constructor & Destructor Documentation
~Buffer()
virtual simlib3::Delay::Buffer::~Buffer () inline virtual
Definition at line 95 of file delay.cc.
Member Function Documentation
clear()
virtual void simlib3::Delay::Buffer::clear () pure virtual
initialize buffer
Implemented in simlib3::SIMLIB_DelayBuffer.
Referenced by simlib3::Delay::Init().
get()
virtual double simlib3::Delay::Buffer::get (double time) pure virtual
read interpolated value
Implemented in simlib3::SIMLIB_DelayBuffer.
Referenced by simlib3::Delay::Value().
put()
virtual void simlib3::Delay::Buffer::put (double value, double time) pure virtual
store value
Implemented in simlib3::SIMLIB_DelayBuffer.
Referenced by simlib3::Delay::Init(), and simlib3::Delay::Sample().
The documentation for this struct was generated from the following file:
src/delay.cc