SIMLIB/C++: simlib3::EventNoticeLinkBase Struct Reference
simlib3::EventNoticeLinkBase Struct Reference
calendar item - PRIVATE for any implementation
we use double-linked circular list
Public Member Functions
EventNoticeLinkBase ()
void remove ()
remove from calendar list
void insert (EventNoticeLinkBase *p)
insert at position p
Public Attributes
EventNoticeLinkBase * pred
previous object in list
EventNoticeLinkBase * succ
next object in list
Detailed Description
calendar item - PRIVATE for any implementation
we use double-linked circular list
Definition at line 117 of file calendar.cc.
Constructor & Destructor Documentation
EventNoticeLinkBase()
simlib3::EventNoticeLinkBase::EventNoticeLinkBase () inline
Definition at line 122 of file calendar.cc.
Member Function Documentation
insert()
void simlib3::EventNoticeLinkBase::insert (EventNoticeLinkBase * p) inline
insert at position p
Definition at line 132 of file calendar.cc.
References pred, remove(), and succ.
Referenced by simlib3::CalendarListImplementation::insert(), and simlib3::CalendarListImplementation::insert_extracted().
remove()
void simlib3::EventNoticeLinkBase::remove () inline
remove from calendar list
Definition at line 125 of file calendar.cc.
References pred, and succ.
Referenced by simlib3::EventNotice::Create(), simlib3::CalendarListImplementation::extract_first(), simlib3::EventNoticeAllocator::free(), insert(), and simlib3::EventNotice::~EventNotice().
Member Data Documentation
pred
EventNoticeLinkBase* simlib3::EventNoticeLinkBase::pred
previous object in list
Definition at line 119 of file calendar.cc.
Referenced by simlib3::EventNoticeAllocator::free(), insert(), simlib3::CalendarListImplementation::iterator::operator--(), remove(), simlib3::EventNotice::Set(), and simlib3::EventNotice::~EventNotice().
succ
EventNoticeLinkBase* simlib3::EventNoticeLinkBase::succ
next object in list
Definition at line 120 of file calendar.cc.
Referenced by simlib3::EventNoticeAllocator::alloc(), simlib3::CalendarListImplementation::begin(), simlib3::EventNoticeAllocator::clear(), simlib3::EventNoticeAllocator::free(), insert(), simlib3::CalendarListImplementation::iterator::operator++(), remove(), and simlib3::EventNotice::Set().
The documentation for this struct was generated from the following file:
src/calendar.cc