SIMLIB/C++: simlib3::EventNotice Struct Reference
simlib3::EventNotice Struct Reference
activation record
Public Member Functions
EventNotice (Entity *p, double t)
void create_reverse_link ()
create link from entity to activation record
void delete_reverse_link ()
delete link from entity to activation record
~EventNotice ()
void Set (Entity *e, double t)
set new values to existing (unlinked) record
Public Member Functions inherited from simlib3::EventNoticeLinkBase
EventNoticeLinkBase ()
void remove ()
remove from calendar list
void insert (EventNoticeLinkBase *p)
insert at position p
Static Public Member Functions
static EventNotice * Create (Entity *p, double t)
creates new EventNotice,
static void Destroy (EventNotice *en)
delete EventNotice, if inserted in calendar remove it first
Public Attributes
Entity * entity
which entity is scheduled
double time
activation time of entity
Entity::Priority_t priority
priority at the time of scheduling
Public Attributes inherited from simlib3::EventNoticeLinkBase
EventNoticeLinkBase * pred
previous object in list
EventNoticeLinkBase * succ
next object in list
Private Member Functions
EventNotice (const EventNotice &)
EventNotice & operator= (const EventNotice &)
Detailed Description
activation record
Definition at line 145 of file calendar.cc.
Constructor & Destructor Documentation
EventNotice() [1/2]
simlib3::EventNotice::EventNotice (Entity * p, double t) inline
Definition at line 153 of file calendar.cc.
References create_reverse_link().
~EventNotice()
simlib3::EventNotice::~EventNotice () inline
Definition at line 171 of file calendar.cc.
References delete_reverse_link(), simlib3::EventNoticeLinkBase::pred, and simlib3::EventNoticeLinkBase::remove().
EventNotice() [2/2]
simlib3::EventNotice::EventNotice (const EventNotice &) private
Member Function Documentation
Create()
EventNotice * simlib3::EventNotice::Create (Entity * p, double t) inline static
creates new EventNotice,
Definition at line 413 of file calendar.cc.
References simlib3::EventNoticeAllocator::alloc(), simlib3::allocator, simlib3::Entity::GetEventNotice(), priority, simlib3::Entity::Priority, simlib3::EventNoticeLinkBase::remove(), t, and time.
Referenced by simlib3::CalendarListImplementation::insert().
create_reverse_link()
void simlib3::EventNotice::create_reverse_link () inline
create link from entity to activation record
Definition at line 163 of file calendar.cc.
References simlib3::Entity::_evn, and entity.
Referenced by EventNotice(), and Set().
delete_reverse_link()
void simlib3::EventNotice::delete_reverse_link () inline
delete link from entity to activation record
Definition at line 167 of file calendar.cc.
References simlib3::Entity::_evn, and entity.
Referenced by simlib3::EventNoticeAllocator::free(), and ~EventNotice().
Destroy()
void simlib3::EventNotice::Destroy (EventNotice * en) inline static
delete EventNotice, if inserted in calendar remove it first
Definition at line 435 of file calendar.cc.
References simlib3::allocator, and simlib3::EventNoticeAllocator::free().
Referenced by simlib3::CalendarListImplementation::remove(), and simlib3::CalendarListImplementation::remove_first().
operator=()
EventNotice & simlib3::EventNotice::operator= (const EventNotice &) private
Set()
void simlib3::EventNotice::Set (Entity * e, double t) inline
set new values to existing (unlinked) record
Definition at line 179 of file calendar.cc.
References create_reverse_link(), entity, simlib3::EventNoticeLinkBase::pred, priority, simlib3::Entity::Priority, simlib3::EventNoticeLinkBase::succ, t, and time.
Referenced by simlib3::EventNoticeAllocator::alloc().
Member Data Documentation
entity
Entity* simlib3::EventNotice::entity
which entity is scheduled
Definition at line 147 of file calendar.cc.
Referenced by create_reverse_link(), delete_reverse_link(), simlib3::CalendarListImplementation::remove_first(), and Set().
priority
Entity::Priority_t simlib3::EventNotice::priority
priority at the time of scheduling
Definition at line 151 of file calendar.cc.
Referenced by Create(), simlib3::CalendarListImplementation::search(), and Set().
time
double simlib3::EventNotice::time
activation time of entity
Definition at line 149 of file calendar.cc.
Referenced by simlib3::Entity::ActivationTime(), Create(), simlib3::CalendarQueue::Resize(), simlib3::CalendarListImplementation::search(), Set(), and simlib3::CalendarQueue::switchtocq().
The documentation for this struct was generated from the following file:
src/calendar.cc